Fix mobile browser back button to act the same as header button in menu.
scandipwa/scandipwa pull request #1859
Opened 2020-12-10 15:25 UTC by polander

Also previous visited categories are saved upon component unmount so user can go back through them by pressing back button.

2020-12-14 15:00 UTC, yeegor requested changes
Clicking the back button in the browser equals calling `history.pop()`

I propose to utilize this mechanic in order to prevent any additional prop drilling and logic handling throughout the application. If it is possible to implement without introducing the activeMenuItemsStack prop, we should do that.

Maybe we can push an entry to the history each time the back button is rendered in the header? Or something like that? Maybe some wrapper around the goBack function passed to that button should get added?

The current solution complicates the application, the goBack logic is not encapsulated inside of the history-related components, which can make some confusion. Please, investigated the proposed option and notify what you come to :)

2020-12-14 19:10 UTC, polander commented
I had some crashing issues with `history.pop()`. But I will look for it again for sure.

activeMenuItemsStack prop is necessary to get last item stack on component mount, so user can return to previous selected subcategory when come back to menu from other component. Actually, this feature wasn't meant in the task, so I a little over-did it. I will remove this feature if needed, then activeMenuItemStack will become a local state and not a prop.

If history entry will be pushed each time back button is rendered, then user will have to press back button multiple times if returned to Menu component to go back. I am not sure it is ok ;D

2020-12-14 19:48 UTC, polander commented
Hope I understand correctly what you meant.

2020-12-23 09:36 UTC, yeegor reviewed
Shouldn't `historyBackHook`and `handleHeaderBackClick` do exactly the same? I did not look in-depth, but it sounds like they should when reading the assignment.

2020-12-23 11:46 UTC, polander commented
> Shouldn't `historyBackHook`and `handleHeaderBackClick` do exactly the same? I did not look in-depth, but it sounds like they should when reading the assignment.

`historyBackHook` will not go back itself, it is just a watcher.  I created `handleHeaderBackClick` as a `history.goBack()` wrapper refering to:

> Maybe some wrapper around the goBack function passed to that button should get added?

2020-12-28 12:12 UTC, alfredsgenkins requested changes
This does not seem as a proper implementation to me, I would redo it using the history state update, by keeping the number of sub-menus in the state.

2020-12-28 12:12 UTC, alfredsgenkins commented on packages/scandipwa/src/component/Menu/Menu.config.js
> +export const SUBCATEGORY_URL = '/menu/subcategory';
I think this could have been easily done without introducing the new URL, by manipulating the history state, but OK

2020-12-28 12:12 UTC, alfredsgenkins commented on packages/scandipwa/src/component/Menu/Menu.container.js
> +        history.push(appendWithStoreCode(`${ SUBCATEGORY_URL }`));
This appears to me as a thing which would only work once, no?

2020-12-28 12:12 UTC, alfredsgenkins commented on packages/scandipwa/src/component/Menu/Menu.container.js
> +        history.push(appendWithStoreCode(`${ SUBCATEGORY_URL }`));
I mean 10 deep menu will not work?

2020-12-28 13:44 UTC, alfredsgenkins commented
I will do that myself.

2020-12-28 13:44 UTC, closed without merging