Modified CartPage items title
scandipwa/scandipwa pull request #2097
Opened 2021-01-15 07:23 UTC by winniepukki

2021-01-19 11:51 UTC, alfredsgenkins requested changes

2021-01-19 11:51 UTC, alfredsgenkins commented on packages/scandipwa/src/route/CartPage/CartPage.container.js
> +            const title = `${ items_qty || '0' } Item(s)`;
This string is not translated, please add translation to it!

2021-01-19 20:55 UTC, winniepukki commented
Changes from [the following](https://github.com/winniepukki/scandipwa/tree/1843-cart-items-mobile-title) pull request don't get to here

2021-01-20 09:55 UTC, alfredsgenkins commented
The issue was not resolved, why did you marked it this way?

2021-02-03 17:27 UTC, closed without merging

2021-02-03 17:33 UTC, winniepukki commented
> Changes from [the following](https://github.com/winniepukki/scandipwa/tree/1843-cart-items-mobile-title) pull request don't get to here

Closed after the following issue