#2099 - Fixed undefined word in address table title
scandipwa/scandipwa pull request #2104
Opened 2021-01-17 17:27 UTC by vromash

Fixed  #2099

2021-01-18 14:18 UTC, alfredsgenkins requested changes

2021-01-18 14:18 UTC, alfredsgenkins commented on packages/scandipwa/src/component/MyAccountAddressBook/MyAccountAddressBook.component.js
> +              title={ __(`Address #${addressNumber} ${postfix}`) }
This won't work, as translations may only take in static string. Something else is an issue in this case.

2021-01-19 11:24 UTC, vromash commented
It was fixed in i18n package here: https://github.com/scandipwa/create-scandipwa-app/commit/c04aa648fd95e7e368e2eb4edeca771c44c12bce

2021-01-19 11:24 UTC, closed without merging

2021-01-25 12:01 UTC, yeegor commented
Yes.