Changed price display and position settings
scandipwa/scandipwa pull request #2121
Opened 2021-01-25 19:47 UTC by winniepukki

2021-02-01 13:51 UTC, alfredsgenkins requested changes

2021-02-01 13:51 UTC, alfredsgenkins commented on packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.component.js
> +            <strong style={ { display: 'inline-block' } }>
Why not just add this in style? In-lining prevents for further modification in parent themes.

2021-02-11 11:02 UTC, yeegor approved these changes
OK

2021-02-11 11:11 UTC, alfredsgenkins approved these changes

2021-02-11 11:12 UTC, merged