Updated login/register/forgot password
scandipwa/scandipwa pull request #2124
Opened 2021-01-26 10:27 UTC by IvansZuks

2021-01-27 12:09 UTC, aleksandrakorolova commented
Please add space after the word 'benefits:' ('...benefits: check..') 
Now nothing happens if user submitted empty form => Please, return the error 'This field is required!' when submitting empty form (or empty field stays in this form). 
https://drive.google.com/file/d/1rGTRwhlpGKlcPEpcYJs__vSBWV6idsuZ/view?usp=sharing

2021-02-02 13:45 UTC, IvansZuks commented
@aleksandrakorolova Spaces are added. Validation of form is SWPWA v4 issue and it's not connected with my code

2021-02-04 11:43 UTC, yeegor requested changes
Overall, very nice :)
Just one small thing:

1. Prefer using CSS over `hr`, these HTML elements is more of a deprecated legacy than a good practice

2021-02-04 11:43 UTC, yeegor commented on packages/scandipwa/src/route/ForgotPassword/ForgotPassword.component.js
> +                <hr />
See final review

2021-02-04 11:43 UTC, yeegor commented on packages/scandipwa/src/route/ForgotPassword/ForgotPassword.component.js
> +                <hr />
See final review

2021-02-04 11:43 UTC, yeegor commented on packages/scandipwa/src/route/ForgotPassword/ForgotPassword.component.js
> +                <hr />
See final review

2021-02-04 11:43 UTC, yeegor commented on packages/scandipwa/src/route/CreateAccount/CreateAccount.style.scss
> +        }
See final review

2021-02-04 11:43 UTC, yeegor commented on packages/scandipwa/src/route/CreateAccount/CreateAccount.component.js
> +                <hr />
See final review

2021-02-04 11:43 UTC, yeegor commented on packages/scandipwa/src/route/CreateAccount/CreateAccount.component.js
> +                <hr />
See final review

2021-02-04 11:43 UTC, yeegor commented on packages/scandipwa/src/route/CreateAccount/CreateAccount.component.js
> +                <hr />
See final review

2021-02-04 11:43 UTC, yeegor commented on packages/scandipwa/src/route/ForgotPassword/ForgotPassword.style.scss
> +        }
See final review

2021-02-04 11:43 UTC, yeegor commented on packages/scandipwa/src/route/LoginAccount/LoginAccount.component.js
> +                <hr />
See final review

2021-02-04 11:43 UTC, yeegor commented on packages/scandipwa/src/route/LoginAccount/LoginAccount.component.js
> +                <hr />
See final review

2021-02-04 11:43 UTC, yeegor commented on packages/scandipwa/src/route/LoginAccount/LoginAccount.container.js
> +        history.replace(appendWithStoreCode(`/${ FORGOT_PASSWORD }`));
Won't this work without `/`? Just `appendWithStoreCode(FORGOT_PASSWORD)`

2021-02-04 11:43 UTC, yeegor commented on packages/scandipwa/src/route/LoginAccount/LoginAccount.style.scss
> +        }
See final review

2021-02-11 11:05 UTC, yeegor approved these changes
Good!

2021-02-11 11:12 UTC, merged