Support for autofill for city when entering zipcode
scandipwa/scandipwa pull request #2152
Opened 2021-02-01 19:23 UTC by teodormoq

2021-02-05 15:02 UTC, yeegor requested changes

2021-02-05 15:02 UTC, yeegor commented on packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.component.js
> +                    /** @namespace Sofacompany/Route/Checkout/Container/fetch/then/then */
Invalid namespaces here

2021-02-05 15:02 UTC, yeegor commented on packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.component.js
> +                    }
No data fetches are allowed in the components. If you wish to perform a data fetch on React level - you do that in the container.
But, consider moving this data retrieval into some util function and calling it from there. Who knows where we'll need this in the future :) Let's keep it as reusable as possible.

2021-02-09 15:34 UTC, yeegor requested changes
Minor change necessary. Use eslint plugin to provide the namespace, please.

2021-02-09 15:34 UTC, yeegor commented on packages/scandipwa/src/util/Address/index.js
> +export const getCityFromZipcode = (countryId, value) => {
Missing namespace here

2021-02-09 15:34 UTC, yeegor commented on packages/scandipwa/src/util/Address/index.js
> +        .then(
Missing namespace also here, and below.

2021-03-03 16:23 UTC, yeegor approved these changes
Legit! Thank you for this contribution!

2021-03-03 16:35 UTC, merged

2021-03-10 10:45 UTC, aleksandrakorolova commented
Hi @teodormoq 
I tested this functional but autofill doesn't work for me. Maybe I did something wrong or something missing
I entered zip code in form and nothing happens. Can you help me?

2021-03-10 13:30 UTC, teodormoq commented
> Hi @teodormoq
> I tested this functional but autofill doesn't work for me. Maybe I did something wrong or something missing
> I entered zip code in form and nothing happens. Can you help me?

Hi @aleksandrakorolova do you have a url i can test on?

2021-03-10 13:50 UTC, aleksandrakorolova commented
@teodormoq https://master.d25kd40decjpue.amplifyapp.com/

2021-03-10 14:02 UTC, teodormoq commented
> @teodormoq https://master.d25kd40decjpue.amplifyapp.com/

Hi @aleksandrakorolova 
yes i can see that now, we need to change:
http://api.zippopotam.us/${countryId}/${value}
to
https://api.zippopotam.us/${countryId}/${value}

so its with https instead of only http.
Currently i dont really have time to change it, can you get someone to fix this? :)

2021-03-11 09:23 UTC, aleksandrakorolova commented
@teodormoq 
Ok, I will create task for this
Thank you