Change Breadcrumbs-List height to 100% so it fits Breadcrumbs
scandipwa/scandipwa pull request #2194
Opened 2021-02-15 10:33 UTC by Scandi-Andy

2021-02-15 10:45 UTC, Scandi-Andy commented
Issue: https://github.com/scandipwa/scandipwa/issues/2172

2021-02-15 14:53 UTC, winniepukki requested changes

2021-02-15 14:53 UTC, winniepukki commented on packages/scandipwa/src/component/Breadcrumbs/Breadcrumbs.style.scss
> +        height: 100%;
Actually, there is no need in defining height for the desktop viewport at all

2021-03-09 22:51 UTC, winniepukki commented
Closing as a [duplicate PR](https://github.com/scandipwa/scandipwa/pull/2195/commits/fe2a883cbb8b9b13b024772d1ae5b71cfc79dd49)

2021-03-09 22:51 UTC, closed without merging