Feature/1479/wishlist disable
scandipwa/scandipwa pull request #2343
Opened 2021-03-23 07:22 UTC by tatiana-scandi

Issue: https://github.com/scandipwa/scandipwa/issues/1479

Related PR: https://github.com/scandipwa/store-graphql/pull/19 (**BACKEND NEEDS TO BE MERGED FIRST**)

Changes made:
- Wishlist button hidden on Product page
- Wishlist button hidden on Category page
- Wishlist hidden in left menu in My account
- Fixed error with links `/my-account/<invalid-url>` leading to an error. Now such links redirect to `Dashboard`. The problem was that even if URL is invalid, it was set to state as `activeTab`, and it lead to errors when other pieces of code referenced it like `tab_map[activeTab]` or in a similar way. The solution was to check new active tab URL validity before setting to state. 

<img width="639" alt="Something+went+wrong++Scandipwa+2021-03-22+22-45-35" src="https://user-images.githubusercontent.com/79456428/112107500-10fe1200-8bc0-11eb-8f2c-290e256bd05b.png">

- Added redirect from `/my-account/my-wishlist` to `/my-account/dashboard`, if wishlist is disabled
- extracted `tabMap` to config in order to be able to easier reuse it between static and non static methods (+ it looks reasonable to place such data in config)
- added `isWishlistEnabled` condition to `_syncWishlistWithBE` method to skip fetching wishlist data in case wishlist is disabled

2021-03-25 13:51 UTC, alfredsgenkins requested changes

2021-03-25 13:51 UTC, alfredsgenkins commented on packages/scandipwa/src/route/MyAccount/MyAccount.config.js
> +};
Please keep it as a property. This makes this code upluggable.

2021-03-25 14:32 UTC, tatiana-scandi commented
@alfredsgenkins I moved it back to a property, yet I wouldn't mind a bit more detailed explanation why exactly it makes the code unpluggable and what cases should be avoided in the future. Is it the fact that as part of config `TAB_MAP` doesn't belong to any namespace?

2021-03-25 14:33 UTC, alfredsgenkins commented
Yes :)

2021-04-27 09:58 UTC, alfredsgenkins approved these changes

2021-04-28 11:06 UTC, merged