Bugfix #2400
scandipwa/scandipwa pull request #2410
Opened 2021-03-30 09:36 UTC by vladi-j

Issue: #2400 

1. Samples title is displayed only if samples exist
2. Instead of star, text: "This field is required!" is displayed
3. Negotiated to implement indent as in luma - big indent and not bold link
4. Link option is in line with other elements

2021-03-30 12:19 UTC, zans-laksa commented on packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.component.js
> +
Please remove empty line.

2021-03-30 12:22 UTC, zans-laksa commented on packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.component.js
> +            { this.renderRequired(isRequired) }
Please indent this.

2021-03-30 12:24 UTC, zans-laksa commented on packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.style.scss
> +        padding: 1rem 0 0rem 1.5rem;
Please replace 0rem with 0.

2021-03-30 12:25 UTC, zans-laksa requested changes
Overall good. Please fix some minor issues commented inline.

2021-03-31 18:02 UTC, vladi-j commented
Minor issues were fixed.

2021-04-01 09:34 UTC, zans-laksa approved these changes
Code review passed.

2021-04-01 10:34 UTC, merged