#2426 - page jumps up
scandipwa/scandipwa pull request #2439
Opened 2021-04-02 12:27 UTC by tatiana-scandi

Issue: https://github.com/scandipwa/scandipwa/pull/2426

Related to https://github.com/scandipwa/scandipwa/pull/2183.

**Reason for the problem:**
When we go to Product Page from search results, `ProductPageContainer` receives key equal to product_id (e.g. 1351, for product http://scandipwapmrev.indvp.com//default/n-seventy-transitional-jacket-13.html). When we select another size on Product Page, the key is reset to `null`. When the page is loaded directly, key equals `null` as well. So in order that issue #2426 doesn't appear, it is needed key not to change when changing product options (to have it equal to null, product_id or some other unique identifier of the product).
Using product_id as key when product is loaded directly is tricky, as you still don't know product id, when this line of code is being executed:
https://github.com/scandipwa/scandipwa/blob/master/packages/scandipwa/src/route/UrlRewrites/UrlRewrites.component.js#L68

**Solution:**
The solution I came up with is to replace product id with a pathname, which:
1.  is known for the product, no matter whether you navigate to product page from search results or via direct URL
2.  doesn't change when product options and hence query params in URL are updated
3. is unique between products, as is based on unique SKUs

Yet I need some advice regarding this solution, as probably I haven't taken into account some of the aspects of the solution with product_id.

2021-04-09 09:58 UTC, alfredsgenkins requested changes
Please consider using SKU, which is known in UrlRewrite. Binding to URL is not secure enough.

2021-04-12 08:59 UTC, alfredsgenkins requested changes
What? Oh now, why did you do that? Such method of getting SKU from URL is not reliable and will not work for any rpoduct that has custom URl rewrite!

Why can not you use real product SKU?

2021-04-12 09:53 UTC, tatiana-scandi commented
I missed out the fact that product SKU is known in `UrlRewrites`:disappointed_relieved:  Product Id is also known in this component. So I changed the solution back to using product id as key, but changed it to be received from UrlRewrites as props.

2021-04-14 10:43 UTC, alfredsgenkins approved these changes

2021-04-14 10:43 UTC, merged