Will retain link parameters when popup is opened
scandipwa/scandipwa pull request #2490
Opened 2021-04-13 13:18 UTC by raivisdejus

If user or a google bot lands for the very first time on some page with parameters, like `/women.html?page=2` or `/women.html?customFilters=color:395124;size:395234` the "new version" popup will be triggered and parameters will be lost.

This commit fixes that, parameters will be retained

2021-04-27 08:12 UTC, yeegor requested changes
You forgot `window.location.hash` :)

[Article](https://stackoverflow.com/a/20746566/14562481)

![image](https://user-images.githubusercontent.com/46347627/116208173-4c54a900-a749-11eb-8caf-7a983547ffe9.png)

2021-05-31 10:23 UTC, yeegor commented
Changes are expected here.

2021-07-14 11:36 UTC, carinadues commented
Hey, @raivisdejus could you do this adjustment?

2021-07-14 13:41 UTC, raivisdejus commented
Excellent catch @yeegor! Implemented suggestion to make ScandiPWA even better.

CC @carinadues

2021-07-23 11:03 UTC, ejnshtein approved these changes

2021-08-16 14:19 UTC, merged