Authentication And Quote Id Fixes
scandipwa/scandipwa pull request #2589
Opened 2021-05-06 00:15 UTC by zans-laksa

Fixes #2568
Added some authentication and quote id related fixes.

2021-05-06 07:36 UTC, aleksandrakorolova commented
2.Now : loader -> success message -> blank page -> my account https://drive.google.com/file/d/1D2JTtgHF0jJFNLhq8iFuMlPn2gjcvYnH/view?usp=sharing
Can we do how it works early? loader -> my account and success message

5. Error message 'Current user isn't authorized' is displayed and user stays on the same page in my account if Cookie Lifetime ends and user changes password -  can reproduce

6.Error message 'Authorization unsuccessful' is displayed and user stays on the same page in my account if Cookie Lifetime ends and user shares wishlist -  can reproduce

8. Can reproduce with account ddd@gmail.com / Scandipwa1234

2021-05-10 08:30 UTC, aleksandrakorolova commented
2. Fixed
8. Will create a separate task for this issue
9. Fixed 
10. Sometimes never-ending loader when user create an account (2 cases: create account after checkout and not)
![image](https://user-images.githubusercontent.com/73526235/117622069-eb7e9500-b17a-11eb-9380-b39d915e2170.png)
![image](https://user-images.githubusercontent.com/73526235/117625129-5c737c00-b17e-11eb-8423-cb4fee09a52f.png)
![image](https://user-images.githubusercontent.com/73526235/117622084-ee798580-b17a-11eb-868e-b66e55d8f408.png)

2021-05-11 07:59 UTC, IvansZuks requested changes

2021-05-11 07:59 UTC, IvansZuks commented on packages/scandipwa/src/component/MyAccountSignIn/MyAccountSignIn.container.js
> +            setLoadingState(false);
This can be moved after try catch block

2021-05-11 07:59 UTC, IvansZuks commented on packages/scandipwa/src/route/LoginAccount/LoginAccount.container.js
> +            return;
Missed white line before return

2021-05-11 07:59 UTC, IvansZuks commented on packages/scandipwa/src/route/MyAccount/MyAccount.container.js
> -
We should leave this white line

2021-05-11 10:10 UTC, zans-laksa commented on packages/scandipwa/src/route/MyAccount/MyAccount.container.js
> -
Fixed

2021-05-11 13:12 UTC, IvansZuks approved these changes

2021-05-11 14:56 UTC, merged