#1439 Bugfix/boolean attributes
scandipwa/scandipwa pull request #2632
Opened 2021-05-18 11:01 UTC by tatiana-scandi

2021-06-03 08:29 UTC, IvansZuks requested changes

2021-06-03 08:29 UTC, IvansZuks commented on packages/scandipwa/src/component/ProductAttributeValue/ProductAttributeValue.component.js
> +
What for white line is added here? Please remove

2021-06-08 12:42 UTC, IvansZuks approved these changes

2021-06-08 17:35 UTC, merged

2021-06-08 17:39 UTC, carinadues commented
Fixes #1439