MyAccount address allowed country fix
scandipwa/scandipwa pull request #2711
Opened 2021-06-02 09:47 UTC by AleksandrsKondratjevs

fixes #2566

2021-06-11 15:29 UTC, IvansZuks requested changes

2021-06-11 15:29 UTC, IvansZuks commented on packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.component.js
> +        const isStateRequired = country ? country.is_state_required : false;
Please destruct country

2021-06-15 10:52 UTC, AleksandrsKondratjevs commented
@IvansZuks Hello! 
Found a bug on checkout after this PR so kind fixed it and code changed a bit. Can you please take a look again at it?

2021-06-17 08:17 UTC, IvansZuks approved these changes

2021-07-07 11:36 UTC, merged