#2693 - Added link for product tab review
scandipwa/scandipwa pull request #2782
Opened 2021-06-16 06:54 UTC by teodormoq

2021-07-22 11:29 UTC, Elena-Evsa commented
Oops page appears then click on 'Be the first to review this product'
https://vimeo.com/577996099/f3fbe6801e

2021-07-23 11:16 UTC, ejnshtein commented on packages/scandipwa/src/route/ProductPage/ProductPage.component.js
> +        ProductTabsDefaultValue: PropTypes.number.isRequired
Probably we should use camelCase for this prop, as everywhere else to keep our code consistent.

2021-07-23 11:17 UTC, ejnshtein requested changes
Resolve case issue, please!

2021-07-30 13:06 UTC, teodormoq commented
Hi @ejnshtein i dont have time to fix this sorry

2021-08-09 23:24 UTC, carinadues commented
PR closed for the reasons explained in the issue.

2021-08-09 23:24 UTC, closed without merging