#2616 - no error message inside mobile pop-up
scandipwa/scandipwa pull request #2785
Opened 2021-06-16 14:54 UTC by tatiana-scandi

Issue: https://github.com/scandipwa/scandipwa/issues/2616

Error message is displayed BELOW popup and invisible, as the popup is fullscreen. The solution here is to show the message inside popup as well, so that user sees it. Only applicable to mobile.

2021-06-17 05:25 UTC, aleksandrakorolova commented
Error message isn't displayed on all width screen as other notification messages
**Actual result:**
![Screenshot_20210617-080458_Chrome](https://user-images.githubusercontent.com/73526235/122335723-6a1ddd80-cf44-11eb-9116-57c270a2008b.jpg)

**Expected result**
Notification error is displayed on all width screen
![Screenshot_20210617-080810_Chrome](https://user-images.githubusercontent.com/73526235/122335733-6c803780-cf44-11eb-831a-59f17937540f.jpg)


Please, change error message if user submitted the form with wrong current password or will I create new task for this?
**Actual result:**
Error message 'Invalid login and password' appears
**Expected result:**
Error message 'The password doesn't match this account. Verify the password and try again.' appears

2021-06-17 13:10 UTC, tatiana-scandi commented
Issue with wrong message: https://github.com/scandipwa/scandipwa/issues/2793

2021-06-17 13:15 UTC, tatiana-scandi commented
Fixed message not full width:
<img width="291" alt="ScandiPWA 2021-06-17 14-14-08" src="https://user-images.githubusercontent.com/79456428/122403697-3e701700-cf87-11eb-87d4-1b3ea83e0dff.png">

2021-06-18 08:10 UTC, zans-laksa commented on packages/scandipwa/src/component/Popup/Popup.style.scss
> +        }
Since the notification should be rendered only on mobile devices, please check the `isMobile` prop and render it only if it's true.

2021-06-18 08:10 UTC, zans-laksa commented on packages/scandipwa/src/component/Popup/Popup.component.js
> +                    <NotificationList />
Since the notification should be rendered only on mobile devices, please check the `isMobile` prop and render it only if it's true.

2021-06-18 08:21 UTC, zans-laksa requested changes
Code review didn't pass.

2021-06-21 10:35 UTC, zans-laksa approved these changes
Code review passed.

2021-07-13 20:58 UTC, merged