2674/plp issue
scandipwa/scandipwa pull request #2817
Opened 2021-06-29 16:20 UTC by tatiana-scandi

Issue: https://github.com/scandipwa/scandipwa/issues/2674

2021-06-29 20:28 UTC, zans-laksa commented on packages/scandipwa/src/component/ProductActions/ProductActions.container.js
> +    SIMPLE, VIRTUAL
Please place `VIRUAL` constant on a new line.

2021-06-29 20:29 UTC, zans-laksa requested changes
Code review not passed.

2021-06-30 05:57 UTC, aleksandrakorolova commented
Still can reproduce 
![Screenshot 2021-06-30 at 08 48 49](https://user-images.githubusercontent.com/73526235/123908409-1ec1f100-d980-11eb-84e5-1a1c7cfb67bd.png)

2021-06-30 09:57 UTC, zans-laksa approved these changes
Code review passed.

2021-06-30 16:15 UTC, merged