bugfix 2810 – duplicate title downloadable pdp
scandipwa/scandipwa pull request #2820
Opened 2021-06-30 09:58 UTC by winniepukki

Fixes scandipwa/scandipwa#2810

2021-07-01 11:47 UTC, aleksandrakorolova commented
Now placeholder is displayed
![Screenshot 2021-07-01 at 14 44 24](https://user-images.githubusercontent.com/73526235/124119235-ed7a1b80-da7a-11eb-9b68-4d5abefb478c.png)

2021-07-02 11:48 UTC, winniepukki commented
@aleksandrakorolova the behaviour is too random. Unable to reproduce

2021-07-02 11:49 UTC, winniepukki commented
Please leave a product link you are testing and in how many cases of 10 you succeed reproducing?

2021-07-14 12:39 UTC, ejnshtein commented on packages/scandipwa/src/component/ProductAttributeValue/ProductAttributeValue.component.js
> +        return this.renderStringValue(+attribute_value ? __('Yes') : __('No'));
If you want to convert a value from string to number, better to use `parseInt` of `parseFloat` functions, using `+` in from of a variable is an implicit way of doing this.

2021-07-14 12:45 UTC, ejnshtein requested changes
Overall looks OK, just need an answer to one comment

2021-07-14 14:51 UTC, carinadues commented
Closed because the issue isn't reproducible anymore.

2021-07-29 12:53 UTC, carinadues commented
The issue was fixed in #2977

2021-07-29 12:53 UTC, closed without merging