#3149 - handle no search results UX
scandipwa/scandipwa pull request #3174
Opened 2021-08-23 12:32 UTC by tatiana-scandi

Issue: https://github.com/scandipwa/scandipwa/issues/3149

2021-08-23 23:02 UTC, zans-laksa requested changes

2021-08-23 23:02 UTC, zans-laksa commented on packages/scandipwa/src/route/CategoryPage/CategoryPage.style.scss
> +        &.CategoryPage-Miscellaneous_noResults {
I guess this selector can be more compact like `&_noResults` ?

2021-08-24 05:58 UTC, aleksandrakorolova commented
1. Mobile: Remove the unnecessary indent 
<img src="https://user-images.githubusercontent.com/73526235/130562932-eb6c93bc-08c9-4cb1-ba03-ae221e9812aa.jpg" width="400" height="700">
2. We show '0 items found' in the mobile layout but it's missing in the desktop layout. We need to show it on mobile and desktop or don't show it at all
<img src="https://user-images.githubusercontent.com/73526235/130563156-c4a55851-d7b0-48c0-9ffe-7a3b89631c8b.png">

2021-08-24 09:02 UTC, tatiana-scandi commented
Fixed 1 and 2.

2021-08-24 18:06 UTC, zans-laksa approved these changes

2021-08-24 18:18 UTC, merged