Image popup fixes
scandipwa/scandipwa pull request #3238
Opened 2021-08-30 13:39 UTC by tatiana-scandi

Fixes issues: 
https://github.com/scandipwa/scandipwa/issues/3196
https://github.com/scandipwa/scandipwa/issues/3197
https://github.com/scandipwa/scandipwa/issues/3198
https://github.com/scandipwa/scandipwa/issues/3211

1. I made mousemove not trigger any visual effect if image is already fits by height and doesn't need to be scrolled.
2. Made image that has height less than window height visually centered. 
3. Made initial image position be calculated and recalculated on slide change, not only on mousemove
4. Made image position be recalculated on window size change.
5. Fixed error of image position be incorrect if image is after video (it turned out that locator for getting images list was incomlete)
6. Fixed issue of video not played im zoom. Previously popup closure occurred in this case, and it broke gallery display at all. What you need is just switch from zoomed mode to not zoomed.
7. Made top and bottom of zoomed image visible.

Also made zoomed popup fullscreen again + improved UX a bit.

2021-08-31 06:01 UTC, aleksandrakorolova commented
1.Images disappear when clicking back 

**Steps:**
1. Open PDP
2. Open image on full-screen
3. Click on Back

**Actual result:**
Images disappear
https://drive.google.com/file/d/1oDa95zAscFdzHV1tntdUyc1BMFe7AtqM/view?usp=sharing

**Expected result**
User redirects to previous page

**Notes:**
User stays on PDP if he/she opens image -> closes it -> clicks back
_________________________________________
2.Slider with arrows is displayed if product has 6+ images. Appear unnecessary indent between the last image and arrow when clicking on arrow
**Steps:**
1. Open product with many images - https://pr-3238.d25kd40decjpue.amplifyapp.com/default/accessories/accessories-bags/travel-bags/travel-bag-1.html
2. Open image on full-screen

**Actual result:**
Slider with arrows is displayed. Appear unnecessary indent between the last image and arrow when clicking on arrow
https://drive.google.com/file/d/1GecC_2-9oRXT72j0IeyqH8P9kz784TPh/view?usp=sharing

**Expected result:**
Slider with arrows is displayed only if product has more than 17 images

2021-08-31 13:32 UTC, tatiana-scandi commented
Issue 1 - fixed
Issue 2 - I rewrote carousel gallery additional logic so that it dynamically updates gallery additional icons on zoom and resize.

2021-09-01 05:47 UTC, aleksandrakorolova commented
1.Images switch quickly when closing images pop-up on full-screen

**Steps:**
1. Open PDP
2. Open image on full-screen
3. Click on Back

**Actual result:**
Images switch quickly (Base image appears and switch to opened image)
https://drive.google.com/file/d/13M_s0Qaydlg9lHNze94Jmg-33eWOZi09/view?usp=sharing

**Expected result**
Opened image is displayed. Images don't switch
______________________________
2.User doesn't redirect to previous page when clicking back button if he/she opened image pop-up and closet it

**Steps:**
1.  Open PDP
2. Open image on full-screen
3. Close it (Click on Cross)
4. Click on back button

**Actual result:**
Nothing happens

**Expected result:**
User redirects to previous page

2021-09-02 08:39 UTC, tatiana-scandi commented
3 - fixed
4 - fixed in a separate PR https://github.com/scandipwa/scandipwa/issues/3248

2021-09-06 11:30 UTC, aleksandrakorolova commented
3. Still, sometimes can reproduce 
https://drive.google.com/file/d/1FUd1cbkZKk9jpf8sn9F3QjgcmRK2Lyks/view?usp=sharing

4. ok

5. Horizontal images are displayed at the top when slider is scrolling to selected image

**Steps:**

1. Open PDP - https://pr-3238.d25kd40decjpue.amplifyapp.com/default/accessories/accessories-bags/travel-bags/travel-bag-1.html
2. Open image on full-screen
3. Click on the last image
4. Click on the penultimate image
5. Click on the last image

**Actual result:**
Horizontal images are displayed at the top
https://drive.google.com/file/d/1wAYW3sPYyJWNdeMvuSboot2bll2IYeh1/view?usp=sharing

**Expected result:**
Slide on full-screen works the same as on PDP

2021-09-13 12:48 UTC, tatiana-scandi commented
Issue 3: I increased delay for image appearance even more (so that all required calculations are made and translateX is applied: you need to wait for page to load first, then get size of the slider container, image width, image number, calculate translateX for setting image correct position, apply translateX - these actions are not immediate and take time). If after that blinking appears in very rare cases, I suggest to leave it as is, as even greater delay will make user look at nothing (white area) for too long => effect will be worse than from very rare not smooth animation.

Issue 5: Fixed

2021-09-13 14:28 UTC, Elena-Evsa commented
Issue 3: ok
Issue 5: Fixed

**Issue 6:** 
Video is not launched if user click on 'Play' in zoomed mode
**Step to reproduce:** 
1. Open https://pr-3238.d25kd40decjpue.amplifyapp.com/default/travel-bag-1.html 
2. Click on any image to zoom it
3. Click on video in carousel 
4. Click Play
**Video:**
https://vimeo.com/603983790/c3137e826e
**Expected result**
Video is launched if user click on 'Play' in zoomed mode

2021-09-13 16:06 UTC, tatiana-scandi commented
Issue 6: should work now.

2021-09-14 07:43 UTC, Elena-Evsa commented
Issue 6: fixed

**Issue 7:** 
Now small part of second picture shown on slide with 1st picture if user zoom in/out page
Screenshot:
![image](https://user-images.githubusercontent.com/84388061/133212469-91cda0b9-ea3b-4328-8b6f-c4690dcf3638.png)
Steps to reproduce:
1. Open https://pr-3238.d25kd40decjpue.amplifyapp.com/default/travel-bag-1.html 
2. Click on wide image with not white background (as on screenshot)
3. Zoom in/out _page_ (in my case it is shown on 33%, 90%, 125%, 175%)

**Issue 8:**
Horizontal scroll appear is carousel which contains 21 pictures after some steps
Steps to reproduce:
1. Open https://pr-3238.d25kd40decjpue.amplifyapp.com/default/travel-bag-1.html 
2. Click on last image
3. Zoom in last image
Screenshot:
![image](https://user-images.githubusercontent.com/84388061/133215293-8c064fc2-941a-4ff8-8f92-d1736e43f4ab.png)

**Issue 9:**
Part of images situated after the borders of screen in carousel after some steps:
1. Open https://pr-3238.d25kd40decjpue.amplifyapp.com/default/travel-bag-1.html 
2. Click on last image
3. Zoom in last image
4. Go to the first image in carousel
5. Observe last image in carousel
Video: 
https://vimeo.com/604600531/db143245c9

**Issue 10:**
Left boarder of image in carousel is cut after steps:
1. Open https://pr-3238.d25kd40decjpue.amplifyapp.com/default/travel-bag-1.html 
2. Click on last image
3. Zoom in last image
4. To better observe, click on image with white background
Screenshot:
![image](https://user-images.githubusercontent.com/84388061/133216076-4a4fa77c-3164-4d15-9b09-9af99b253bb9.png)

2021-09-14 10:17 UTC, Elena-Evsa commented
Created separate bug report for issues 7-10 - #3328

2021-09-14 17:40 UTC, zans-laksa requested changes
Did you also tested this on RTL layout?

2021-09-14 17:40 UTC, zans-laksa commented on packages/scandipwa/src/component/ProductGallery/ProductGallery.style.scss
> +            left: 20px;
Please use the logical css properties.

2021-09-14 19:28 UTC, tatiana-scandi commented
> Did you also tested this on RTL layout?

Yes (no new RTL related logic was added in this PR, the old one was not broken)

2021-09-14 19:28 UTC, zans-laksa approved these changes

2021-09-19 23:48 UTC, merged