#1998 - Added Compare count in header
scandipwa/scandipwa pull request #3340
Opened 2021-09-15 14:53 UTC by teodormoq

2021-09-15 15:25 UTC, carinadues commented
Hey! Thanks for the PR
Can you position the number on the same level as the number for the cart?
![image](https://user-images.githubusercontent.com/82165392/133462516-06a2b2c3-554a-40d5-ad77-c40b12eb04cf.png)

2021-09-15 17:12 UTC, teodormoq commented
Hi @carinadues can you please share your browser and device, because i dont see the same as you
<img width="204" alt="Screenshot 2021-09-15 at 19 11 47" src="https://user-images.githubusercontent.com/8639654/133478821-ae8e70a0-309c-474d-9956-cc8036847312.png">

2021-09-15 17:21 UTC, carinadues commented
Hey @teodormoq sure
It is Chrome and Windows 10

2021-09-16 09:20 UTC, Elena-Evsa commented
Issue 1: Can reproduce the same as Carina on Win10 Opera and FireFox
Issue 2: differebt size of fonts of numbers near the compare icon and cart icon on Mac Safari (checked on browsersatck)
![image](https://user-images.githubusercontent.com/84388061/133584165-26f7799a-3d98-4455-a666-4cbf5681a82e.png)
Issue 3: should we show Qty of prodcuts in compare list on mobile? @carinadues

2021-12-03 09:47 UTC, arturs-pesockis requested changes

2021-12-03 09:47 UTC, arturs-pesockis commented on packages/scandipwa/src/component/Menu/Menu.container.js
> +
remove empty line

2021-12-03 09:47 UTC, arturs-pesockis commented on packages/scandipwa/src/component/Menu/Menu.component.js
> +                    { `(${this.renderCompareCountInMenu()})` }
I think you should move braces inside the renderCompareCountInMenu, and here it will be simply `{ this.renderCompareCountInMenu() }`

2021-12-03 09:47 UTC, arturs-pesockis commented on packages/scandipwa/src/component/Menu/Menu.component.js
> +    renderCompareCountInMenu() {
don't see reason why that InMenu postfix is needed

2021-12-03 14:59 UTC, aleksandrakorolova commented
1.Count for compare list is slightly shifted compering count for cart 
**Mac:**
![Screenshot 2021-12-03 at 15 30 58](https://user-images.githubusercontent.com/73526235/144610904-fea39148-e6ba-4964-a256-9776a6856c55.png)

**Windows:**
![count](https://user-images.githubusercontent.com/73526235/144614403-34ab2bfc-d8b6-438b-9df9-a1d4aac1cfdf.PNG)

_____________________________

2.Different size of fonts of numbers near the compare icon and cart icon 
**Chrome:** 
Size for cart count is 10.6667px
![Screenshot 2021-12-03 at 15 38 42](https://user-images.githubusercontent.com/73526235/144612976-ce7f3c71-0f47-4e9c-a7b5-fae0e3d108ac.png)

Size for compare count is 10.5px
![Screenshot 2021-12-03 at 15 38 53](https://user-images.githubusercontent.com/73526235/144612990-45a7b666-2263-49a7-9944-00d7f0e36d00.png)

**Safari:** 
Size for cart count is 8.8px
![Screenshot 2021-12-03 at 15 45 20](https://user-images.githubusercontent.com/73526235/144613138-f55fb212-8a62-466a-834a-5eb5cab1c64b.png)

Size for compare count is 10.5px
![Screenshot 2021-12-03 at 15 45 07](https://user-images.githubusercontent.com/73526235/144613058-3d1f543a-6864-4ead-a35f-ad95fd2e65f8.png)
_____________________________

3.Compare count is missing after refreshing page
https://drive.google.com/file/d/1K_Nf3lqmI--yx5CttaAz2DHJZ7WAjAcn/view?usp=sharing
_____________________________
4.Different behavior for compare and cart count when logging in 

**Actual result:**
Cart count disappears when logging in and then appears
Compare count is displayed when logging in and then count of products changes
https://drive.google.com/file/d/1QSChV-5reHn2fzuZpxcMdbkNViAK4cCd/view?usp=sharing

**Expected result:**
The same behavior for compare and cart count as cart count works 
______________________________
5.Mobile: Different font size 

**Actual result:**
Font style is 'Mulish'
![Screenshot 2021-12-03 at 16 54 37](https://user-images.githubusercontent.com/73526235/144623124-e1795ecd-311b-4b03-9227-1eab4b9e9926.png)

**Expected result:**
Font style is 'Muli' as other content
![Screenshot 2021-12-03 at 16 56 27 (2)](https://user-images.githubusercontent.com/73526235/144623464-63a51109-04a6-4c2c-80f2-73ddf3f8abf5.png)
________________________________
6.Mobile: Compare count is shifted left
**Actual result:**
![Screenshot 2021-12-03 at 16 48 57](https://user-images.githubusercontent.com/73526235/144622379-90f3967a-edad-466d-8d19-ca595f74cc64.png)

**Expected result:**
![Screenshot 2021-12-03 at 16 50 25](https://user-images.githubusercontent.com/73526235/144622498-6bd37c98-c02e-46f6-91dc-fe80d4a447ea.png)

2021-12-07 09:13 UTC, aleksandrakorolova commented
1. Count of compare list and cart should aligned and display in the upper right corner of the icon
**Actual result:** 
![Screenshot 2021-12-07 at 10 34 24](https://user-images.githubusercontent.com/73526235/144995581-6393ad29-687f-4550-9a09-8d8e78e497cc.png)
**Expected result:**
https://www.figma.com/file/qhlU4sg973vSMLexf3oiRM/SW%2FINT_PWA?node-id=4904%3A12887
![Screenshot 2021-12-07 at 10 43 55](https://user-images.githubusercontent.com/73526235/144995938-4c8caaf3-aec5-4570-bc9b-4580d8b6c297.png)
2. Chrome - Compare and cart count is 11px - Ok
Safari - Compare count is 11.20px and cart count is 8.8px - Please, do the same size (11px)
3. Still, can reproduce
4. Still, can reproduce
5. Fixed
6. Still, can reproduce on iOS
![Screenshot 2021-12-07 at 11 10 29](https://user-images.githubusercontent.com/73526235/145000125-b1cd0eb5-a261-4bb5-978b-552458076fce.png)
7. Android: Text 'Compare products' is written in two lines in menu
![Screenshot 2021-12-07 at 10 53 11](https://user-images.githubusercontent.com/73526235/144997333-babe8eec-cc7e-454c-9969-7635366fce12.png)

2021-12-09 08:50 UTC, aleksandrakorolova commented
1. Still, count for compare list is shifted up on Mac
![Screenshot 2021-12-09 at 09 46 08](https://user-images.githubusercontent.com/73526235/145355331-fef55816-79b1-4ad6-95c5-a25d2acb2dd0.png)

2. Chrome - Compare count is 11.20px and cart count is 10.6667px 
Safari - Compare count is 11.20px and cart count is 8.8px 
**Expected result:**
Size is 11px

3. Now compare count is displayed after refresh page BUT Different behavior for compare and cart count when refreshing page. (See video in next point) Please, do the same behavior  

4. Still, Different behavior for compare and cart count when logging in https://drive.google.com/file/d/1utmQA6irpRearqKSAk9-LewrO6rLbDVh/view?usp=sharing

6.Fixed

7.Fixed

8. Mobile: Compare count is slightly shifted up
![Screenshot 2021-12-09 at 10 49 06](https://user-images.githubusercontent.com/73526235/145363883-8d848bbb-0243-4ffe-8018-f5db78dbe121.png)

2021-12-16 06:08 UTC, aleksandrakorolova commented
1. Still can reproduce
Mac:
![Screenshot 2021-12-16 at 07 39 16](https://user-images.githubusercontent.com/73526235/146314807-6f0349e3-af57-4d0f-8412-7efeac0956e1.png)

Windows:
![compare](https://user-images.githubusercontent.com/73526235/146314795-25eb32cd-0587-43c0-802b-31ca26ba0753.PNG)

2. Fixed
3. Fixed
4. Still can reproduce:
- Cart count disappears but compare count stays when loading
- Cart count appears but compare count is not updated when logging in
- Compere count is updated for a few seconds after login
https://drive.google.com/file/d/16stEjP0D93_hN5YPSjgYLRK0Eyq5K1Vw/view?usp=sharing
8. Fixed

2021-12-21 10:07 UTC, Elena-Evsa commented
1. Still can reproduce
2. Fixed
3. Fixed
4. Still can reproduce: 
Compere count is updated for a few seconds after login, first step old value of compare count shown and after few seconds new value
 https://vimeo.com/658899807/fdc9dc247d
5. Fixed

2022-01-09 17:29 UTC, gShubo commented
Problem: 

-    Compare Count has different positions on Mac/Windows/Linux 
-    Compere count is updated for a few seconds after login, first step old value of compare count shown and after few seconds new value

In this Commit: 

-   Changed Compare Count <a> element style 

-  Fixed Compare count render after login. New value renders after sign in.

2022-01-10 13:27 UTC, ejnshtein approved these changes

2022-01-10 13:28 UTC, merged