[3680] Fix Text Shifted Up On Mobile
scandipwa/scandipwa pull request #3809
Opened 2021-11-23 12:21 UTC by mahmoud-Elshahawy

Related issue(s):
* Fixes https://github.com/scandipwa/scandipwa/issues/3680

Problem:
* Mobile: Text is shifted up in checkboxes on PDP.

In this PR:
* I have added margin: auto; to ProductDownloadableLink-SampleTitle class in ProductDownloadableLinks.style.scss file.

2021-11-24 06:58 UTC, aleksandrakorolova commented
**On Android:** Text is slightly shifted up in checkboxes 
![Screenshot 2021-11-24 at 08 53 25](https://user-images.githubusercontent.com/73526235/143189481-d0e6299a-3707-4256-9560-21ce46d81be2.png)

**On iOS:** Text is slightly shifted down in checkboxes 
<img src="https://user-images.githubusercontent.com/73526235/143189761-0b8d2140-29d9-4de9-a3f1-c4325f3ead45.PNG" width="360" height="650">

**Expected result:**
Text is central aligned

2021-11-25 08:09 UTC, aleksandrakorolova commented
Still, can reproduce
![Screenshot 2021-11-25 at 09 58 04](https://user-images.githubusercontent.com/73526235/143403414-2d37399b-9264-4eef-9477-7c1a88d804e5.png)
![Screenshot 2021-11-25 at 10 03 58](https://user-images.githubusercontent.com/73526235/143403429-72561a99-4f84-4db9-b31a-d1570ee8914d.png)

2021-12-02 08:53 UTC, arturs-pesockis requested changes

2021-12-02 08:53 UTC, arturs-pesockis commented on packages/scandipwa/src/component/ProductDownloadableSamples/ProductDownloadableSamples.style.scss
> -
Blank line shouldn't be removed. Usually there should be separation between properties and `@includes`

2021-12-02 08:53 UTC, arturs-pesockis commented on packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.style.scss
> +        // removed top
comment is not needed here

2021-12-02 10:01 UTC, arturs-pesockis requested changes

2021-12-02 10:01 UTC, arturs-pesockis commented on packages/scandipwa/src/component/ProductDownloadableSamples/ProductDownloadableSamples.style.scss
> +
remove trailing spaces

2021-12-02 10:33 UTC, aleksandrakorolova commented
Still, Text is slightly shifted like as arrow in #3734. => So there is no proper way to avoid this issue on devices if Muli is used.

2021-12-03 11:22 UTC, AleksandrsKondratjevs requested changes

2021-12-03 11:22 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.style.scss
> +        margin:auto;
please space between property and value

2021-12-04 16:52 UTC, AleksandrsKondratjevs approved these changes

2021-12-06 11:23 UTC, merged