3771
scandipwa/scandipwa pull request #3823
Opened 2021-11-26 09:56 UTC by hoahoang311

Make button height flexible to fit content & set fixed high for date/time field to 44.6px on PDP
Related issue(s):

- Fixes #3771
- Fixes #3800

Problem:

- Long category names do not stay within the button box on the Homepage
- Wrong date/time field's height on PDP

In this PR:

- Added flex-wrap styling so the text will stay within the button and set button height fit content
- Fixed date/time field height to 44.6px on PDP

2021-11-27 05:35 UTC, AleksandrsKondratjevs requested changes

2021-11-27 05:35 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/style/cms/block/homepage-category-preview.scss
> +        .Button {
Please use BEM to style elements in task. Block is HomepageCategories and elem is Button. 
So you can make &-Button and it should get your styles.

2021-11-29 05:58 UTC, aleksandrakorolova commented
1. Buttons change size when hovering mouse on it 
https://drive.google.com/file/d/1VxdrHYOXU_XFWpa9husU1ZvgDj0zggDi/view?usp=sharing
2. Fixed

2021-12-07 14:22 UTC, carinadues commented
This will be fixed in https://github.com/scandipwa/scandipwa/pull/3877

2021-12-07 14:22 UTC, closed without merging