3771/ Fixed long category names go over the button on Homepage
scandipwa/scandipwa pull request #3829
Opened 2021-11-29 17:24 UTC by hoahoang311

Make button height fit content and text wrapped inside the button

Related issue(s):

- Fixes https://github.com/scandipwa/scandipwa/issues/3771

Problem:

- Text overflow the category button on the Home page

In this PR:

- Make button height fit content and text wrapped inside the button

2021-11-30 08:28 UTC, aleksandrakorolova commented
1. Button/text is displayed behind the button if screen width ±940px 
Safari:
![Screenshot 2021-11-30 at 08 03 05](https://user-images.githubusercontent.com/73526235/143995199-854ef8e1-26c2-4553-aee2-1b6d965587d5.png)
Chrome (Win):
![Capture](https://user-images.githubusercontent.com/73526235/143996075-c56b7c96-faa3-47fc-a569-0c789807084d.PNG)
_______________________
2. Looks like indent/padding is missing between button border and text on Windows and Android if compare with iOS and Mac
Windows:
Mac:
![Screenshot 2021-11-30 at 08 14 40](https://user-images.githubusercontent.com/73526235/143995845-5fd337c1-71fb-4010-8bd2-43d67971b358.png)
Windows:
![Screenshot 2021-11-30 081601](https://user-images.githubusercontent.com/73526235/143996320-c1886ff0-3868-4d4d-ac65-44545bddbf23.png)

2021-12-02 11:13 UTC, aleksandrakorolova commented
1. Fixed
2. Fixed
3. iOS: Text is cropped if the word does not fit on one line 
![Screenshot 2021-12-02 at 12 56 58](https://user-images.githubusercontent.com/73526235/144409358-03af4e9e-bb9a-4feb-94a0-6392a6c6ccf1.png)

4. Android: Text is displayed behind the button if the word does not fit on one line
![Screenshot 2021-12-02 at 12 55 40](https://user-images.githubusercontent.com/73526235/144409097-35d5beea-fc69-4e57-a10d-26c35d94564a.png)

2021-12-06 12:46 UTC, aleksandrakorolova commented
3. Fixed
4. Fixed
5. Button is displayed behind the button in big screen resolution 
![Screenshot 2021-12-06 at 14 20 26](https://user-images.githubusercontent.com/73526235/144848389-357ab8b4-4303-4f7a-8b9c-cdeed157227e.png)

Display Resolution - 2560x1440 pixels
Screen Size - 25 inches

2021-12-08 06:45 UTC, aleksandrakorolova commented
5. Fixed

2021-12-09 15:39 UTC, AleksandrsKondratjevs requested changes

2021-12-09 15:39 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductAttributeValue/ProductAttributeValue.component.js
> +                { subLabel ? `(${subLabel})` : undefined }
isn't it fixed in this PR?
https://github.com/scandipwa/scandipwa/pull/3838/files

2021-12-09 15:39 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductAttributeValue/ProductAttributeValue.component.js
> +            return this.renderDropdown(value, isProductCountVisible ? count : null);
Please check in renderDropdown function

2021-12-09 15:39 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/style/cms/block/homepage-category-preview.scss
> +        }
To everything? Maybe we can restring it a bit for specific elements?

2021-12-10 12:15 UTC, AleksandrsKondratjevs approved these changes

2021-12-14 00:20 UTC, carinadues commented
Hey, @hoahoang311 can you please fix this merge conflict? Then we'll merge the PR :)

2021-12-14 04:34 UTC, hoahoang311 commented
Conflict resolved!

2021-12-14 17:28 UTC, merged