[3733] Font settings
scandipwa/scandipwa pull request #3849
Opened 2021-12-03 09:44 UTC by Dagnija-Viktorova

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3733

**Problem:**
* Wrong font color for the old price
* Incorrect line-height for product card
* Selected filters don't show up as bold
* On mobile price doesn't use mobile h2 style

**In this PR:**
* Changed font color and opacity of ProductPrice-HighPrice
* Adjusted line-height of ProductCard, ProductPrice, and AddToCart
* Added font-weight to ResetAttributes-AttributeText
* Added the same style on mobile as h2 (mobile) for ProductPrice-PriceValue

2021-12-06 06:52 UTC, aleksandrakorolova commented
1.Color for old price - **Fixed**
2.1Line-height for product name 20.02px
![Screenshot 2021-12-06 at 08 23 31](https://user-images.githubusercontent.com/73526235/144797739-a8f94f0e-3f35-4df6-8804-d47fe7f24c7e.png)

**Expected result:**
Line-height is 20px

2.2 Line-height for price excl.tax 16.08px
![Screenshot 2021-12-06 at 08 24 54](https://user-images.githubusercontent.com/73526235/144797863-2e429c8e-e419-45ba-829f-d9d25a54365c.png)
**Expected result:**
Line-height is 16px

2.3  Line-height for price 20.04px
![Screenshot 2021-12-06 at 08 35 47](https://user-images.githubusercontent.com/73526235/144799028-f4e8c8fe-6e20-4320-9a7c-c249bb3e418e.png)

**Expected result:**
Line-height is 20px

2.4 Old price - **Fixed**

2.5 Line-height for price 28.08px
![Screenshot 2021-12-06 at 08 50 48](https://user-images.githubusercontent.com/73526235/144800795-4049e8cd-b2b0-4bc3-8078-3a8e2978e1ae.png)

**Expected result:**
Line-height is 28px

2.6 Add to cart - **Fixed**

2.7 Line-height for price 12px
![Screenshot 2021-12-06 at 08 32 34](https://user-images.githubusercontent.com/73526235/144798874-ad85e640-3b7c-4ec6-8fd7-abf4758fb8f9.png)

**Expected result:**
Line-height is 16px

3.Attribute name and options are bold
![Screenshot 2021-12-06 at 08 42 04](https://user-images.githubusercontent.com/73526235/144799740-310b204d-966a-4628-9268-1280573693cb.png)

**Expected result:**
Attribute name is bold but attribute option isn't bold as in design 
![Screenshot 2021-12-06 at 08 40 20](https://user-images.githubusercontent.com/73526235/144799659-1591b806-0b80-4204-ae25-7305d078255a.png)
https://www.figma.com/file/qhlU4sg973vSMLexf3oiRM/SW%2FINT_PWA?node-id=3939%3A16438

4. Mobile: Price doesn't use style for mobile H2 - **Fixed**

5.Please, return mobile styles as it were before your changes except 4. issue
![Screenshot 2021-12-06 at 08 43 25](https://user-images.githubusercontent.com/73526235/144800246-c631fb8b-dacc-4733-8922-81b70a8d5e8a.png)

2021-12-07 07:52 UTC, aleksandrakorolova commented
1.Can reproduce in mobile view
![Screenshot 2021-12-07 at 09 28 32](https://user-images.githubusercontent.com/73526235/144985313-903c54eb-7afa-45bf-8b53-6ccd584bfb92.png)
2.1 Fixed
2.2 Fixed
2.3 Fixed
2.5 Fixed
2.7 Fixed
3.Can reproduce in mobile layout 
![Screenshot 2021-12-07 at 09 42 40](https://user-images.githubusercontent.com/73526235/144987275-c2a6ea49-e57d-477d-86f8-9c17698e1039.png)
4.Can reproduce
5.Fixed

2021-12-07 08:15 UTC, Dagnija-Viktorova commented
Fixed the issues by adding changes for mobile view, could this please get reviewed again?

2021-12-07 14:46 UTC, AleksandrsKondratjevs requested changes

2021-12-07 14:46 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductPrice/ProductPrice.style.scss
> +
No need white-space here

2021-12-07 15:03 UTC, Dagnija-Viktorova commented
Removed white-space, can this get approved?

2021-12-07 15:50 UTC, AleksandrsKondratjevs requested changes

2021-12-07 15:50 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductPrice/ProductPrice.style.scss
> +            text-transform: var(--h2-text-transform-mobile);
Wait, why it should be same as h2?

2021-12-07 15:50 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductPrice/ProductPrice.style.scss
> +            text-transform: var(--h2-text-transform-mobile);
Wont it be like if client will set h2 to be 20px on mobile, so that price value will be also 20px ?

2021-12-08 07:44 UTC, aleksandrakorolova commented
1.Fixed
3.Fixed
4.Aleksandrs explained why we don't need to do this. So, please, remove this inherit and change line-height to 24px as per design

2021-12-08 09:17 UTC, Dagnija-Viktorova commented
I removed the inherit and added line-height for mobile as per design, can you approve?

2021-12-09 15:35 UTC, AleksandrsKondratjevs approved these changes

2021-12-10 08:02 UTC, Dagnija-Viktorova commented
Fixed merge conflict, can the pull request get merged?

2021-12-10 11:49 UTC, merged