[3743] Font style on mobile PDP
scandipwa/scandipwa pull request #3880
Opened 2021-12-07 12:30 UTC by Dagnija-Viktorova

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3743

**Problem:**
* Wrong line-height in multiple places
* {rate} / {numberOfReviews} reviews doesn't use mobile h2 styling
* Incorrect font setting for stock status and SKU

**In this PR:**
* Adjusted line-height for buttons, product title, attributes, details, description, reviews
* Made {rate} / {numberOfReviews} use mobile h2 font-size and line-height
* Added font-style: normal and font-size: 12px to stock status
* Added font-style: normal, font-weight: normal and font-size: 12px to SKU

2021-12-07 14:48 UTC, AleksandrsKondratjevs requested changes

2021-12-07 14:48 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductActions/ProductActions.style.scss
> +
excess white-space

2021-12-07 14:48 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductReviewItem/ProductReviewItem.style.scss
> +
same here

2021-12-07 14:48 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductReviews/ProductReviews.style.scss
> +
also here

2021-12-07 15:21 UTC, Dagnija-Viktorova commented
Removed the white-spaces, could this get approved?

2021-12-08 08:19 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductReviews/ProductReviews.style.scss
> +            line-height: var(--h2-line-height-mobile);
Again noticed h2 here. Please don't inherit from h2.

2021-12-08 09:41 UTC, Dagnija-Viktorova commented
I removed the inherit and added line-height and font-size as per requirements, could you approve this pull request?

2021-12-08 10:10 UTC, AleksandrsKondratjevs approved these changes

2021-12-10 08:18 UTC, Elena-Evsa commented
Issue 1: passed
Issue 2: passed
Issue 3: passed
Issue 4: passed
Issue 5: stars is not centrally alligned to the rating 
![image](https://user-images.githubusercontent.com/84388061/145537631-a2e19149-9f27-45df-b44c-72a76e736ff0.png)
Issue 6: line-height for summary of review is 16, but according to design it is 20px, change it please
![image](https://user-images.githubusercontent.com/84388061/145538202-749d520c-23b6-4f84-a939-51bd94728b52.png)
Issue 7: passed
Issue 8: passed

2021-12-10 09:05 UTC, closed without merging