#3794 - Change color and font setting on cart page
scandipwa/scandipwa pull request #3910
Opened 2021-12-10 08:01 UTC by IrinaZhadzinets

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3794

**Problem:**
* Wrong color and font settings on cart page

**In this PR:**
* Colors and size of fonts changed according to the issue

2021-12-10 12:13 UTC, AleksandrsKondratjevs requested changes

2021-12-10 12:13 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductPrice/ProductPrice.component.js
> +            <h3 block="ProductPrice" aria-label="Product Price" mix={ mix }>
So while products will be loading, we will have +20 h3 tags? I don't think it semantically it is correct to set h3 for price or its placeholder.

2021-12-10 12:13 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductPrice/ProductPrice.style.scss
> +    margin-top: 0;
Please use logical properties for margins.

2021-12-10 12:13 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/CartPage/CartPage.style.scss
> +            border: 1px solid var(--cart-page-table-head-background);
Since ``` --cart-page-divider-background ``` is used only here, better to set correct value for variable and not replace it.

2021-12-15 10:10 UTC, Elena-Evsa commented
Issue 1: Color of background table header is not inherited from (--secondary-base-color);
![image](https://user-images.githubusercontent.com/84388061/146167104-85f2ee68-4ed3-4e66-8b1d-2fd885aa07a9.png)

Issue 2: Passed
Issue 3: Passed 
Issue 4: Passed 
Issue 5: Passed

2021-12-16 07:31 UTC, IrinaZhadzinets commented
Good afternoon

Regarding issue 1:
The fact is that the --cart-page-divider-background variable is used only for this border, so the value is not specified directly, but the value of the variable itself has been changed.
![Снимок экрана от 2021-12-16 10-24-57](https://user-images.githubusercontent.com/82805412/146327176-dd797763-333e-4544-960b-1c36bec12231.png)
Do I need to change the value of this border directly, or leave it as set now?

2021-12-17 11:45 UTC, Elena-Evsa commented
Ok, lets left

2021-12-28 12:06 UTC, AleksandrsKondratjevs approved these changes

2022-01-05 18:23 UTC, merged