#3833 - Show unavailable items in a dropdown
scandipwa/scandipwa pull request #3915
Opened 2021-12-10 09:40 UTC by IrinaZhadzinets

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3833

**Problem:**
* Unavailable dropbox items are not displayed in product options

**In this PR:**
* All elements of the dropdown are displayed, without the event on inaccessible elements

2021-12-10 12:34 UTC, AleksandrsKondratjevs requested changes

2021-12-10 12:34 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/FieldSelect/FieldSelect.component.js
> +        const isDisabled = option.isAvailable !== undefined ? !option.isAvailable : false;
Please destruct isAvailable from option and set default value for it, so you could just pass it to mods without checking if it is undefined.

2021-12-14 11:55 UTC, AleksandrsKondratjevs approved these changes

2021-12-14 12:54 UTC, Elena-Evsa commented
Issue 1: out of stock options is not disabled on mobile
Expected result: 
![image](https://user-images.githubusercontent.com/84388061/146002178-a936386c-baee-4c04-bd9d-7c7ea8567952.png)

2021-12-17 12:20 UTC, merged