[3750] Error message for not long enough password
scandipwa/scandipwa pull request #3924
Opened 2021-12-13 10:05 UTC by Dagnija-Viktorova

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3750

**Problem:**
* No custom error message when entered password is less than 8 characters

**In this PR:**
* Added to validation rules error message 'Password should be at least 8 characters long' with min range 8 to sign in, confirm account, reset password and change password forms

2021-12-15 13:01 UTC, Elena-Evsa commented
Issue 1: field 'New password' in My Account > Account Information > Change Password has no same validation, 
Field 'New password' stay green and error message appear
Field should become red and error message appear under the field
https://vimeo.com/656995356/89f8a2b7c8
Issue 2: validation absent on confirm account page 
![image](https://user-images.githubusercontent.com/84388061/146191176-23c501f7-a5e1-44a1-90c8-603150715e17.png)

2021-12-22 14:42 UTC, Elena-Evsa commented
Issue 1: Passed
Issue 2: please add word 'characters' after number of symbols everythere after 'Password should be at least Х' 
![image](https://user-images.githubusercontent.com/84388061/147103096-3fac3e56-7543-4e4b-803f-17a3a4c2e5a3.png)

2021-12-23 13:21 UTC, Dagnija-Viktorova commented
Changed password length fail message as requested, can it pass QA?

2022-01-04 09:52 UTC, Elena-Evsa commented
Please, take a look on Issue 3

2022-01-04 16:59 UTC, tatiana-scandi commented on packages/scandipwa/src/component/PasswordChangeForm/PasswordChangeForm.form.js
> +                onRangeFailMin: `Password should be at least ${props.minimumPasswordLength} characters`
Why not just pass `minimumPasswordLength` as function parameter?

2022-01-04 17:00 UTC, tatiana-scandi commented on packages/scandipwa/src/route/ConfirmAccountPage/ConfirmAccountPage.component.js
> +                          onRangeFailMin: `Password should be at least ${minimumPasswordLength} characters`
Please, use a translatable string here.

2022-01-04 17:00 UTC, tatiana-scandi commented on packages/scandipwa/src/component/PasswordChangeForm/PasswordChangeForm.form.js
> +                onRangeFailMin: `Password should be at least ${props.minimumPasswordLength} characters`
+ Please, use a translatable string here.

2022-01-04 17:02 UTC, tatiana-scandi commented on packages/scandipwa/src/component/MyAccountSignIn/MyAccountSignIn.component.js
> +                          onRangeFailMin: `Password should be at least ${minimumPasswordLength} characters`
Please, use a translatable string here + think of a way to reuse password fields + validation logic (now there is too much duplicated code)

2022-01-04 17:03 UTC, tatiana-scandi requested changes
CR failed.

2022-01-24 12:48 UTC, carinadues commented
Issue will be fixed in https://github.com/scandipwa/scandipwa/pull/4145

2022-01-24 12:48 UTC, closed without merging