[3562] Notification on submitting forgot password
scandipwa/scandipwa pull request #3925
Opened 2021-12-13 13:48 UTC by Dagnija-Viktorova

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3562

**Problem:**
* When submitting forgot password form a duplicate notification is shown

**In this PR:**
* Removed showNotification() from MyAccountOverlay container when forgot password request is sent

2021-12-17 10:08 UTC, Elena-Evsa commented
Issue 1: Success message does not appear on Forgot password page
https://vimeo.com/657769849/c98df2c8b2
Same on mobile

2021-12-20 11:29 UTC, Dagnija-Viktorova commented
Fixed the notification showing up in the wrong place or not at all, can the pull request get approved?

2022-01-03 13:33 UTC, AleksandrsKondratjevs requested changes
Maybe I miss something, but check please comments and correct me if I didn't understood it right

2022-01-03 13:33 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/ForgotPassword/ForgotPassword.component.js
> +                { this.renderForgotPassword(isForgotPasswordPage) }
Where this value is used in MyAccountOverlay renderForgotPassword function?

2022-01-03 13:33 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.container.js
> +        if (isPasswordForgotSend !== currentIsPasswordForgotSend && isForgotPasswordPage && !isOverlayVisible) {
Out here it always will be false

2022-01-03 13:33 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/ForgotPassword/ForgotPassword.container.js
> +            isForgotPasswordPage
Is it even necessary to set prop if you can just set argument in function above to false and pass it to component where you need it?

2022-01-24 12:50 UTC, carinadues commented
Issue will be fixed in https://github.com/scandipwa/scandipwa/pull/4146

2022-01-24 12:50 UTC, closed without merging