#3575 - Add selected option for swatch attribute to title
scandipwa/scandipwa pull request #3949
Opened 2021-12-17 07:36 UTC by IrinaZhadzinets

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3575

**Problem:**
* Switch attribute not display label for selected option

**In this PR:**
* Selected option label to display for switch attribute

2021-12-20 10:07 UTC, AleksandrsKondratjevs requested changes

2021-12-20 10:07 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductConfigurableAttributes/ProductConfigurableAttributes.style.scss
> +            padding-left: 17px;
Change to logic property

2021-12-20 10:07 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductConfigurableAttributes/ProductConfigurableAttributes.component.js
> +                            <span block="ProductConfigurableAttributes" elem="Title" mods={ { selectedOption: true } }>
Why just not to set elem like: 'OptionLabel' or something like that ?

2022-01-11 14:38 UTC, AleksandrsKondratjevs approved these changes

2022-01-12 15:09 UTC, carinadues commented
@IrinaZhadzinets please fix the merge conflicts :))

2022-01-12 15:56 UTC, merged