#3933 - Add comments in order
scandipwa/scandipwa pull request #3992
Opened 2021-12-27 13:46 UTC by IrinaZhadzinets

**Related issue(s):**
* https://github.com/scandipwa/scandipwa/issues/3933
* https://github.com/scandipwa/sales-graphql/pull/5

**Problem:**
* Lack of comments on the order on the frontend

**In this PR:**
* Add comment in order in my account if user left comment in Admin panel

2022-01-04 16:05 UTC, AleksandrsKondratjevs approved these changes
@aleksandrakorolova,

Won't in this PR also fit comments for shipment and invoices (if they can be rendered on FE)?

2022-01-05 08:43 UTC, aleksandrakorolova commented
@AleksandrsKondratjevs 
You are right! We can set visible comments for shipment, invoice, and refund

@IrinaZhadzinets 
Please, add comments  for shipment, invoice, and refund

2022-01-11 14:36 UTC, AleksandrsKondratjevs requested changes
Nice! Just some minor changes required

2022-01-11 14:36 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/MyAccountOrderItemsTable/MyAccountOrderItemsTable.style.scss
> +            margin-top: 20px;
Use logic properties

2022-01-11 14:55 UTC, AleksandrsKondratjevs approved these changes

2022-01-12 00:10 UTC, merged