issue-3939 - Issues with customer orders
scandipwa/scandipwa pull request #4002
Opened 2021-12-30 09:27 UTC by AleksandrsKondratjevs

**Related issue(s):**
* Fixes #3939 

**Problem:**
* Issues with customer orders functionality and styles

**In this PR:**
* Fixing issues with customer orders.

2022-01-06 08:01 UTC, aleksandrakorolova commented
1. Fixed
2. Fixed
3. Fixed
4. Fixed
5. Fixed
6. Tabs are fixed but still, can reproduce Name of table columns and value are displayed as Product name: {productName} (only Quantity is displayed correctly)
![Screenshot 2022-01-06 at 09 23 43](https://user-images.githubusercontent.com/73526235/148344842-76c40fa5-fb3d-4fe8-99bf-40f9405e8d42.png)
7. Fixed
8. Fixed
9. Fixed
10. Mobile: Words 'Product name' is shifted slightly up
![Screenshot 2022-01-06 at 10 00 46](https://user-images.githubusercontent.com/73526235/148349379-086a3ef1-d780-48be-96c2-c9989973cac2.png)
11. Button Back doesn't work on order page
https://drive.google.com/file/d/1SWK-3wLBixPbLQ8Lrj-Nr8_ME5QbNELv/view?usp=sharing

2022-01-19 12:58 UTC, aleksandrakorolova commented
6 and 10 need to check after print feature 
11.Fixed

2022-01-20 09:00 UTC, riha112 requested changes

2022-01-20 09:23 UTC, riha112 approved these changes
CR passed

2022-01-20 14:22 UTC, merged