#3956 Hover effect is absent on billing options
scandipwa/scandipwa pull request #4052
Opened 2022-01-06 18:18 UTC by iman-sujamiko

**Related issue(s):**
* [#3956 Hover effect is absent on billing options](https://github.com/scandipwa/scandipwa/issues/3956)

**Problem:**
* Hover effect is absent on billing options

**In this PR:**
* change .Field_type_checkbox pointer-events from none to auto
* wrap billing options title in label pointed to billing options input checkbox

2022-01-07 12:05 UTC, Sliceem approved these changes

2022-01-07 12:39 UTC, AleksandrsKondratjevs approved these changes

2022-01-07 12:40 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CheckoutPayment/CheckoutPayment.style.scss
> +        pointer-events: auto;
If auto then do we even need it ? I guess it is auto by default.

2022-01-07 13:12 UTC, aleksandrakorolova commented
Please, add hover effect for text (name of option) too + change cursor to 'hand' when hovering the mouse over text option

2022-01-10 06:43 UTC, aleksandrakorolova commented
Still, the hover effect is missing for text. It doesn't become orange. Please, change text color when hovering on it as it works in Layered navigation on PLP
![Screenshot 2022-01-10 at 08 29 09](https://user-images.githubusercontent.com/73526235/148725873-d59a88b6-f528-4ba1-a8a5-f9c0ea07f57d.png)

2022-01-11 11:46 UTC, AleksandrsKondratjevs requested changes

2022-01-11 11:46 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/Field/Field.style.scss
> +            @include desktop {
Add space between

2022-01-11 12:21 UTC, AleksandrsKondratjevs approved these changes

2022-01-11 13:52 UTC, merged