#3928 Wrong space between last subcategory and category in mobile menu
scandipwa/scandipwa pull request #4058
Opened 2022-01-07 11:09 UTC by iman-sujamiko

**Related issue(s):**
* [#3928 Wrong space between last subcategory and category in mobile menu](https://github.com/scandipwa/scandipwa/issues/3928)

**Problem:**
* Wrong space between last subcategory and category in the mobile menu it should be 22px

**In this PR:**
* adding margin-bottom: 22px to _isVisible mobile state

2022-01-07 12:06 UTC, Sliceem approved these changes

2022-01-07 12:41 UTC, AleksandrsKondratjevs requested changes

2022-01-07 12:41 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/Menu/Menu.style.scss
> +                    margin-bottom: 22px;
Please use logic properties.

2022-01-07 14:43 UTC, AleksandrsKondratjevs approved these changes

2022-01-10 05:56 UTC, aleksandrakorolova commented
Still, can reproduce
![Screenshot 2022-01-10 at 07 52 27](https://user-images.githubusercontent.com/73526235/148723580-73ddbc8f-1218-46ae-a12b-0f48e8e15b57.png)

2022-01-11 11:45 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/Menu/Menu.style.scss
> +                    margin-block-end: 0px;
You can set without px in this case.

2022-01-11 12:21 UTC, AleksandrsKondratjevs approved these changes

2022-01-11 13:53 UTC, merged