#4010 Required star on the same line as required field
scandipwa/scandipwa pull request #4065
Opened 2022-01-10 21:07 UTC by BrunoScorzafave

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4010

**Problem:**
* Star for customizable product option is in the next line of its fields

**In this PR:**
* Now required start is on the same line as required field

2022-01-11 07:41 UTC, Elena-Evsa commented
Issue 1: Space is absent between star and price of option or title of option if price absent
![image](https://user-images.githubusercontent.com/84388061/148900070-a68abb04-9517-49ed-8ef4-df5b77b1b29f.png)

2022-01-13 16:18 UTC, AleksandrsKondratjevs requested changes

2022-01-13 19:55 UTC, BrunoScorzafave commented on packages/scandipwa/src/component/ProductCustomizableOptions/ProductCustomizableOptions.style.scss
> +        margin-left: 4px;
I think I'd use "git checkout --no-track -b <branch name> scandipwa/master" to create. This is the right way?

2022-01-13 23:14 UTC, AleksandrsKondratjevs approved these changes

2022-01-14 11:50 UTC, merged