#4018 Removed discount duplicate and added negative attribute to the discount value
scandipwa/scandipwa pull request #4074
Opened 2022-01-11 20:16 UTC by BrunoScorzafave

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4018

**Problem:**
* Word 'Discount' is duplicated + discount amount is displayed without symbol minus

**In this PR:**
* Discount duplicate removed and negative attribute added to the discount value

2022-01-12 09:10 UTC, aleksandrakorolova commented
1. Return word 'Discount' if cart price rule WITH coupon is applied to order 
![Screenshot 2022-01-12 at 11 08 25](https://user-images.githubusercontent.com/73526235/149097834-bccee353-f79b-410d-b600-fb6a301755d2.png)

2. Please, add '-' symbol to discount amount in Refunds tab
![Screenshot 2022-01-12 at 11 06 22](https://user-images.githubusercontent.com/73526235/149097432-6eb5612d-cc80-4b1a-9141-c8d45606254d.png)

2022-01-13 05:58 UTC, aleksandrakorolova commented
1. Need to display 'Discount{couponCode} {discountAmount}' is cart price rule WITH Coupon is applied to order. Please, return the coupon code also.
**Expected result:**
![Screenshot 2022-01-13 at 07 44 19](https://user-images.githubusercontent.com/73526235/149272806-f4fe3a5d-3e20-46d0-919b-7f4d0981322d.png)
2. Fixed

2022-01-14 08:08 UTC, aleksandrakorolova commented
@BrunoScorzafave Please, fix PR
![Screenshot 2022-01-14 at 09 39 08](https://user-images.githubusercontent.com/73526235/149473170-3c168699-8745-4ee5-95dd-900eedfc30c8.png)

2022-01-17 21:00 UTC, AleksandrsKondratjevs requested changes

2022-01-17 21:00 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/MyAccountOrderTotals/MyAccountOrderTotals.component.js
> +        if (label === 'Discount') {
Discount can be translatable, what in this case?

2022-01-17 21:00 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/MyAccountOrderTotals/MyAccountOrderTotals.component.js
> +        return this.renderPriceLine(__('Discount (%s)', label), -value, null, {}, `discount-${index}`);
Better to make check if it is default discount without label for it, this case if no label -> render default label `Discount`

2022-01-19 22:01 UTC, AleksandrsKondratjevs requested changes

2022-01-19 22:01 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/MyAccountOrderTotals/MyAccountOrderTotals.component.js
> +        return this.renderPriceLine(__('Discount (%s)', label), -value, null, {}, `discount-${index}`);
Make it simpler, like :
```
const discountLabel = label ? __('Discount (%s)', label)  : __('Discount');

return this.renderPriceLine(discountLabel, -value, null, {}, `discount-${index}`);
```

2022-01-21 13:18 UTC, Elena-Evsa commented
Issue 3: word discount still duplicated if user had discount and did not enter coupon 
![image](https://user-images.githubusercontent.com/84388061/150532725-43a5d177-618a-4d84-afd8-f2e2444531f8.png)

2022-02-01 11:49 UTC, BrunoScorzafave commented on packages/scandipwa/src/component/MyAccountOrderTotals/MyAccountOrderTotals.component.js
> +        return this.renderPriceLine(__('Discount (%s)', label), -value, null, {}, `discount-${index}`);
Done!

2022-02-02 07:05 UTC, Elena-Evsa commented
1. Passed
2. Passed
3. Failed: word 'discount' still duplicated
4. Passed

2022-02-02 07:07 UTC, AleksandrsKondratjevs commented
@Elena-Evsa 
BE PR is still not merged.
https://github.com/scandipwa/sales-graphql/pull/8

2022-02-04 12:29 UTC, aleksandrakorolova commented
3. Still, can reproduce 
![Screenshot 2022-02-04 at 14 28 58](https://user-images.githubusercontent.com/73526235/152529213-173f5989-0a1a-4dad-905f-e81d98da734a.png)

2022-02-25 07:51 UTC, Elena-Evsa commented
3. Still can reproduce
![image](https://user-images.githubusercontent.com/84388061/155676302-7c934237-a99d-473b-b1ba-2fc6395876db.png)

2022-03-07 12:27 UTC, aleksandrakorolova commented
3. Fixed
4. Please, add '-' symbol for discount in refund tab in mobile view
![Screenshot 2022-03-07 at 14 22 28](https://user-images.githubusercontent.com/73526235/157033733-4243adc2-607e-4542-8ca6-4dedbfbb54dc.png)

2022-03-10 20:59 UTC, AleksandrsKondratjevs requested changes

2022-03-10 20:59 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/MyAccountOrderTotals/MyAccountOrderTotals.component.js
> +        const discountLabel = (label && (label !== 'Discount')) ? __('Discount (%s)', label) : __('Discount');
It is hardcode, label can be translated and it will not be 'Discount' string in this case.

2022-03-21 07:04 UTC, AleksandrsKondratjevs approved these changes

2022-03-21 20:35 UTC, merged