#4060 Ooops page appears when opening /menu page in incognito mode
scandipwa/scandipwa pull request #4082
Opened 2022-01-13 06:21 UTC by iman-sujamiko

**Related issue(s):**
* Fixes [#4060 Ooops page appears when opening /menu page in incognito mode](https://github.com/scandipwa/scandipwa/issues/4060)

**Problem:**
* Ooops page appears when opening /menu page in incognito mode

**In this PR:**
* Change MenuPage.container to only call function redirectIfNotOnMobile() once in componentDidUpdate()

2022-01-13 13:43 UTC, aleksandrakorolova commented
User stays on /menu page and sees duplicate of menu
![Screenshot 2022-01-13 at 15 21 22](https://user-images.githubusercontent.com/73526235/149340561-d456b95e-f668-461b-a5b5-dd9f28de95ac.png)

**Expected result:**
User redirected to homepage in desktop layout

2022-01-14 08:07 UTC, aleksandrakorolova commented
Still, can reproduce 
https://drive.google.com/file/d/1NNQsR1Hn7SHdJ4U2FG4K5RJqlZb6qM1E/view?usp=sharing

2022-01-14 08:56 UTC, AleksandrsKondratjevs reviewed
@iman-sujamiko Hello.
Please check your code, amplify is failed to build it.
Look at history where from you importing it.

2022-01-17 12:05 UTC, AleksandrsKondratjevs requested changes

2022-01-17 12:05 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/MenuPage/MenuPage.container.js
> +
Namespace not needed here.

2022-01-17 12:05 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/MenuPage/MenuPage.container.js
> +             updateMeta({ title: __('Menu') });
Can you please make it more clear and less nesting, so if !isMobile then redirect and if is mobile, then do all things for page.

2022-01-17 12:05 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/MenuPage/MenuPage.container.js
> +     }
What is purpose of those indents?

2022-01-17 12:05 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/MenuPage/MenuPage.container.js
> +import history from 'Util/History';
Since issue was actually in appendWithStoreCode can we get back history from router ?

2022-01-17 12:56 UTC, closed without merging