#2574 added validation to detect missing StarReviews, marked it as required field, and error on not selected
scandipwa/scandipwa pull request #4095
Opened 2022-01-14 15:30 UTC by pablobentivengo

#2574 added validation to detect missing StarReviews, marked it as required field, and error on not selected

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/2574

**Problem:**
* Review form was not validation StarReviews as required

**In this PR:**
* Added validation on submitting the form in ProductReviewFormContainer, renderStarErros function in ProductReviewFormComponent, and finally added the required "*".

2022-01-19 09:54 UTC, Elena-Evsa commented
Issue 1: fixed
Issue 2: fixed
Issue 3: in RTL mode titles shown from left side, but should be from right side
Same logic for stars related to titles
![image](https://user-images.githubusercontent.com/84388061/150107002-a2421500-4ae4-4236-a7b9-5c9071fdfd70.png)

2022-01-20 09:54 UTC, Elena-Evsa commented
Issue 1: fixed
Issue 2: fixed
Issue 3: fixed
Issue 4: in LTR direction, quantity of stars increasing in wrong direction from right to left
https://vimeo.com/668142577/77efe210ee
Issue 5: RTL: message 'This field is required' situated from the right side of stars
![image](https://user-images.githubusercontent.com/84388061/150314571-e74b3553-e14a-4664-bd29-ff847d1f0090.png)

2022-01-26 07:59 UTC, riha112 requested changes
Implementation for star/rating validation can be done much simpler via `FieldGroup`.

Instead of creating separate validation logic you can add/wrap:
```js
<FieldGroup
  validationRule={ {
      isRequired: true,
      selector: '[type="radio"]'
  } }
>
    <fieldset block="ProductReviewForm" elem="Rating"....
    ...
</FieldGroup>
```
in `ProductReviewForm.component.js` -> `renderReviewRating`.

Form will then automatically validate it for you on submit.
(More info should be available here: https://www.notion.so/scandiweb/5-1-0-Config-Bundle-Form-Validation-update-v1-0-5366e403c9644a09ad634c5ffaada7cf#1844715db672410ea2a054889eb264b2)

2022-01-26 07:59 UTC, riha112 commented on packages/scandipwa/src/component/ReviewStar/ReviewStar.style.scss
> +    /* &:first-of-type {
delete commented-out lines, no need to keep them.

2022-01-26 07:59 UTC, riha112 commented on packages/scandipwa/src/component/ReviewStar/ReviewStar.style.scss
> +    margin-block-start: 0 !important;
Do not use `!important`, instead use higher priority class to override the rule.

2022-01-26 07:59 UTC, riha112 commented on packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.style.scss
> +
Delete one new line

2022-01-26 07:59 UTC, riha112 commented on packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.style.scss
> +        // margin-block-end: 16px;
delete commented-out lines, no need to keep them.

2022-01-28 08:02 UTC, riha112 requested changes

2022-01-28 08:02 UTC, riha112 commented on packages/scandipwa/src/component/ReviewStar/ReviewStar.style.scss
> +
Extra new line, should be only one

2022-02-02 06:32 UTC, riha112 approved these changes

2022-02-02 12:18 UTC, merged