#2608 Cross-sells products getting duplicated if user added config products to cart with different attributes options
scandipwa/scandipwa pull request #4102
Opened 2022-01-17 10:09 UTC by iman-sujamiko

**Related issue(s):**
* Fixes [#2608 Cross-sells products getting duplicated if user added config products to cart with different attributes options](https://github.com/scandipwa/scandipwa/issues/2608)

**Problem:**
* Cross-sells products getting duplicated in the cart if user added config products with different options to cart

**In this PR:**
* add filtering for duplicate product (configurable product) items that will be used to search Cross-sell Product

2022-01-19 12:04 UTC, Elena-Evsa commented
Issue 1: only related to product 'Cocktail dress' shown in cart in 'Frequently Bought Together' if product 'Cocktail dress' added to cart twice with different attributes and also added product 'Baggini Y' with other products 'Frequently Bought Together'

Expected result: in 'Frequently Bought Together' shown products for 'Cocktail dress' and 'Baggini Y'

Steps to reproduce: 
1. Open https://pr-4102.d25kd40decjpue.amplifyapp.com/default/n-cocktail-dress.html 
2. Select attributes 
3. Add to cart 
4. Select other attributes
5. Add to cart
6. Open https://pr-4102.d25kd40decjpue.amplifyapp.com/default/baggini-y.html
7. Add to cart
8. Open cart

![image](https://user-images.githubusercontent.com/84388061/150124461-b94dc6e9-7ace-4879-a4d3-c794a832e0a7.png)

Expected result:
![image](https://user-images.githubusercontent.com/84388061/150126064-51e50f7d-0832-4e62-9f09-8b0c294d8690.png)

2022-01-25 21:47 UTC, AleksandrsKondratjevs requested changes

2022-01-25 21:47 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/CartPage/CartPage.container.js
> +        );
Move it into util as function.

2022-01-25 21:47 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/CartPage/CartPage.container.js
> +                return (duplicate.product.id === item.product.id && duplicate.sku === item.sku);
Destruct objects.

2022-01-25 21:47 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/CartPage/CartPage.container.js
> +                return (duplicate.product.id === item.product.id && duplicate.sku === item.sku);
Space before return

2022-01-25 21:47 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/CartPage/CartPage.container.js
> +                return (duplicate.product.id === item.product.id && duplicate.sku === item.sku);
no need for braces if you make return in one line

2022-01-25 21:47 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/CartPage/CartPage.container.js
> +                }
Unify it

2022-01-27 08:10 UTC, AleksandrsKondratjevs approved these changes

2022-01-27 08:10 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/util/Cart/Cart.js
> +        if (index === 0 || itemVariants.length === 0) {
won't this be same as `!index || !itemsVariants.length` ?

2022-01-27 12:25 UTC, merged