[4090] Hover effect on 'I agree to terms and conditions' fix
scandipwa/scandipwa pull request #4114
Opened 2022-01-18 10:04 UTC by Mohamed-halim-sw

**Related issue(s):**
* Fixes [https://github.com/scandipwa/scandipwa/issues/4078]

**Problem:**
* [Hover effect on ' I agree to terms and conditions was not matching the requirements.]

**In this PR:**
* [I added a hover selector to the "checkoutBilling.style.scss"  file under TACLabel class ]

2022-01-19 13:13 UTC, aleksandrakorolova commented
Hover effect shouldn't display for text and checkbox when hovering mouse over link 'Read more'. 
https://drive.google.com/file/d/1MG67pWaBB4eDDf-k3Avc60CMMF9Uz9zM/view?usp=sharing

2022-01-20 12:29 UTC, aleksandrakorolova commented
1. Link 'Read more' - **Fixed**
2. Please return hover effect for text when hovering mouse over checkbox as it works with payment methods
https://drive.google.com/file/d/1s1sCfkri7Kf9frgBEsrrVIn2aF7ZR0W_/view?usp=sharing

2022-01-25 13:35 UTC, ejnshtein requested changes

2022-01-25 13:35 UTC, ejnshtein commented on packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.style.scss
> +        margin-inline-start: .5em;
probably should add `0` (`0.5em`) to the value, as you did on line 88

2022-01-26 17:08 UTC, ejnshtein approved these changes

2022-01-26 17:17 UTC, merged