[4083] bullet list indent to right missing fix
scandipwa/scandipwa pull request #4116
Opened 2022-01-18 11:50 UTC by Mohamed-halim-sw

**Related issue(s):**
* Fixes scandipwa/scandipwa/issues/4083

**Problem:**
* the bullets were not indented in relation to the text

**In this PR:**
* made style changes to "shortDescription" class in "ProuctActions.style.scss" component style
* fixed position to relative
* added margin-inline-end
* added inset-block-start

2022-01-20 10:50 UTC, aleksandrakorolova commented
Fixed for short description on PDP

Still, can reproduce for:
1.  Description on PDP
![Screenshot 2022-01-19 at 12 44 52](https://user-images.githubusercontent.com/73526235/150323083-fd9db5ab-4ca2-4caa-a303-a13e9d9f43cf.png)
2. CMS Page
![Screenshot 2022-01-20 at 12 41 23](https://user-images.githubusercontent.com/73526235/150323393-824dbf5f-cbf8-4f7c-bd77-607b3d0dbc1a.png)
3. Category description on PLP
![Screenshot 2022-01-20 at 12 46 21](https://user-images.githubusercontent.com/73526235/150324192-03e5f80e-4704-4e2e-8643-c4d7a07f8311.png)

2022-01-24 12:00 UTC, Elena-Evsa commented
Please, recreate link
![image](https://user-images.githubusercontent.com/84388061/150779257-a2762e29-f2e9-4bba-878d-275599bfe2d1.png)

2022-01-25 10:16 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CategoryDetails/CategoryDetails.style.scss
> +
remove duplicate white space

2022-01-25 10:16 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductInformation/ProductInformation.style.scss
> +
remove this white space

2022-01-25 10:16 UTC, AleksandrsKondratjevs requested changes
See comments

2022-01-27 12:10 UTC, Elena-Evsa commented
1. Fixed
2. Fixed
3. Fixed
4. Wrong indent betwen lines with bullets on PDP now it 20 px, but should be 6px
![image](https://user-images.githubusercontent.com/84388061/151355402-e2a16b0a-b2bf-44a8-bced-70eeef67a4e7.png)

2022-01-28 17:02 UTC, Elena-Evsa commented
4. Please, Make the styling of indents as on master
Now margin from the top and botom present
Indent after paragraphs = 6 px, but should be 14 px
![image](https://user-images.githubusercontent.com/84388061/151589334-3d2c3ca6-48df-4552-b427-ffa0192e4c01.png)
Here the example of product description of which you can compare
https://master.d25kd40decjpue.amplifyapp.com/default/bundl-with-out-of-stock-radio-buttons.html
https://master.d25kd40decjpue.amplifyapp.com/default/n-cocktail-dress.html

2022-01-31 08:51 UTC, Elena-Evsa commented
1. Fixed
2. Fixed
3. Fixed
4. Fixed
5. Please, make margin after last bullet (now = 20px) same as after any other paragraph = 14px
![image](https://user-images.githubusercontent.com/84388061/151764104-3f3d1590-387a-4bb7-8b36-86d9753974e1.png)

2022-01-31 09:25 UTC, Elena-Evsa commented
1. Fixed
2. Fixed
3. Fixed
4. Fixed
5. Fixed

2022-02-02 06:43 UTC, AleksandrsKondratjevs requested changes

2022-02-02 06:43 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductInformation/ProductInformation.style.scss
> +            position: relative;
Make nesting as it was before
```
li {
   &::before {
   ....
   }
}
```

2022-02-02 06:43 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CategoryDetails/CategoryDetails.style.scss
> +            position: relative;
Same here

2022-02-03 06:27 UTC, AleksandrsKondratjevs requested changes

2022-02-03 06:27 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/Html/Html.component.js
> +        }
I guess it is applied in another PR

2022-02-03 06:27 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductInformation/ProductInformation.style.scss
> +
Remove this space

2022-02-04 10:39 UTC, AleksandrsKondratjevs approved these changes

2022-02-04 11:23 UTC, merged