3785 extends PR https://github.com/scandipwa/scandipwa/pull/4093
scandipwa/scandipwa pull request #4133
Opened 2022-01-20 09:36 UTC by pablobentivengo

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3785

**Problem:**
* Not scrolling to and shaking unselected options 

**In this PR:**
* Extends PR https://github.com/scandipwa/scandipwa/pull/4093

2022-01-24 12:35 UTC, Elena-Evsa commented
Issue 7: Animation of shaking absent 
https://vimeo.com/669396048/bbaba8bde9

2022-02-07 09:43 UTC, aleksandrakorolova commented
1. Animation of shaking is missing for dropdown - https://drive.google.com/file/d/1VOHeyqFWpMcJ_5NBIdNmHWPtZuDT7T0d/view?usp=sharing
2. Please, do animation of shaking more smooth as it was before (https://5-0-0-rc.d25kd40decjpue.amplifyapp.com/default/n-cocktail-dress.html)

2022-02-08 07:49 UTC, aleksandrakorolova commented
1. Fixed
2. Fixed
3. Page scrolls to the review/status. User can't see options at all in mobile view if product has long 'short description'
https://drive.google.com/file/d/1PRKSis0VyKsbtku-lboKtexC3cKauHR3/view?usp=sharing
1st part of video - PR
2nd part of video - 5-0-0.
Please, do the same as in 5-0-0

2022-02-09 06:04 UTC, aleksandrakorolova commented
3. Fixed
4. Quantity control buttons are shifted up 
Screenshot: lest side - PR, right side - master
![Screenshot 2022-02-09 at 07 57 23](https://user-images.githubusercontent.com/73526235/153131445-869ba9ab-e3c7-4291-a837-9eee5cc1a0b5.png)

2022-02-09 13:26 UTC, ejnshtein requested changes

2022-02-09 15:52 UTC, pablobentivengo commented on packages/scandipwa/src/component/Product/Product.container.js
> +        Object.keys(configurable_options).forEach((option) => {
Hey! I ran a test to see performance and it was pretty much the same. Even though I changed it to **reduce**, I think it makes the code shorter and simpler. Let me know what you think.

![image](https://user-images.githubusercontent.com/97158749/153237165-1bcfbc67-bde2-4392-bb03-20c68c911592.png)

2022-02-10 13:23 UTC, ejnshtein approved these changes

2022-02-10 13:31 UTC, merged