[4078] Loader missing on checkout page fix
scandipwa/scandipwa pull request #4134
Opened 2022-01-20 10:08 UTC by Mohamed-halim-sw

**Related issue(s):**
* Fixes scandipwa/scandipwa/issues/4078

**Problem:**
* summary block loader is missing while logging in and displays "0 items" instead.

**In this PR:**
* Cart.action
   	* line 18 added action type,
	* line 85-89 added updateIsLoading function,
	
* Cart.reducer
	* line 15 import UPDATE_TOTALS_IS_LOADING TYPE,
	* line 81-86 added UPDATE_TOTAL_IS_LOADING case and it's return,
	* line 44 added isloading:false in updatecarttotals method return
	* line 66 added isloading:false in initial state
	
* Cart.dispatcher 
	* line 13 import updateIsLoading
	* line 256 to 258 added _updateCartIsLoading function
	* line 54 call dispatch on updatecartisloading set to true
	* line 41 call dispatch on updatecartisloading set to false
	
* CheckoutOrderSummary.container
	* line 33 added isloading prop
	
* CheckoutOrderSummary.component
	* line 18 import loader component
	* line 47 isloading prop
	* line 52 isloading defaultProp
	* line 328 added renderloader method
	* line 355 added a condition to render loader if isloading is true

2022-01-20 13:24 UTC, Elena-Evsa commented
Issue 1: Make the frame sized like on screenshot. Move loader to the center of frame
![image](https://user-images.githubusercontent.com/84388061/150347055-a9061da4-d5d9-41b5-9ea2-35371f188e3e.png)

2022-01-25 21:44 UTC, AleksandrsKondratjevs requested changes

2022-01-25 21:44 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
> +                { this.renderLoader() }
In this case can just pass component loader without making a function.

2022-01-25 21:44 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
>          return (
Space before return

2022-01-25 21:44 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.container.js
> +
redundant space

2022-01-25 21:44 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/Checkout/Checkout.component.js
> +
Same here, no need space

2022-01-25 21:44 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/Checkout/Checkout.component.js
> +
also here

2022-01-25 21:44 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/store/Cart/Cart.dispatcher.js
> +            this._updateCartIsLoading(true, dispatch);
No need for function, can directly call dispatch update is loading.

2022-01-25 21:44 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/store/Cart/Cart.dispatcher.js
>              return this._updateCartData(cartData, dispatch);
Space before return

2022-01-25 21:44 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/store/Cart/Cart.reducer.js
> +        return {
space before return

2022-01-25 21:44 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/store/Cart/Cart.action.js
> +});
make semantically correct name of function, like updateIsLoadingCart, same for type

2022-01-25 21:45 UTC, AleksandrsKondratjevs commented on packages/scandipwa/package.json
> +    "proxy": "https://scandipwapmrev.indvp.com/"
Get it back

2022-01-26 10:15 UTC, Mohamed-halim-sw commented on packages/scandipwa/src/store/Cart/Cart.reducer.js
> +        return {
do i need to add space?

2022-01-26 10:16 UTC, Mohamed-halim-sw commented on packages/scandipwa/package.json
> +    "proxy": "https://scandipwapmrev.indvp.com/"
get it to demo100?

2022-01-26 10:35 UTC, AleksandrsKondratjevs commented on packages/scandipwa/package.json
> +    "proxy": "https://scandipwapmrev.indvp.com/"
yes

2022-01-27 08:14 UTC, AleksandrsKondratjevs approved these changes

2022-01-27 12:23 UTC, merged