[4126]  modified text align to start
scandipwa/scandipwa pull request #4163
Opened 2022-01-25 14:51 UTC by pablobentivengo

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4126

**Problem:**
* Product review text was justify instead of left alignment

**In this PR:**
* Modified ProductReviewItem style. Text alignment set to "start"

2022-01-31 14:27 UTC, riha112 requested changes

2022-01-31 14:27 UTC, riha112 commented on packages/scandipwa/src/component/ProductReviewItem/ProductReviewItem.style.scss
> +
Extra new line, can be deleted.

2022-01-31 17:05 UTC, pablobentivengo commented on packages/scandipwa/src/component/ProductReviewItem/ProductReviewItem.style.scss
> +
Done!

2022-02-02 06:29 UTC, riha112 approved these changes

2022-02-02 12:04 UTC, merged