[3563] Incorrect message appears in ChangePasswordPage
scandipwa/scandipwa pull request #4175
Opened 2022-01-26 20:17 UTC by BrunoScorzafave

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3563

**Problem:**
* Fields don't have validation rules
* Incorrect message appears in  ChangePasswordPage

**In this PR:**
* Create validation rules for password fields

2022-02-02 07:47 UTC, aleksandrakorolova commented
1. Still can reproduce
![Screenshot 2022-02-02 at 09 35 08 (2)](https://user-images.githubusercontent.com/73526235/152112409-9b240822-e754-4d29-830a-a5bc0f13b8dd.png)

2. Field border is grey if user entered new password
![Screenshot 2022-02-02 at 09 30 37](https://user-images.githubusercontent.com/73526235/152111998-1eb60270-dc4d-48f8-b875-29234b53eb7d.png)

**Expected result:**
Field is green as in screenshot
![Screenshot 2022-02-02 at 09 32 46](https://user-images.githubusercontent.com/73526235/152112156-033390fe-1c69-4b74-8ce7-fe3b41e86a59.png)

**Notes:**
New password validation happens only when submitting form (the same situation with error messages). Please return form validation as it was (it happens immediately)

2022-02-03 06:08 UTC, aleksandrakorolova commented
Still, can reproduce

2022-02-22 08:25 UTC, aleksandrakorolova commented
1. Still, can reproduce
2. Fixed
3. Error message 'Incorrect input!' appears below Confirm password field
Please return the previous error message 'Passwords do not match!' if user entered different passwords in New password and Confirm password fields
![Screenshot 2022-02-22 at 10 19 48 (2)](https://user-images.githubusercontent.com/73526235/155091439-77538be0-006a-41dd-b715-3e496fc14c18.png)

2022-03-10 09:28 UTC, aleksandrakorolova commented
1. Fixed 
now error message appears immediately below field
2. Fixed
3. Still can reproduce
![Screenshot 2022-03-10 at 11 26 54](https://user-images.githubusercontent.com/73526235/157631992-47de2dc2-49c5-442b-9d1b-6d17c11e9ab6.png)

2022-03-24 07:38 UTC, riha112 requested changes

2022-03-24 07:38 UTC, riha112 commented on packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.config.js
> +export const MIN_CHARACTER_SETS_IN_PASSWORD = 3;
This is never used.

2022-03-29 06:27 UTC, riha112 approved these changes

2022-03-29 10:12 UTC, merged