[3456] modified advertising string, removed TierPrice rendering
scandipwa/scandipwa pull request #4192
Opened 2022-01-28 12:28 UTC by pablobentivengo

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3456

**Problem:**
* Advertising message shows Price value per item.
* Product Card rendered "As Low As" tag price

**In this PR:**
* Modified string for advertising message
* Removed As Low As tag

2022-02-02 11:17 UTC, aleksandrakorolova commented
1. Apply fixes mentioned in the task only for bundle product (display message in this format 'Buy 2 with 10% discount each')
2. Please, return previous logic for all products except bundle product (display message in this format 'Buy 2 for US$14.04 each and save 10%')
![Screenshot 2022-02-02 at 12 51 16](https://user-images.githubusercontent.com/73526235/152140296-e600a1c2-7703-44d4-a64b-1c68aa150baa.png)

3. Also, return 'As low as'  on PLP and PDP for all products except bundle product
![Screenshot 2022-02-02 at 12 51 38](https://user-images.githubusercontent.com/73526235/152140312-11241f0f-50b3-4b8a-aaa3-d7746b1441b7.png)

2022-02-03 10:05 UTC, aleksandrakorolova commented
1. Please, add word '**discount**' for bundle product as I wrote in previous comment ('Buy 2 with 10% **discount** each')
2. Fixed
3. Fixed

2022-02-04 11:58 UTC, AleksandrsKondratjevs requested changes
Looks good for me.
Some minor changes required.

2022-02-04 11:58 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/TierPrices/TierPrices.component.js
> +            </>
I assume indent out here is not correct

2022-02-04 11:58 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/TierPrices/TierPrices.component.js
> +            </>
Same here

2022-02-04 11:59 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/TierPrices/TierPrices.component.js
> -
Return white space.

2022-02-04 12:14 UTC, pablobentivengo commented on packages/scandipwa/src/component/TierPrices/TierPrices.component.js
> -
Done!

2022-02-04 12:14 UTC, pablobentivengo commented on packages/scandipwa/src/component/TierPrices/TierPrices.component.js
> +            </>
Done!

2022-02-04 12:14 UTC, pablobentivengo commented on packages/scandipwa/src/component/TierPrices/TierPrices.component.js
> +            </>
Done!

2022-02-07 15:35 UTC, merged