[4120] block with widgets width fix
scandipwa/scandipwa pull request #4208
Opened 2022-01-31 17:44 UTC by Mohamed-halim-sw

**Related issue(s):**
* Fixes scandipwa/scandipwa/issues/4120

**Problem:**
* Product list widget width fix

**In this PR:**
* CmsPage.style.scss 
      * removed margin from line 118.

2022-02-01 11:49 UTC, Elena-Evsa commented
1. Block with New and recently viewed products are aligned, cards from catalog product list widget is not aligned

![image](https://user-images.githubusercontent.com/84388061/151960735-0067ca97-f332-45db-ab8d-47e0ef3ce2c1.png)

2022-02-03 10:22 UTC, Elena-Evsa commented
1. Passed
2. Same situation on About us page: widget (New products or Category) should be sized with content on any CMS page
![image](https://user-images.githubusercontent.com/84388061/152324204-17f34119-acd4-4899-afdc-154bb7ad0e0d.png)

2022-02-07 09:12 UTC, aleksandrakorolova commented
2. Fixed
3. PLP doesn't have padding on the left and right side
![Screenshot 2022-02-07 at 11 07 48](https://user-images.githubusercontent.com/73526235/152758599-0ba2dceb-524b-4b2f-a6b5-13eef2f1b2bf.png)

2022-02-21 09:26 UTC, aleksandrakorolova commented
2. Please, use the same padding-inline as on other pages (14px)
![Screenshot 2022-02-21 at 11 01 02](https://user-images.githubusercontent.com/73526235/154926271-ff8a8c63-85eb-493b-90cd-319d3e38c423.png)

2022-03-07 17:12 UTC, AleksandrsKondratjevs approved these changes

2022-03-07 17:12 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/Html/Html.component.js
> -
No need to remove this white space.

2022-03-07 17:12 UTC, AleksandrsKondratjevs requested changes
See comments

2022-03-16 13:54 UTC, AleksandrsKondratjevs requested changes

2022-03-17 09:21 UTC, AleksandrsKondratjevs approved these changes

2022-03-17 09:21 UTC, merged