4205
scandipwa/scandipwa pull request #4214
Opened 2022-02-01 18:05 UTC by Mohamed-halim-sw

**Related issue(s):**
* Fixes scandipwa/scandipwa/issues/4205

**Problem:**
* oops page displays instead of requested URL.

**In this PR:**
* Html.component.js
	* lines from 240-244 handled data absence.
	* lines from 259-261 handled script being a number.

2022-02-03 06:25 UTC, AleksandrsKondratjevs requested changes

2022-02-03 06:25 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/Html/Html.component.js
>          this.createdOutsideElements[elemHash] = true;
Good to have white-space after if block

2022-02-04 10:38 UTC, AleksandrsKondratjevs approved these changes

2022-02-04 11:20 UTC, merged

2023-05-19 12:27 UTC, Andrii-Antoniuk commented
Hi! @Mohamed-halim-sw 
I was wondering how this change is affecting the actual check.
As for me, script always will be **NaN**