[4138] coupon field missing fix
scandipwa/scandipwa pull request #4215
Opened 2022-02-01 18:16 UTC by Mohamed-halim-sw

**Related issue(s):**
* Fixes scandipwa/scandipwa/issues/4138

**Problem:**
* coupon component was missing on the checkout page.

**In this PR:**
* Checkout.component.js
	* line 471 rendered cartCoupon component

* CartCoupon.style.scss
	* line 43 to 46 styled the form to be block when computer screen is less than 1026px

2022-02-03 12:11 UTC, aleksandrakorolova commented
1. Coupon field is displayed on shipping page too. But it should display only on billing page as in default magenta
![Screenshot 2022-02-03 at 13 25 44](https://user-images.githubusercontent.com/73526235/152334241-6bf2698d-4801-4bc2-981c-09b4b7bec776.png)
2. Coupon field is displayed on billing step if user applied coupon in the cart
**Steps:**
Open PDP
Add to cart
Open Cart
Apply Coupon
Go to shipping step
Fill form
Go to billing step

**Actual result**
Coupon field is displayed 

**Expected result:**
Text' Applied coupon code: 50OFF' and button 'Remove coupon' are displayed as in screenshot
![Screenshot 2022-02-03 at 14 08 20](https://user-images.githubusercontent.com/73526235/152340189-4fc48102-fda3-4e4d-bb28-1844f9047fff.png)

2022-02-07 08:07 UTC, aleksandrakorolova commented
1. Fixed
2. Fixed
3. Coupon block is displayed few sec on success complete order page
https://drive.google.com/file/d/1flgJaX4S4d-UiCslm92Rs-54Pywqemyh/view?usp=sharing

2022-02-08 06:10 UTC, aleksandrakorolova commented
3. Fixed
4. Mobile: coupon block is displayed below payments methods
![Screenshot 2022-02-08 at 07 59 57](https://user-images.githubusercontent.com/73526235/152927617-dd7b8895-5e76-4eff-abd7-0b95e997a8f1.png)

**Expected result:**
it's displayed in summary block as in desktop view

2022-02-09 07:03 UTC, aleksandrakorolova commented
Read carefully comments, move coupon field IN summary block

**Actual result:**
Coupon field is displayed below summary block
<img src="https://user-images.githubusercontent.com/73526235/153134181-58b10a19-c15d-434f-9608-e6d27d346ca1.PNG" width=“385” height="700">

 **Expected result:**
 Coupon field is displayed in the summary block

2022-02-10 05:49 UTC, aleksandrakorolova commented
1. Coupon should be displayed in Summary block only in mobile view. On desktop view - coupon field is displayed below summary block
2. Coupon field is unwrapped in mobile. 
**Expected result:**
Coupon field is always wrapped in mobile

2022-02-11 06:02 UTC, aleksandrakorolova commented
5. Fixed
6. Fixed
7. Mobile: Text 'Have a discount code?' is missing above coupon field
![Screenshot 2022-02-11 at 08 00 01](https://user-images.githubusercontent.com/73526235/153544352-fa145520-2281-4722-9200-aba577de36ca.png)

2022-02-23 12:05 UTC, AleksandrsKondratjevs requested changes

2022-02-23 12:05 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
> +        return null;
Make it simplier, can even create separate function for rendering mobile version.

1. checkout step is not billing step => return null;
2. if is mobile => render mobile version;
3. default render just expandablecontent.

2022-02-23 12:05 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
> +                    Have a discount code?
Translation?

2022-02-23 12:05 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
> +                  mix={ { block: 'CartPage', elem: 'Discount' } }
Is block correct?

2022-02-23 12:05 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
> +                      mix={ { block: 'CartPage', elem: 'ExpandableContentHeading' } }
Is block correct?

2022-02-23 12:05 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/Checkout/Checkout.component.js
> +                  heading={ __('Have a discount code?') }
Is block correct?

2022-02-23 12:05 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/Checkout/Checkout.component.js
> +    }
if checkout step not billing, return null before.

2022-02-23 12:05 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/Checkout/Checkout.component.js
> +            { !showOnMobile && this.renderDiscountCode() }
Indent out here is not correct.

2022-02-23 23:14 UTC, AleksandrsKondratjevs requested changes

2022-02-23 23:14 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
> +        if (isMobile && checkoutStep === BILLING_STEP) {
U actually know that it is billing step

2022-02-23 23:14 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
> +        }
unify

2022-02-23 23:14 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
>          return (
space before return

2022-02-23 23:14 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
> +                { isMobile && this.renderDiscountCode() }
Im confused. Out here u check if mobile and then render. Why in this case in renderDiscountCode function it again checks if mobile and renders depending on it.

2022-02-23 23:14 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/Checkout/Checkout.component.js
> +        }
unify

2022-03-02 14:57 UTC, AleksandrsKondratjevs requested changes

2022-03-02 14:57 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
> +            <div>
use just fragment

2022-03-04 08:31 UTC, AleksandrsKondratjevs requested changes

2022-03-04 08:31 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/Checkout/Checkout.component.js
> +                  renderCmsBlock={ () => this.renderPromo(true) }
Fix it please

2022-03-04 08:31 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
> +                { __('Have a discount code?') }
Indent out here is not correct

2022-03-14 23:33 UTC, AleksandrsKondratjevs requested changes

2022-03-14 23:33 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/Checkout/Checkout.component.js
> +                // eslint-disable-next-line react/jsx-no-bind
remove eslint disable

2022-03-24 17:20 UTC, AleksandrsKondratjevs approved these changes

2022-03-28 12:46 UTC, merged