[4249] Added sublabel when maxcharacters bigger than 0
scandipwa/scandipwa pull request #4275
Opened 2022-02-10 08:40 UTC by pablobentivengo

**Related issue(s):**
* Fixes #4249 

**Problem:**
* 'Maximum X characters' absent under text field or area on PDP if parameter 'Max Characters' is set in admin

**In this PR:**
* Added sublabel when max_characters bigger than 0

2022-02-11 07:55 UTC, aleksandrakorolova commented
1. Text 'Maximum X characters (X remaining)' is bold
![Screenshot 2022-02-11 at 09 33 36](https://user-images.githubusercontent.com/73526235/153554035-2ae0524a-a8f0-46eb-804c-984fec8ca3a2.png)
**Expected result:**
Text isn't bold

2. Text '(X remaining)' is displayed if user didn't enter text in field
![Screenshot 2022-02-11 at 09 45 42](https://user-images.githubusercontent.com/73526235/153554486-78e896a1-9f63-4b82-b524-c81803f242f0.png)

**Expected result:**
Text '(X remaining)' appears when starting to enter text in the field as it works in default Magenta
![Screenshot 2022-02-11 at 09 54 31](https://user-images.githubusercontent.com/73526235/153555380-a3c64152-2283-4816-904c-2ea6e0a32044.png)

3. Error message 'Maximum X characters' appears below field if user entered more that max characters
![Screenshot 2022-02-11 at 09 50 01](https://user-images.githubusercontent.com/73526235/153554921-850b79b7-a8f5-4caf-b8e0-7aade770e329.png)
**Expected result:**
Error message 'Maximum X characters (Y too many)' appears as in default Magenta
![Screenshot 2022-02-11 at 09 53 30](https://user-images.githubusercontent.com/73526235/153555338-140a7acf-13a6-4c8d-aef0-0b887b6cbf30.png)

2022-02-14 06:11 UTC, aleksandrakorolova commented
1. Fixed
2. Fixed
3. Please, delete '!' symbol in the error message
4. Text 'Field required' is displayed below field for the required field if user didn't enter text in the field
![Screenshot 2022-02-14 at 07 59 10](https://user-images.githubusercontent.com/73526235/153808451-7e88d34f-3518-42c2-9fd1-e6c9c0a786dd.png)

2022-02-15 05:40 UTC, aleksandrakorolova commented
3. Still, can reproduce
4. Still can reproduce but now Text 'Field required' is displayed in the separate line
![Screenshot 2022-02-15 at 07 38 12](https://user-images.githubusercontent.com/73526235/153999387-8a0be156-3c18-4843-ab09-a14dce8ad2d7.png)

2022-02-16 06:06 UTC, aleksandrakorolova commented
3. Fixed
4. Fixed
5. Different errors appear to products with customizable products when entering more than max characters and trying to add product to cart in condition that all required options are selected

**Product 1:**
Error message 'Incorrect or missing options!' appears
![Screenshot 2022-02-16 at 07 49 13 (2)](https://user-images.githubusercontent.com/73526235/154204760-15be51f8-c854-48ed-9339-c54495fa4ca4.png)
**Product 2:**
Error message 'The text is too long. Shorten the text and try again.' appears
![Screenshot 2022-02-16 at 07 49 07 (2)](https://user-images.githubusercontent.com/73526235/154204811-fa18eb9c-17a3-4664-9e9e-34e6f4a0c25f.png)

**Expected result:**
Error message 'Please enter no more than X characters.' appears below text field/area as it works in default Magenta

2022-02-21 09:57 UTC, aleksandrakorolova commented
5. Still, error message 'The text is too long. Shorten the text and try again.' appears when adding product to cart
![Screenshot 2022-02-21 at 11 47 44 (2)](https://user-images.githubusercontent.com/73526235/154930865-76c8d36b-f30e-4cc1-a5d9-e6bf09a99933.png)

6. Error message 'Incorrect or missing options!' is missing when adding config/bundle product to cart (or product with required options)
https://drive.google.com/file/d/11Pc1-99qFjc4Q05hmaJcEAO5WhYzkL0O/view?usp=sharing

2022-02-22 08:56 UTC, aleksandrakorolova commented
5. Fixed
6. Fixed
7. Nothing happens when adding config product to cart from PLP if user can select all attributes from PLP
https://drive.google.com/file/d/1ehwTRfMeT5KWH46BuT3TB3IlDLNPfOwh/view?usp=sharing
**Expected result:**
- Shaking effect is displayed and error message appears if user can add product from PLP
- User redirects to PDP if user can't select all attributes from PLP (now it works correctly)

2022-02-24 06:59 UTC, aleksandrakorolova commented
7. Fixed
8. Error message 'Please enter no more than X characters.' disappears when adding more characters in the field 
**Steps:**
Open product - https://pr-4275.d25kd40decjpue.amplifyapp.com/default/testing-simple.html
Enter more X symbols in the field
Click on 'Add to cart'
Add one more symbol in the field

**Actual result:**
 Error message 'Please enter no more than X characters.' disappears 
https://drive.google.com/file/d/1l-jUsVttIz0elQ_p3HxcsRUWNdKF7s1s/view?usp=sharing

**Expected result:**
 Error message 'Please enter no more than X characters.' stays while characters won't be equal or less than X

2022-03-01 06:13 UTC, aleksandrakorolova commented
8. The expected result is not achieved. Now error message doesn't disappear if user removed extra characters 
https://drive.google.com/file/d/1dICS1QT1s1VxvVl6SL7UNZmQb8SdRhfj/view?usp=sharing

2022-03-01 10:10 UTC, pablobentivengo commented
Hey! Right now its working such as in Luma.
https://vimeo.com/683221476/7d34b50847

2022-03-01 11:26 UTC, aleksandrakorolova commented
Hey, we have different logic with error messages below field. Please, do the same as written in expected result because all other errors messages work as written in expected result (you can check message 'This field is required')
https://drive.google.com/file/d/1KYq3lpbPzb2O3hDwELJxpJf0R4l8Ljjn/view?usp=sharing

2022-03-03 14:03 UTC, aleksandrakorolova commented
8. Please, show this error message 'Please enter no more than X characters.' only when validating form (add product to cart)

**Steps:**
1. Open https://pr-4275.d25kd40decjpue.amplifyapp.com/default/jeans-for-girls.html
2. Enter more than X characters in the field
3. Add product to cart
4. Enter less than X characters in the field
5. Enter more than X characters in the field

**Actual result:**
2. Error message 'Please enter no more than X characters.' is missing (ok)
4. Error message 'Please enter no more than X characters.' is displayed (ok)
5. Error message 'Please enter no more than X characters.' is displayed

**Expected result:**
5. Error message 'Please enter no more than X characters.' is missing 
Error message 'Please enter no more than X characters.' appears only if user entered more than max characters and clicked 'Add to cart'

2022-03-07 06:07 UTC, aleksandrakorolova commented
8. Can reproduce: Error message 'Please enter no more than X characters.' disappears when adding more characters in the field
**Steps:**
1. Open product - https://pr-4275.d25kd40decjpue.amplifyapp.com/default/testing-simple.html
2. Enter more X symbols in the field
3. Click on 'Add to cart'
4. Add one more symbol in the field

**Actual result:**
Error message 'Please enter no more than X characters.' disappears
https://drive.google.com/file/d/1oQ_0YsATjhD1wEpIQk8NOt-gZ_xiFkx7/view?usp=sharing

**Expected result:**
Error message 'Please enter no more than X characters.' stays while characters won't be equal or less than X

2022-03-08 07:05 UTC, aleksandrakorolova commented
8. Again can reproduce https://github.com/scandipwa/scandipwa/pull/4275#issuecomment-1058072406

2022-03-14 23:06 UTC, AleksandrsKondratjevs requested changes

2022-03-14 23:06 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/util/Validator/Validator.js
> +                const tooMany = value.length - max;
Usually we use prefix 'is' for booleans

2022-03-14 23:06 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/util/Validator/Validator.js
> +                const tooMany = value.length - max;
Usually we use prefix 'is' for booleans

2022-03-14 23:06 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/Product/Product.container.js
> +            return true;
space before return.

2022-03-14 23:06 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/Product/Product.container.js
> +            return true;
space before return.

2022-03-15 10:56 UTC, pablobentivengo commented on packages/scandipwa/src/component/Field/Field.container.js
>          return output;
done

2022-03-15 10:56 UTC, pablobentivengo commented on packages/scandipwa/src/component/Field/Field.container.js
>          return output;
done

2022-03-15 10:57 UTC, pablobentivengo commented on packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.component.js
> +import { getSubLabelFromMaxCharacters } from '../../util/Product/Extract';
done

2022-03-15 10:57 UTC, pablobentivengo commented on packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.component.js
> +import { getSubLabelFromMaxCharacters } from '../../util/Product/Extract';
done

2022-03-15 10:58 UTC, pablobentivengo commented on packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.container.js
> +
done

2022-03-15 10:58 UTC, pablobentivengo commented on packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.container.js
> +
done

2022-03-15 11:00 UTC, pablobentivengo commented on packages/scandipwa/src/util/Product/Extract.js
> +//#region SubLabel
done

2022-03-15 11:00 UTC, pablobentivengo commented on packages/scandipwa/src/util/Product/Extract.js
> +//#region SubLabel
done

2022-03-15 11:00 UTC, pablobentivengo commented on packages/scandipwa/src/util/Product/Extract.js
> +
done

2022-03-15 11:01 UTC, pablobentivengo commented on packages/scandipwa/src/util/Product/Extract.js
> +
done

2022-03-15 11:02 UTC, pablobentivengo commented on packages/scandipwa/src/component/Product/Product.container.js
> +            return true;
done

2022-03-15 11:02 UTC, pablobentivengo commented on packages/scandipwa/src/component/Product/Product.container.js
> +            return true;
done

2022-03-15 11:05 UTC, pablobentivengo commented on packages/scandipwa/src/component/Field/Field.container.js
> +        const maxValidLength = range ? range.max : 0;
But if validationRule doesn't have range defined how should I destruct? something like this?
`const {
            validationRule: { range: { max = 0 } = {} } = this.props;`

2022-03-15 11:09 UTC, pablobentivengo commented on packages/scandipwa/src/component/Field/Field.container.js
> +        if (response === true) {
Tested and it doesn't work

2022-03-15 11:09 UTC, pablobentivengo commented on packages/scandipwa/src/component/Field/Field.container.js
> +        if (response === true) {
Tested and it doesn't work

2022-03-15 11:13 UTC, pablobentivengo commented on packages/scandipwa/src/util/Validator/Validator.js
> +                const tooMany = value.length - max;
Hey! But tooMany is an Int.

2022-03-15 11:15 UTC, pablobentivengo commented on packages/scandipwa/src/store/Product/Product.reducer.js
> -
Hey, this file is as it was, I modified it to add an extra action but removed it and left it as is.

Before I applied that extra action it wasn't even exported in the index.js file of Stores folder. (So I removed it after the mods I made)

2022-03-15 18:13 UTC, AleksandrsKondratjevs reviewed
Resolve

2022-03-15 18:13 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/Field/Field.container.js
> +        const maxValidLength = range ? range.max : 0;
yeap

2022-03-16 13:40 UTC, merged