[4055] removed scrollbar styling attributes
scandipwa/scandipwa pull request #4280
Opened 2022-02-10 14:41 UTC by pablobentivengo

**Related issue(s):**
* Fixes #4055 

**Problem:**
* Small part of background visible from the left side of scroll

**In this PR:**
* Removed scrollbar styling

**Related PRs:**
* #4079

2022-02-10 15:03 UTC, pablobentivengo commented
**Not ready**

2022-02-14 08:18 UTC, aleksandrakorolova commented
Can reproduce with the bottom side of scrollbar
![Screenshot 2022-02-14 at 10 16 36](https://user-images.githubusercontent.com/73526235/153825850-d742a36e-7a27-455a-b7ca-2039b931c0a5.png)

2022-02-15 13:06 UTC, aleksandrakorolova commented
Decided to create separate task for this issue

2022-02-18 13:45 UTC, AleksandrsKondratjevs requested changes

2022-02-18 13:45 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
> +
not required line

2022-02-18 13:45 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
Same

2022-02-23 11:49 UTC, AleksandrsKondratjevs approved these changes

2022-02-23 15:20 UTC, merged