Issue 3751
scandipwa/scandipwa pull request #4289
Opened 2022-02-14 11:52 UTC by AleksandrsKondratjevs

**Related issue(s):**
* Fixes #3751 

**Problem:**
* [Describe the problem briefly]

**In this PR:**
* [Say what you changed]

2022-02-21 12:12 UTC, Elena-Evsa commented
1. Mobile: 'Print All Invoices' written without space before the top line - Same for order shipments
![image](https://user-images.githubusercontent.com/84388061/154950091-9523e664-9e57-4924-b4a0-a92af2145992.png)

2. IOS: only titles shown in 'Order information' block on Print page, empty space instead of data https://vimeo.com/679981669/8c76ba3566

2022-03-06 08:54 UTC, Elena-Evsa commented
1. Fixed
2. Fixed
3. Fixed

2022-03-09 06:50 UTC, riha112 requested changes

2022-03-09 06:50 UTC, riha112 commented on packages/scandipwa/src/component/MyAccountOrder/MyAccountOrder.config.js
> +import { } from 'Util/Url';
Can be removed.

2022-03-09 06:50 UTC, riha112 commented on packages/scandipwa/src/route/OrderPrintPage/OrderPrintPage.container.js
> +                <OrderPrintPage
Incorrect indent for `<OrderPrintPage...` _(Too many spaces)_

2022-03-30 07:55 UTC, riha112 approved these changes

2022-03-30 14:07 UTC, merged