Search hovering fixed
scandipwa/scandipwa pull request #4300
Opened 2022-02-16 15:01 UTC by tazo-dvalishvili

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4256

**Problem:**
* Hover effect is missing for product card in search overlay.

**In this PR:**
* Added hover effect for product card in search overlay.

2022-02-16 19:12 UTC, carinadues commented
Hey!
Can you make it so that this whole area marked would be gray?
![image](https://user-images.githubusercontent.com/82165392/154338399-f222bbc5-1d00-400e-bfc0-97615cba90ea.png)

2022-02-23 14:33 UTC, Elena-Evsa commented
1. Issue about size of grey area - Failed
2. Placeholders and products moved to right
![image](https://user-images.githubusercontent.com/84388061/155340113-13981f07-e376-4aef-b840-75fecd5485ed.png)

Expected: https://vimeo.com/680900494/b0b6de249f

2022-03-01 21:07 UTC, AleksandrsKondratjevs approved these changes

2022-03-18 13:34 UTC, AleksandrsKondratjevs requested changes

2022-03-18 13:34 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/SearchItem/SearchItem.style.scss
> +    padding: 12px;
So you making padding left to be 20px and then overriding it to be 12px. 
I guess out here something wrong.

2022-03-24 17:19 UTC, AleksandrsKondratjevs approved these changes

2022-03-24 17:45 UTC, merged