#4295 added property margin-block-start to Quantity Control Buttons
scandipwa/scandipwa pull request #4305
Opened 2022-02-17 09:49 UTC by Mohamed-Ahmed711

**Related issue(s):**
* Fixes [https://github.com/scandipwa/scandipwa/issues/4295]

**Problem:**
* [Quantity control buttons for product option is shifted down for bundle product on PDP]

**In this PR:**
* [Added property margin-block-start to DropdownWrapper_customQuantity Field_type_number in ProductBundleOptions.style]

2022-02-17 21:08 UTC, carinadues commented
Hey!
Can you please set the size of the buttons as it was [here](https://5-0-0-rc.d25kd40decjpue.amplifyapp.com/default/baggini-dyn-with-special-price.html)? Currently, it is 44 instead of 48, so it doesn't look fully aligned. 

![image](https://user-images.githubusercontent.com/82165392/154570933-97771798-5a81-4d71-9f6f-e55842fe00bb.png)

2022-02-18 12:51 UTC, AleksandrsKondratjevs requested changes

2022-02-18 12:51 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductBundleOptions/ProductBundleOptions.style.scss
> +                        margin-block-start: 0px;
just 0

2022-02-18 12:51 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductBundleOptions/ProductBundleOptions.style.scss
> +                        margin-block-start: 0px;
Same as if u just delete this property won't it base same result?

2022-02-22 09:47 UTC, AleksandrsKondratjevs approved these changes

2022-02-22 09:48 UTC, AleksandrsKondratjevs requested changes
Still need to put 0 instead of 0px

2022-02-22 10:40 UTC, AleksandrsKondratjevs approved these changes

2022-02-22 13:42 UTC, merged