#3802 Added Html Component inside the function getCheckboxLabel
scandipwa/scandipwa pull request #4322
Opened 2022-02-21 13:14 UTC by Mohamed-Ahmed711

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3802

**Problem:**
* Name of attributes of 'Images Type Map' shown in html format in Layered navigation on 40SKUDEMO

**In this PR:**
* Added a Html Component inside the function getCheckboxLabel in ProductAttributeValue.component

2022-03-11 08:23 UTC, aleksandrakorolova commented
1. Please, do image size the same as visual swatch (38x38)
3. Name of attributes is displayed in html format if user selected filter
![Screenshot 2022-03-11 at 10 00 37](https://user-images.githubusercontent.com/73526235/157828571-8dd1ec32-6077-44ed-96df-02c4f50094ac.png)
4. Name of attributes is displayed in html format on PDP
![Screenshot 2022-03-11 at 10 04 01](https://user-images.githubusercontent.com/73526235/157828783-6e03541c-78a5-4c89-b36f-efefecba9fd0.png)
5. Image isn't displayed in Compare list
![Screenshot 2022-03-11 at 10 16 39](https://user-images.githubusercontent.com/73526235/157829433-80bb1995-0bc5-4137-b3b4-49585f4cc89a.png)

2022-03-16 06:33 UTC, aleksandrakorolova commented
1. Sorry, I made mistake - color swatch is 32x32. Please, change it
Notes: And save proportion for image
2. Now Big image is displayed 
![Screenshot 2022-03-16 at 07 53 14](https://user-images.githubusercontent.com/73526235/158525437-eb83acf6-673d-4585-a197-8b0e24d71f7c.png)
3. Ooops page when opening PDP
Error message 'TypeError: First argument must be a string' appears in the console
![Screenshot 2022-03-16 at 07 53 56](https://user-images.githubusercontent.com/73526235/158525650-9d9284ff-cbd3-4847-92ed-f5eca1dd71f4.png)
4. Fixed
5. 'Image not found' is not aligned with other attributes values
![Screenshot 2022-03-16 at 08 02 23](https://user-images.githubusercontent.com/73526235/158527464-8abfd232-8937-49ef-81e0-3f41de704ab8.png)
6. Number is moved to next line 
![Screenshot 2022-03-16 at 08 32 08](https://user-images.githubusercontent.com/73526235/158530413-266306c5-1f1f-4726-be8a-a4124ecd59d6.png)

2022-03-17 18:51 UTC, Mohamed-Ahmed711 commented
Regarding part 6 It is aligned by removing the <div> tag in Magento as shown in the images below: 
![images_type_map - Product Attributes - Attributes - Stores - Magento Admin 2022-03-17 17-12-36](https://user-images.githubusercontent.com/99433797/158875001-e0418185-6598-4259-aecb-bc887d696b34.png)
![Equipment 2022-03-17 17-14-01](https://user-images.githubusercontent.com/99433797/158875032-0546119d-c8ed-469c-82f6-7190014f1801.png)

2022-03-18 09:39 UTC, aleksandrakorolova commented
1.Please, save proportion for image (the largest side of image should be 32px but the shortest side of image is proportionately reduced)
2.1 Attribute name and X are not aligned 
![Screenshot 2022-03-18 at 10 13 39](https://user-images.githubusercontent.com/73526235/158964939-d3a7b083-0719-4faa-a0fb-e5a6e526ad25.png)
2.2. 'Image not found' is moved to the next line and overlaps to Attribute name
![Screenshot 2022-03-18 at 10 40 15](https://user-images.githubusercontent.com/73526235/158966066-cc64e7ad-b19e-4544-9598-1a802d13602e.png)
2.3 Image is moved to the next line
![Screenshot 2022-03-18 at 11 12 37](https://user-images.githubusercontent.com/73526235/158974353-44abdf85-55f5-491b-8e87-c471e67481fe.png)
3.Fixed
5.Still, can reproduce 
6.Ok
7.Ooops page when selecting price filter or boolean attribute
Error message 'TypeError: First argument must be a string' appears in the console
![Screenshot 2022-03-18 at 10 46 14](https://user-images.githubusercontent.com/73526235/158966874-77723f35-7b83-4793-b3a1-4629d2905848.png)
8. Please, return previous size of images in compare list. Now it's small
![Screenshot 2022-03-18 at 10 28 21](https://user-images.githubusercontent.com/73526235/158967015-98110a68-b2ad-48a6-920a-39d9c2c6d391.png)
9. Number should be center-aligned according to image
![Screenshot 2022-03-18 at 11 37 13](https://user-images.githubusercontent.com/73526235/158978454-1c63f3c3-856d-497a-b14f-38b2e161ad47.png)

2022-03-22 06:15 UTC, aleksandrakorolova commented
1.Please, apply this for vertical images too - 'the largest side of image should be 32px but the shortest side of image is proportionately reduced'
![Screenshot 2022-03-22 at 07 48 12](https://user-images.githubusercontent.com/73526235/159416308-4f6ddcca-3633-4383-abea-8185b03b2057.png)
2.1.Fixed
2.2.Fixed
2.3.Fixed
5.Still, can reproduce
![Screenshot 2022-03-22 at 07 54 26](https://user-images.githubusercontent.com/73526235/159416937-8259fcb3-8df0-4f67-94ae-3742c9c6f9af.png)
7.Fixed
8.1.Image overlaps to other fields
![Screenshot 2022-03-22 at 07 53 31](https://user-images.githubusercontent.com/73526235/159417174-f99f0798-68ed-40ff-80ec-e9c1fa054732.png)

8.2.Please, save proportion for image in compare list
![Screenshot 2022-03-22 at 07 53 42](https://user-images.githubusercontent.com/73526235/159417165-53f9d7c2-eba4-45ce-a8db-e167f76b922d.png)
9.Indent between these two images (see in screenshot) less then between other 
![Screenshot 2022-03-22 at 08 10 45](https://user-images.githubusercontent.com/73526235/159419152-b6f730cf-c84a-4334-93c8-fd6080431017.png)

2022-03-28 05:14 UTC, aleksandrakorolova commented
1.Fixed
1.1 Fixed
5.Still, can reproduce
8.1 Fixed
8.2 Fixed
8.3.Please return previous sizes for images from the description and short description in compare list
**Actual result:**
![Screenshot 2022-03-28 at 08 05 39](https://user-images.githubusercontent.com/73526235/160329968-a409af73-b55c-4909-a6d7-e127a09f691d.png)
**Expected result:**
![Screenshot 2022-03-28 at 08 07 05](https://user-images.githubusercontent.com/73526235/160330004-22b9ad4f-af2b-444e-8787-80f9684de5d2.png)

2022-04-07 05:00 UTC, zans-laksa requested changes

2022-04-22 03:33 UTC, carinadues commented
The issue will be fixed in https://github.com/scandipwa/scandipwa/pull/4728

2022-04-22 03:33 UTC, closed without merging