[3446] added isSortSelect property and modified styling to show chevron icon on mobile
scandipwa/scandipwa pull request #4323
Opened 2022-02-21 13:48 UTC by pablobentivengo

**Related issue(s):**
* Fixes #3446 

**Problem:**
* Arrow near 'Sort' on PLP is missing on mobile

**In this PR:**
* Added isSortSelect prop to Field and FieldSelect
* FieldSelect component conditionally renders "sort" if isSortSelect
* Modified CategorySelect styling to show chevron (arrow) on mobile

2022-02-22 09:26 UTC, aleksandrakorolova commented
1. Arrow is shifter up on iOS but it's shifted slightly down on Android. Please, align the arrow ± in the center on both platforms
2. Inverted arrow is displayed when selecting sorting method
https://drive.google.com/file/d/10upE16Ncb3gdxoL3f8cJ0TlqwJ6n1ZzH/view?usp=sharing

2022-02-22 10:11 UTC, pablobentivengo commented
Not ready

2022-02-23 10:27 UTC, pablobentivengo commented
2) With @Elena-Evsa and @carinadues we agreed to create a new issue for the arrow not changing direction properly on mobile devices, since this issue is present in all dropdowns. The issue is generated because of the way the dropdown is rendered on mobile devices. Arrow only changes direction when opening dropdown.

_Tests done on PMREV_
- IOS
 https://vimeo.com/680814098/146639adee
- Android
 https://vimeo.com/680814806/99e34d1cc2

2022-02-24 07:59 UTC, aleksandrakorolova commented
1. Fixed
2. Ok
3. Please, change text 'Sort' to 'Sort by' and change font size to 16px as 'Filter'. Also, add margin 10px between text 'Sort by' and arrow as between Filter icon and 'Filter text'

2022-02-28 21:08 UTC, AleksandrsKondratjevs requested changes

2022-02-28 21:08 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CategorySort/CategorySort.style.scss
> +                        margin-inline-start: 0px;
Stay constantly. 0 goes without px

2022-02-28 21:08 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CategorySort/CategorySort.style.scss
> +                margin-block-start: 3px;
first properties, then new selectors

2022-02-28 21:08 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/FieldSelect/FieldSelect.component.js
>      };
So isn't always passed from field component? It is most lucky always will be with default value.

2022-02-28 21:08 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/FieldSelect/FieldSelect.component.js
> +        return null;
Replace them

2022-03-01 09:32 UTC, pablobentivengo commented on packages/scandipwa/src/component/CategorySort/CategorySort.style.scss
> +                margin-block-start: 3px;
done

2022-03-01 09:32 UTC, pablobentivengo commented on packages/scandipwa/src/component/CategorySort/CategorySort.style.scss
> +                        margin-inline-start: 0px;
done

2022-03-01 09:33 UTC, pablobentivengo commented on packages/scandipwa/src/component/FieldSelect/FieldSelect.container.js
> +        isSortSelect: false
done

2022-03-01 11:36 UTC, AleksandrsKondratjevs approved these changes

2022-03-01 16:03 UTC, merged