Fixed Price moved from first line to second line
scandipwa/scandipwa pull request #4363
Opened 2022-03-01 09:31 UTC by SalimMersally

**Related issue(s):**
* Fixes #4355 

**Problem:**
* Price moved from first line to second line with disabled option in dropdown

**In this PR:**
* Fixed price so it don't overlap with other lines when wrapping

2022-03-01 10:02 UTC, Elena-Evsa commented
1. Options are not aligned to placeholder in dropdown, options are moved right
![image](https://user-images.githubusercontent.com/84388061/156146745-f111596b-3e59-4c93-9de2-7014a5af9e47.png)

2022-03-04 08:33 UTC, AleksandrsKondratjevs requested changes

2022-03-04 08:33 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
> +        padding-block: 10px 10px;
Is it necessary to repeat 10px in this case? I guess writing 1 time 10px will be same result.

2022-03-04 08:33 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
> +        padding: 0px;
just 0

2022-03-09 10:23 UTC, AleksandrsKondratjevs approved these changes

2022-03-11 17:43 UTC, merged