[4338] initialized current address values, set input values to current values
scandipwa/scandipwa pull request #4377
Opened 2022-03-04 10:16 UTC by pablobentivengo

**Related issue(s):**
* Fixes #4338

**Problem:**
* Name of state saved for field without dropdown when user selected other country

**In this PR:**
* initialized current address values, set input values to current values

**Related PR(s):**
* #4359

2022-03-07 07:17 UTC, aleksandrakorolova commented
3. Fixed but Can we stay empty State field when selecting 'Select country'? Now dropdown with States is displayed 
![Screenshot 2022-03-07 at 09 16 16](https://user-images.githubusercontent.com/73526235/156985256-fcb4110b-be35-49f4-bf47-c02c168c501e.png)

2022-03-09 07:02 UTC, riha112 requested changes

2022-03-09 07:02 UTC, riha112 commented on packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.container.js
> +        if (!address.id) {
better use:
```js
const { address, address: { id: addressId } = {} } = this.props;

if (!addressId) {
   ....
}
```

2022-03-09 07:02 UTC, riha112 commented on packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.container.js
> +        const { region: { region, region_id: regionId }, postcode, city } = address;
add empty line before `const { ...`

2022-03-09 09:28 UTC, pablobentivengo commented on packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.container.js
> +        if (!address.id) {
Done

2022-03-09 09:28 UTC, pablobentivengo commented on packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.container.js
> +        const { region: { region, region_id: regionId }, postcode, city } = address;
Done

2022-03-09 09:53 UTC, riha112 approved these changes

2022-03-09 10:47 UTC, merged