Issue 4344
scandipwa/scandipwa pull request #4383
Opened 2022-03-04 14:47 UTC by Mohamed-Ahmed711

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4344

**Problem:**
* Opacity for selected by default product option is missing on PDP if this product is out of stock

**In this PR:**
* Fixed the Opacity for selected by default product option

2022-03-07 07:41 UTC, aleksandrakorolova commented
1. Opacity is applied for all selected product option. Don't matter if product is out of stock or not - https://drive.google.com/file/d/1ylIr9DvhAzx9piQ6-jGio-NKOmtMm05g/view?usp=sharing
2. Mobile: Red line is displayed above dropdown  
![Screenshot 2022-03-07 at 09 38 35](https://user-images.githubusercontent.com/73526235/156988181-9bd099d2-b6f9-4c03-a8de-a239aaabd08e.png)

3. Mobile: Can't open dropdown if there is at least one in stock product  - https://drive.google.com/file/d/1XjpNEQ9ClG574bk0WIm77N1n8OxW5Ype/view?usp=sharing

2022-03-11 09:49 UTC, aleksandrakorolova commented
4. Opacity - fixed
Error message - still, can reproduce

2022-03-11 23:04 UTC, carinadues commented
Decided with Mohamed and Alex that the 2nd part of issue 4 will be fixed separately. Here's the new issue: https://github.com/scandipwa/scandipwa/issues/4445

2022-03-13 21:53 UTC, AleksandrsKondratjevs requested changes

2022-03-13 21:53 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/FieldSelect/FieldSelect.container.js
> +    }
Shouldn't there some some kind of condition to not call it each time?

2022-03-15 11:30 UTC, AleksandrsKondratjevs requested changes

2022-03-15 17:36 UTC, merged