fixed padding bottom issue in older firefox and older edge
scandipwa/scandipwa pull request #4391
Opened 2022-03-07 12:22 UTC by florianf22

**Related issue(s):**
* [Fixes [link for issue]](https://github.com/scandipwa/scandipwa/issues/1657)

**Problem:**
* For older firefox and edge browsers, padding-bottom wasn't showing. According to this - https://stackoverflow.com/questions/48687129/padding-bottom-not-working-in-firefox-ie11 , I did use pseudo element to make it work.

**In this PR:**
* instead of, set padding on every side, but the bottom. then, in pseudo element, set padding-bottom

2022-03-09 10:23 UTC, AleksandrsKondratjevs requested changes

2022-03-09 10:23 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/Popup/Popup.style.scss
> +        padding: var(--popup-content-padding) var(--popup-content-padding) 0 var(--popup-content-padding);
just padding-block-end: 0;

2022-03-10 14:22 UTC, florianf22 commented on packages/scandipwa/src/component/Popup/Popup.style.scss
> +        padding: var(--popup-content-padding) var(--popup-content-padding) 0 var(--popup-content-padding);
done

2022-03-14 23:34 UTC, AleksandrsKondratjevs approved these changes

2022-03-15 11:30 UTC, merged