[4365] set name to lowercase and then capitalize with css
scandipwa/scandipwa pull request #4398
Opened 2022-03-08 09:24 UTC by pablobentivengo

**Related issue(s):**
* Fixes #4365

**Problem:**
* One of letters is written as capital letter in the middle of word in breadcrumbs in my account and compare list

**In this PR:**
* Set name to lowercase and then capitalize with css

2022-03-11 13:24 UTC, aleksandrakorolova commented
1. Breadcrumbs aren't written with capital letters on search result page if user entered word with Caps lock
![Screenshot 2022-03-11 at 15 01 24](https://user-images.githubusercontent.com/73526235/157871466-2f6c5ab4-5f2c-4def-8475-80d88a38cfdc.png)

2022-03-15 11:29 UTC, AleksandrsKondratjevs requested changes

2022-03-15 11:29 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/Breadcrumb/Breadcrumb.component.js
> +        const nameToString = name.toString();
Name is an object?

2022-03-15 11:37 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/Breadcrumb/Breadcrumb.component.js
> +        const nameToString = name.toString();
String(name)

2022-03-15 12:22 UTC, pablobentivengo commented on packages/scandipwa/src/component/Breadcrumb/Breadcrumb.component.js
> +        const nameToString = name.toString();
Done

2022-03-15 17:34 UTC, AleksandrsKondratjevs approved these changes

2022-03-15 17:34 UTC, merged