Fixed Excl. tax location so it won't overflow
scandipwa/scandipwa pull request #4412
Opened 2022-03-09 06:46 UTC by SalimMersally

**Related issue(s):**
* Fixes #4293 

**Problem:**
* [Price excl.tax is shifted left for shipping method if shipping method has long name

**In this PR:**
* FIxed Excl. tax postion so it won't overflow its container

2022-03-16 08:48 UTC, aleksandrakorolova commented
Issue fixed but Please, return price excl tax on the previous place if method name is not long 
![Screenshot 2022-03-16 at 10 44 31](https://user-images.githubusercontent.com/73526235/158551196-d570dd90-3657-4153-8ab8-f349f7763007.png)

2022-03-24 07:52 UTC, riha112 requested changes

2022-03-24 07:52 UTC, riha112 commented on packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.component.js
> +        if (this.rowRef.current && this.subPriceRef.current) {
This if block can be replaced with `updateState()` function call, as they do the same thing.

2022-03-24 07:52 UTC, riha112 commented on packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.component.js
> +            const SubPriceLeft = this.subPriceRef.current.getBoundingClientRect().left;
Reduce access chaining to something like:
```js
const { current: rowEl } = this.rowRef;
const { current: subPriceEl } = this.subPriceRef;

if (rowEl && subPriceEl) {
    const rowLeft = rowEl.getBoundingClientRect().left;
    const SubPriceLeft = subPriceEl.getBoundingClientRect().left;
    ...
```

2022-03-29 06:31 UTC, riha112 requested changes

2022-03-29 06:31 UTC, riha112 commented on packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.component.js
> +            const SubPriceLeft = this.subPriceRef.current.getBoundingClientRect().left;
rename `SubPriceLeft ` to `subPriceLeft`
change `this.subPriceRef.current.` to `subPriceEl.`

2022-03-30 07:07 UTC, riha112 approved these changes

2022-03-30 13:45 UTC, merged