fixed not found page error when redirected from the wishlist page
scandipwa/scandipwa pull request #4436
Opened 2022-03-10 12:29 UTC by florianf22

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4427

**Problem:**
* 404 page opened for a sec when adding product to cart from wishlist if product has required options

**In this PR:**
* I couldn't reproduce the issue, no matter what - tried incoginito, other browser's and so on. But the error was only caught in the dispatcher. Changed how the redirection if case of that error is treated (re-used the logic that will be executed configurableVariantIndex isn't found) - set the state first, did history.push();

2022-03-16 13:37 UTC, AleksandrsKondratjevs requested changes

2022-03-16 13:37 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/WishlistItem/WishlistItem.container.js
> +            history.push({ pathname: appendWithStoreCode(item.url) });
Please destruct url from item object

2022-03-16 13:57 UTC, florianf22 commented on packages/scandipwa/src/component/WishlistItem/WishlistItem.container.js
> +            history.push({ pathname: appendWithStoreCode(item.url) });
done

2022-03-17 09:19 UTC, AleksandrsKondratjevs approved these changes

2022-03-17 09:19 UTC, merged