fixed + throwing an error when sent via graphql
scandipwa/scandipwa pull request #4447
Opened 2022-03-13 17:28 UTC by florianf22

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4255

**Problem:**
* When inputting the symbol '+' in the search, it would throw an error, a graphql one.

**In this PR:**
* Graphql treats the symbol '+' differently, most likely. To get a very similar results, modified a search term in the query class. Now, i'll replace all the '+' with '-' that graphql can handle (it'll have a very similar results)

2022-03-14 13:56 UTC, Elena-Evsa commented
Still can see the errors if user enter + in search query
![image](https://user-images.githubusercontent.com/84388061/158186906-80314801-32b9-4748-adb6-c8ae18ece23a.png)

2022-03-14 14:07 UTC, florianf22 commented
Hi, looks like not all the files had been pushed, check now, please

2022-03-14 14:39 UTC, Elena-Evsa commented
1. Sign + absent in header on mobile:
![image](https://user-images.githubusercontent.com/84388061/158195159-09135173-b872-457a-8bde-e59a91cc1f0c.png)

2022-03-16 08:18 UTC, AleksandrsKondratjevs commented
`Now, i'll replace all the '+' with '-' that graphql can handle (it'll have a very similar results)`
What means very similar results? We need same result, not similar. Won't elastic in this case search for `short-jeans-for-man` instead of `short jeans for man` ?

2022-03-16 12:00 UTC, florianf22 commented
Before I made any change, '+' was parsed anyway. Graphql doesn't want to get '+'. If you, for example search for 'short+jeans', it returns 107 results. if you do 'short jeans', again 107 results. 'short-jeans', again 107. I tried different approaches, this worked very well. I'm guessing these symbols are parsed on the server anyway, so that's why I decided to remove '+'

2022-03-21 07:08 UTC, AleksandrsKondratjevs approved these changes

2022-03-21 07:54 UTC, AleksandrsKondratjevs requested changes

2022-03-21 07:54 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/query/ProductList.query.js
> +                handler: (option) => option.replace(/\+/g, '-')
No, stay with +. Is something wrong on our side.

2022-03-22 09:38 UTC, aleksandrakorolova commented
1. Don't show 'true' or 'false' in the console 
![Screenshot 2022-03-22 at 08 48 57](https://user-images.githubusercontent.com/73526235/159423777-12b36285-2ad1-4149-8acd-faf18568d748.png)
2. '-' is searched instead '+'
![Screenshot 2022-03-22 at 09 05 08](https://user-images.githubusercontent.com/73526235/159426187-639bc6da-30c2-45a3-af3a-00b872408305.png)

2022-03-25 15:49 UTC, florianf22 commented
@AleksandrsKondratjevs Please check this. As I said, "+" will only be changed if search terms contains only and only "+" (it'll be changed with "-" and no results will be returned). I couldn't find anything related to why + might throw an error if any other symbol don't.

2022-03-28 09:55 UTC, aleksandrakorolova commented
1. Fixed
2. Didn't fix

2022-05-02 12:18 UTC, leonazava commented
This is a backend issue. This PR can be closed, I've linked a nw PR that tackles backend modules

2022-05-03 00:52 UTC, closed without merging