[4437] - 'Same shipping and billing addresses' checkbox is no longer checked if user has different default billing address
scandipwa/scandipwa pull request #4462
Opened 2022-03-15 13:12 UTC by EriSilver

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4437

**Problem:**
* checkbox is checked only when the default shipping === default billing (customer data in the redux store), not accounting for changing the address (custom address or choosing another previously saved address (non-default)) in the checkout shipping step.

**In this PR:**
* In the checkout shipping file:
When selecting a previously saved address other than the default, the checkout reducer.shippingFields are updated.
* In the checkout billing file:
> New constants were created: newShippingStreet, newShippingId - (from the checkout reducer's shippingFields)
> -- newShippingId is:
> ----- undefined: if the default shipping address is used, and if custom shipping address
> ----- number: if a previously saved address was selected.
> 
> -- newShippingStreet is:
> ------ empty array : if default shipping
> ------ array of strings : otherwise
> 
> ----> the changes in isSameShippingAddress -> function returns true if:
> -- no custom address ( undefined newShippingId && newShippingStreet.length === 0) and default_billing === default_shipping
> or 
> -- the previously saved address is the same as the default billing (comparing IDs)

2022-03-17 09:28 UTC, aleksandrakorolova commented
Checkbox 'My billing and shipping are the same' should be selected if quest or user without saved addresses places order
https://drive.google.com/file/d/1ttinF4saCALsPb4SUSrlXdCsigiz8d46/view?usp=sharing

2022-03-21 07:00 UTC, AleksandrsKondratjevs requested changes

2022-03-21 07:00 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.container.js
> +            || (default_billing && parseInt(default_billing, 10) === newShippingId)
Im confused, you parsing default_billing? It is string ? :0

2022-03-21 07:01 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CheckoutShipping/CheckoutShipping.container.js
> +                formattedFields.street.length > 0
you need to destruct street.

2022-03-24 17:18 UTC, AleksandrsKondratjevs approved these changes

2022-03-24 17:57 UTC, merged