#4361 - fixed user not be redirected to shipping step when logging in billing
scandipwa/scandipwa pull request #4467
Opened 2022-03-15 14:38 UTC by florianf22

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4361

**Problem:**
* if someone, not yet logged in, goes through shipping and then logs in on the billing step, he/she isn't redirected back to the shipping step so it's a bit of problem.

**In this PR:**
* Added logic so that when pathname includes checkout url, it redirects user back

2022-03-16 10:22 UTC, aleksandrakorolova commented
1. User stays on billing step if user logged in via sign in form in billing page
https://drive.google.com/file/d/1a9TGSNMEe1nqWZremjpGHZm-af7zoPd8/view?usp=sharing
2. User is redirected to the previous page if user logged in via sign in form in overlay 
https://drive.google.com/file/d/1SzZMyU7RVkWldTWpoibkOBWnsCCpfQRg/view?usp=sharing

2022-03-16 14:18 UTC, florianf22 commented
Fixed all that. if user logs in on billing step, he'll be redirected back to shipping step

2022-03-17 08:16 UTC, aleksandrakorolova commented
Still, can reproduce
https://drive.google.com/file/d/1FACPFasdcVbws-m9RFvgiGB7kevWohJD/view?usp=sharing

2022-03-18 15:30 UTC, florianf22 commented
Changed the redirection logic, all good now :-)

2022-03-21 06:48 UTC, aleksandrakorolova commented
1. Can't check because of 3. issue
2. Can't check because of 3. issue
3. Shipping step opens when user is buying only virtual products => user can't complete order
https://drive.google.com/file/d/1mzj1tx0im65MjF3T-IjNURGMQdN0XOQL/view?usp=sharing

2022-03-22 19:37 UTC, florianf22 commented
should go through all edge cases now

2022-03-23 06:11 UTC, aleksandrakorolova commented
1. Fixed
2. Fixed
3. Fixed
4. User is redirected to Shipping step after log in if user has **only** virtual products to the cart
https://drive.google.com/file/d/16CheE4qgRPvDVBAeBa27L_uvzs1GyAxf/view?usp=sharing

2022-03-24 05:49 UTC, aleksandrakorolova commented
1. Failed. The same situation if user logged in via overlay
https://drive.google.com/file/d/1ZZq9jC_HTqhpwF1WMNlf8Zafkewk0BjE/view?usp=sharing
2. Fixed
3. Fixed

2022-03-24 14:59 UTC, florianf22 commented
Could you check now, please?

2022-03-25 09:22 UTC, aleksandrakorolova commented
1. Fixed
5. User is redirected to cart if user logged in from /customer/account/login page or overlay but not on checkout
https://drive.google.com/file/d/1l4N1o5dNYQvAzGJ3ZLHo6LVhoSUWnJuk/view?usp=sharing

2022-03-25 16:56 UTC, florianf22 commented
It won't redirect user to cart once logged in from the main page

2022-03-28 09:29 UTC, AleksandrsKondratjevs requested changes

2022-03-28 09:29 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/Header/Header.container.js
> +        if (pathname.includes(BILLING_URL) && title === 'Sign in' && !is_virtual) {
Definitely should not really on title check, it can be translated and on other langue it will not be 'Sign in'.

2022-03-28 09:29 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/MyAccountSignIn/MyAccountSignIn.container.js
> +import { SHIPPING_URL } from '../../route/Checkout/Checkout.config';
Use alias

2022-03-28 11:39 UTC, florianf22 commented
All corrected now

2022-03-28 15:25 UTC, AleksandrsKondratjevs approved these changes

2022-03-28 15:47 UTC, merged