[4445] set deafult option if its available
scandipwa/scandipwa pull request #4476
Opened 2022-03-16 10:25 UTC by pablobentivengo

**Related issue(s):**
* Fixes #4445 

**Problem:**
* Error message 'Product is out of stock' appears when selecting an in-stock product if an out-of-stock product is selected by default in dropdown.

**In this PR:**
* Set default option only if its available

2022-03-17 11:20 UTC, aleksandrakorolova commented
1. Ooops page when opening bundle product with radio buttons (For example, https://pr-4476.d25kd40decjpue.amplifyapp.com/default/bundle-e-reader-with-fixed-price.html)
Error message 'TypeError: Cannot read properties of null (reading 'isAvailable')' appears in the console 
![Screenshot 2022-03-17 at 13 06 23](https://user-images.githubusercontent.com/73526235/158797408-affebad9-3deb-45cf-8684-3ca8d780983e.png)

2022-03-21 07:55 UTC, AleksandrsKondratjevs requested changes

2022-03-24 08:01 UTC, AleksandrsKondratjevs requested changes

2022-03-24 08:01 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductBundleOption/ProductBundleOption.container.js
> +        const { isAvailable } = defaultOption || false;
No, just const { isAvailable  = false } = defaultOption || {};

2022-03-24 08:01 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductBundleOption/ProductBundleOption.container.js
> +        const { isAvailable } = defaultOption || false;
In this case if defaultOption undefined, it will be possible to descruct empty object and get isAvailable as false by default

2022-03-24 12:19 UTC, AleksandrsKondratjevs approved these changes

2022-03-24 13:16 UTC, merged