#4272 Mobile: Navigation bar doesn't disappear
scandipwa/scandipwa pull request #4479
Opened 2022-03-16 12:38 UTC by VanilStorm

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4272

**Problem:**
* Mobile: Navigation bar disappears for few sec and then appears again when adding product to cart

**In this PR:**
* Created an additional scroll check

2022-03-17 13:00 UTC, aleksandrakorolova commented
Still, can reproduce issue 
Notes: Navigation bar doesn't disappear when adding product to the cart to for the second time with condition: user didn't scroll page
https://drive.google.com/file/d/1YEvSzGUsk6_p_pYX0bfL5pjcfI6CDYtF/view?usp=sharing

2022-03-22 07:42 UTC, aleksandrakorolova commented
Still, can reproduce with steps:
1. Open PDP
2. Open Write new review form
3. Fill form
4. Submit
https://drive.google.com/file/d/1Ys_Lau9H2h-hOc5ZsWyLMH-ZIjcMfQaP/view?usp=sharing

2022-04-07 04:52 UTC, zans-laksa requested changes

2022-04-07 04:52 UTC, zans-laksa commented on packages/scandipwa/src/component/NavigationTabs/NavigationTabs.container.js
> +        isNotificationVisable: PropTypes.bool.isRequired
Please fix the typo.
Visible, not visable.

2022-04-07 04:52 UTC, zans-laksa commented on packages/scandipwa/src/component/NavigationTabs/NavigationTabs.container.js
> +        const { isScrolling } = this.state;
I believe the `isScrolling` is a misnomer here.
You don't check whether the page is scrolling here.
You just set the boolean flag here and exit the function if the flag is true.
Please put the proper name.

2022-04-29 09:14 UTC, aleksandrakorolova commented
Closed because issue was fixed in #4579

2022-04-29 09:14 UTC, closed without merging