[4000] Show Loader instead of Empty Cart on reorder
scandipwa/scandipwa pull request #4504
Opened 2022-03-18 11:34 UTC by leonazava

**Related issue(s):**
* [Fixes [link for issue]](https://github.com/scandipwa/scandipwa/issues/4000)

**Problem:**
* After pressing "Reorder", the cart displayed "Cart is empty" instead of a loader

**In this PR:**
* Changed the loader display condition from something that never happens (the "items" prop is always at least an empty array) 
* Added an extra variable to delegate the correct "if" condition between Loader and Empty Cart

2022-03-18 12:49 UTC, AleksandrsKondratjevs requested changes

2022-03-18 12:49 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/CartPage/CartPage.component.js
> +    initial = true;
Use component state

2022-03-18 13:59 UTC, AleksandrsKondratjevs requested changes

2022-03-22 09:56 UTC, aleksandrakorolova commented
Loader is added
1. Please, show previously added products in the cart + loader when adding products from order
https://drive.google.com/file/d/1WqfILa23Q18BA6jvUbE8JoiK8cs4C38p/view?usp=sharing
2. Loader is displayed not in the center of page if user didn't have products in the cart
![Screenshot 2022-03-22 at 11 52 22 (2)](https://user-images.githubusercontent.com/73526235/159454117-eab713aa-d83e-430f-946d-539afd850b9e.png)

2022-03-24 06:12 UTC, aleksandrakorolova commented
1. Fixed
2. Fixed
3. Mobile: User sees 2 loaders when doing reorder if cart was empty.
![Screenshot 2022-03-24 at 08 11 10](https://user-images.githubusercontent.com/73526235/159853448-7b63b6fb-76b5-489b-ae54-7dbade034d57.png)
4. Mobile: User doesn't see loader if user has a lot of products in the cart. Show loader within screen
![Screenshot 2022-03-24 at 08 10 55](https://user-images.githubusercontent.com/73526235/159853440-1d458484-4bc5-4388-a249-bd7bac95c334.png)

2022-03-25 06:31 UTC, aleksandrakorolova commented
2. Loader is displayed not in the center of page if user didn't have products in the cart
![Screenshot 2022-03-25 at 08 13 09 (2)](https://user-images.githubusercontent.com/73526235/160064872-8f1ef45c-927e-416f-8e45-39230b2ff794.png)
3. Fixed
4. Fixed
5. Loader is shifted down when doing reorder if cart was empty or refresh page
![Screenshot 2022-03-25 at 08 29 38](https://user-images.githubusercontent.com/73526235/160066767-80fb116d-9675-4c1a-bb7c-70727e3f97e0.png)
6. Two loaders are displayed when doing reorder and user already has 1-2 products in the card
![Screenshot 2022-03-25 at 08 29 49](https://user-images.githubusercontent.com/73526235/160066780-88baa689-acf5-4556-814d-c37ebfbf7640.png)

2022-03-25 07:56 UTC, leonazava commented
Couldn't replicate 5 and 6, but I expect this new commit should patch them as well.

2022-03-25 13:18 UTC, closed without merging