#4475 added max-height for expanded state of dropdown
scandipwa/scandipwa pull request #4509
Opened 2022-03-18 15:51 UTC by AzizKHAN030

**Related issue(s):**
* Fixes [#4475]

**Problem:**
* Dropdown select didn't have max-height so it didn't scroll

**In this PR:**
* added max-height 300px

2022-03-21 12:31 UTC, aleksandrakorolova commented
1. Now height of dropdown is 300px. Add scroll bar if dropdown have 4+ options (It will be about 200px)
![Screenshot 2022-03-21 at 14 27 57](https://user-images.githubusercontent.com/73526235/159260919-eab1fb99-fd6e-49ba-9188-bb3e241f1dda.png)

2022-03-22 09:13 UTC, AzizKHAN030 commented
Access this pull request here: https://pr-4509.d25kd40decjpue.amplifyapp.com/

2022-03-22 12:11 UTC, aleksandrakorolova commented
2. The last option is partially showing in currency switcher
![Screenshot 2022-03-22 at 13 54 32](https://user-images.githubusercontent.com/73526235/159477650-c93d9252-5376-492e-b1ab-324576534b35.png)

2022-03-23 12:19 UTC, riha112 approved these changes

2022-03-23 12:19 UTC, AleksandrsKondratjevs requested changes

2022-03-23 12:19 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
> +                max-height: $select-option-height * 5;
wrap with a calc

2022-03-23 14:16 UTC, AleksandrsKondratjevs approved these changes

2022-03-23 14:28 UTC, merged