[4375] Missing Product Filter Placeholder Fix
scandipwa/scandipwa pull request #4520
Opened 2022-03-21 11:05 UTC by leonazava

**Related issue(s):**
* Fixes #4375

**Problem:**
* The placeholder for the product filter wasn't visible on a first load

**In this PR:**
* Fixed the issue with one CSS line to give the placeholder a visible background

2022-03-24 06:28 UTC, aleksandrakorolova commented
1. Placeholders is good
2. 'Shopping Options' wasn't added
**Actual result:**
![Screenshot 2022-03-24 at 08 15 59](https://user-images.githubusercontent.com/73526235/159855272-c7cd43ae-3432-462c-8af4-f0cccc46c518.png)
**Expected result:**
Add 'Shopping Options' text and it should align with placeholder for category name
![Screenshot 2022-03-24 at 08 27 38](https://user-images.githubusercontent.com/73526235/159855694-b95159be-044c-4b4a-8a1f-77a081fbec7c.png)

2022-03-25 06:43 UTC, aleksandrakorolova commented
2. 'Shopping Options' was added but it's not aligned with placeholder for category name (on the left side of screenshot - when user is opening PLP in the first time, the right side - the second time). Please, align 'Shopping Options' text with placeholder for category name as on the right side of screenshot)
![Screenshot 2022-03-25 at 08 37 27](https://user-images.githubusercontent.com/73526235/160068004-77778bc5-67a7-457f-a5fe-e1a32834f1b2.png)

2022-03-28 09:26 UTC, AleksandrsKondratjevs requested changes

2022-03-28 09:26 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/CategoryFilterOverlay/CategoryFilterOverlay.container.js
> +
Remove whitespace

2022-03-28 09:26 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductConfigurableAttributes/ProductConfigurableAttributes.component.js
> +        renderPlaceholder: PropTypes.func,
Remove disabling eslint

2022-03-28 09:26 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductConfigurableAttributes/ProductConfigurableAttributes.container.js
> +        renderPlaceholder: PropTypes.func,
Same here

2022-03-28 09:26 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js
> +                    </div>
I assume you can refactore this to avoid eslint disabling.

2022-03-28 15:26 UTC, AleksandrsKondratjevs approved these changes

2022-03-28 15:47 UTC, merged