fixed loading state in overlay sign in form, removed overlay's Loader…
scandipwa/scandipwa pull request #4539
Opened 2022-03-23 07:53 UTC by AzizKHAN030

… component

**Related issue(s):**
* Fixes #4505 

**Problem:**
* Missing Loader for sign in for in checkout page and finally loader being displayed in the sign-in overlay in the main page

**In this PR:**
* Removed Overlay's Loader because now sign-in component has itself

2022-03-23 08:34 UTC, aleksandrakorolova commented
1. Two loaders are displayed on /customer/account/login page when logging in
![Screenshot 2022-03-23 at 10 31 44 (2)](https://user-images.githubusercontent.com/73526235/159656592-6e284ee4-700d-47a5-a777-4101fd18e2dd.png)

2022-03-23 12:20 UTC, AleksandrsKondratjevs requested changes

2022-03-23 12:20 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.component.js
> +              isLoading={ false }
What is the point in this case? Should it be always false? Maybe then add default prop to MyAccountSignIn if it is not passed, then be false?

2022-03-24 07:05 UTC, AzizKHAN030 commented
Access this pull request here: https://pr-4539.d25kd40decjpue.amplifyapp.com/

Seems like amplify stuck on sending comment but actually built

2022-03-24 11:15 UTC, AleksandrsKondratjevs approved these changes

2022-03-24 11:16 UTC, merged