#3530 Added wishlist check
scandipwa/scandipwa pull request #4549
Opened 2022-03-23 16:02 UTC by VanilStorm

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3530

**Problem:**
* Mobile: Share button is active in Wishlist

**In this PR:**
* Added wishlist check

2022-03-24 17:21 UTC, AleksandrsKondratjevs requested changes

2022-03-24 17:21 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/Header/Header.component.js
> +        const wishListQty = Number(title.split(' ').filter((item) => Number(+item)));
Well, you definitely could find wishlist qty another way.

2022-03-28 09:19 UTC, AleksandrsKondratjevs requested changes

2022-03-28 09:19 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/Header/Header.component.js
> +        if (!wishListQty) {
perhaps there is no point to create variable for 1 time use in if block condition.

2022-03-28 09:19 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/Header/Header.component.js
> +        productsInWishlist: PropTypes.objectOf(PropTypes.number),
I assume those Proptypes are not correct.  All types in object are numbers ? :/

2022-03-28 09:23 UTC, AleksandrsKondratjevs requested changes

2022-03-28 09:23 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/Header/Header.component.js
> +        productsInWishlist: PropTypes.objectOf(PropTypes.number),
Recheck propTypes, I assume they are not numbers. It is array ob products objects.

2022-03-28 11:17 UTC, VanilStorm commented on packages/scandipwa/src/component/Header/Header.component.js
> +        productsInWishlist: PropTypes.objectOf(PropTypes.number),
actually, productsInWishlist is an object that stores other product objects, the key of which is a number
<img width="609" alt="Снимок экрана 2022-03-28 в 14 17 28" src="https://user-images.githubusercontent.com/77737846/160386956-9f736d0d-8238-4f1e-a3c7-d2f6a7bbdcf8.png">
.

2022-03-28 15:27 UTC, AleksandrsKondratjevs requested changes

2022-03-28 15:27 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/Header/Header.component.js
> +        productsInWishlist: PropTypes.objectOf(PropTypes.object),
Object is deprecated proptype. Check proptypes in Types same as check where same state is get, maybe you can just reuse already made logic.

2022-03-29 19:21 UTC, VanilStorm commented
Closed this since it has reverted changes and it's easier to fix in a different branch.
See #4616

2022-03-29 19:21 UTC, closed without merging