[4364] - Background is no longer visible in dropdown lists
scandipwa/scandipwa pull request #4555
Opened 2022-03-24 09:08 UTC by EriSilver

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4364

**Problem:**
* Background is visible in dropdown lists
Issue couldn't be produced directly. It's shown in this [comment](https://github.com/scandipwa/scandipwa/issues/4364#issuecomment-1075339302) with pics 

**In this PR:**
* Wrapped the list items with a div to which I specified max-height and auto overflow
* Changed the parent's overflow to auto
By this, I made dropdown lists support any number of options + no visible background.

2022-03-24 12:29 UTC, aleksandrakorolova commented
1. Safari: Dropdown closes not smooth + options overlap to other options and link 'notify...'  when closing dropdown
https://drive.google.com/file/d/10hbvSA-Hv7fAO_DO40kh3GKZxxQFbdI5/view?usp=sharing

2022-03-28 08:05 UTC, aleksandrakorolova commented
1. Fixed
2. Safari: Dropdowns opens gradually (Line below dropdown appears -> dropdown opens)
https://drive.google.com/file/d/1wFrTnVxxtIsdq7Eida_M3kQ0TCnCyGBS/view?usp=sharing

2022-03-29 21:33 UTC, zans-laksa requested changes

2022-03-29 21:33 UTC, zans-laksa commented on packages/scandipwa/src/component/FieldSelect/FieldSelect.component.js
> +                  elem="Options-ulDiv"
Please find a better name. Don't use hyphens for element names. Since hyphens are the BEM dividers in our project.

2022-03-30 09:12 UTC, zans-laksa approved these changes

2022-03-30 13:43 UTC, merged