#4556 Loaderis absent on PLP after refresh of page
scandipwa/scandipwa pull request #4563
Opened 2022-03-24 12:17 UTC by VanilStorm

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4556

**Problem:**
* Mobile: Loader is shown on PLP after refresh of page or some time after of click on category in menu

**In this PR:**
* Deleted loaders, left only placeholders

2022-03-28 15:47 UTC, zans-laksa approved these changes

2022-03-29 08:04 UTC, zans-laksa commented
Please fix eslint warnings!

2022-03-29 17:22 UTC, carinadues requested changes
Will need changes

2022-03-29 18:22 UTC, zans-laksa commented
Closed this since it has reverted changes and it's easier to fix in a different branch.
See #4615

2022-03-29 18:22 UTC, closed without merging