Fixed mobile hover state
scandipwa/scandipwa pull request #4565
Opened 2022-03-24 14:07 UTC by SalimMersally

**Related issue(s):**
* Fixes #4522 

**Problem:**
* Hover state stay after tapping on mobile view

**In this PR:**
* Fix hover state

2022-03-25 07:37 UTC, aleksandrakorolova commented
1. Android: can reproduce 
https://drive.google.com/file/d/1YuMX0SU1kFjvVcEU92OfNKjevBudZ0ZF/view?usp=sharing
2. iOS: + and - stay hovereвю Also, reorder button
https://drive.google.com/file/d/1crHlC4nfGmLv1gA2kpdiGKudP-8dTJkr/view?usp=sharing
3. Don't show hover effect for 'notify...' and samples links in mobile view

2022-03-28 06:03 UTC, aleksandrakorolova commented
1. Fixed
2. Still, hover effect stays for Reorder and Subscribe to Order status on Order page

2022-03-29 20:02 UTC, zans-laksa requested changes

2022-03-29 20:02 UTC, zans-laksa commented on packages/scandipwa/src/component/MyAccountOrder/MyAccountOrder.style.scss
> +            @media (hover: hover) and (pointer: fine) {
This is a beautiful solution, but too complex to memorize.
Please make a helper mixin for it and replace all occurrences with the new mixin.
As an example, you can see `@desktop` or `@mobile` mixins.

2022-03-30 09:10 UTC, zans-laksa requested changes

2022-03-30 09:10 UTC, zans-laksa commented on packages/scandipwa/src/component/ProductActions/ProductActions.style.scss
> +
Please remove trailing spaces.

2022-03-30 09:10 UTC, zans-laksa commented on packages/scandipwa/src/style/abstract/_media.scss
> +@mixin hovarable {
Please replace hovarable with hoverable.

2022-03-30 09:10 UTC, zans-laksa commented on packages/scandipwa/src/style/base/_input.scss
> +        }
Please remove trailing spaces.

2022-03-30 10:15 UTC, zans-laksa approved these changes

2022-03-30 13:43 UTC, merged