#4261 - fixed text overflowing on second line on small devices #4523
scandipwa/scandipwa pull request #4570
Opened 2022-03-25 11:10 UTC by florianf22

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4261

**Problem:**
* The problem was that when going on small devices, terms and conditions text were stretching on two lines and so did the '-' symbol.

**In this PR:**
* used screen variable to render corresponding layout. this PR had already been opened here - https://github.com/scandipwa/scandipwa/pull/4523 but because I deleted branch and re-opened, it was deleted as well. Re-created now

2022-03-25 13:23 UTC, aleksandrakorolova commented
Please, merge master in this PR

2022-03-25 17:32 UTC, florianf22 commented
What do you mean merge master?

2022-03-28 06:49 UTC, aleksandrakorolova commented
I mean - Merge branch 'master' into issue as you did [here](https://github.com/scandipwa/scandipwa/pull/4447)

2022-03-29 10:45 UTC, aleksandrakorolova commented
Please, fix amplify
![Screenshot 2022-03-29 at 13 32 40](https://user-images.githubusercontent.com/73526235/160592808-026ad9a3-c640-4c93-bee7-ef79eab12fd0.png)

2022-03-29 10:55 UTC, florianf22 commented
link fixed

2022-03-30 05:08 UTC, aleksandrakorolova commented
No, Link isn't fixed 
![Screenshot 2022-03-30 at 08 08 21](https://user-images.githubusercontent.com/73526235/160755530-d587cdb6-9f40-49ad-8b11-1dd4288c9f8f.png)

2022-03-30 08:55 UTC, aleksandrakorolova commented
```
                                 # Starting phase: preBuild
                                 # Executing command: nvm install 14
2022-03-29T10:56:26.321Z [INFO]: Downloading and installing node v14.19.1...
2022-03-29T10:56:26.404Z [WARNING]: Downloading https://nodejs.org/dist/v14.19.1/node-v14.19.1-linux-x64.tar.gz...
2022-03-29T10:56:26.522Z [WARNING]: ##################################                                        47.8%
2022-03-29T10:56:26.578Z [WARNING]: ################################################
2022-03-29T10:56:26.578Z [WARNING]: ######################## 100.0%
2022-03-29T10:56:26.594Z [WARNING]: Computing checksum with sha256sum
2022-03-29T10:56:26.682Z [WARNING]: Checksums matched!
2022-03-29T10:56:27.716Z [INFO]: Now using node v14.19.1 (npm v6.14.16)
2022-03-29T10:56:27.746Z [INFO]: Installing default global packages from /root/.nvm/default-packages...
2022-03-29T10:56:27.746Z [INFO]: npm install -g --quiet yarn@1.22.0
2022-03-29T10:56:29.082Z [INFO]: /root/.nvm/versions/node/v14.19.1/bin/yarn -> /root/.nvm/versions/node/v14.19.1/lib/node_modules/yarn/bin/yarn.js
2022-03-29T10:56:29.084Z [INFO]: /root/.nvm/versions/node/v14.19.1/bin/yarnpkg -> /root/.nvm/versions/node/v14.19.1/lib/node_modules/yarn/bin/yarn.js
2022-03-29T10:56:29.085Z [INFO]: + yarn@1.22.0
                                 added 1 package in 1.014s
2022-03-29T10:56:29.128Z [INFO]: # Executing command: nvm use 14
2022-03-29T10:56:29.366Z [INFO]: Now using node v14.19.1 (npm v6.14.16)
2022-03-29T10:56:29.367Z [INFO]: # Executing command: yarn install
2022-03-29T10:56:29.763Z [INFO]: yarn install v1.18.0
2022-03-29T10:56:29.896Z [INFO]: [1/4] Resolving packages...
2022-03-29T10:56:30.750Z [INFO]: [2/4] Fetching packages...
2022-03-29T10:56:55.747Z [WARNING]: warning scandipwa-development-toolkit-vscode@1.0.25: The engine "vscode" appears to be invalid.
2022-03-29T10:56:55.749Z [INFO]: info fsevents@2.1.3: The platform "linux" is incompatible with this module.
2022-03-29T10:56:55.750Z [INFO]: info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-03-29T10:56:55.750Z [INFO]: info fsevents@2.3.2: The platform "linux" is incompatible with this module.
                                 info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-03-29T10:56:55.754Z [INFO]: info fsevents@1.2.13: The platform "linux" is incompatible with this module.
2022-03-29T10:56:55.755Z [INFO]: info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-03-29T10:56:55.761Z [INFO]: [3/4] Linking dependencies...
2022-03-29T10:56:55.765Z [WARNING]: warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.4" has unmet peer dependency "@octokit/core@>=3".
2022-03-29T10:56:55.766Z [WARNING]: warning " > @scandipwa/router@0.0.8" has incorrect peer dependency "@scandipwa/framework@^0.0.1".
2022-03-29T10:56:55.766Z [WARNING]: warning " > @scandipwa/scandipwa-scripts@2.4.19" has unmet peer dependency "@tilework/mosaic@0.1.4".
                                    warning " > @scandipwa/service-worker@0.0.17" has unmet peer dependency "@tilework/mosaic-craco@0.0.5".
2022-03-29T10:56:55.766Z [WARNING]: warning "workspace-aggregator-db2d53f9-fe8a-4079-a2a9-48053ed0fe57 > @scandipwa/router > react-router@5.2.1" has unmet peer dependency "react@>=15".
                                    warning "workspace-aggregator-db2d53f9-fe8a-4079-a2a9-48053ed0fe57 > @scandipwa/router > react-router-dom@5.3.0" has unmet peer dependency "react@>=15".
2022-03-29T10:56:55.767Z [WARNING]: warning "workspace-aggregator-db2d53f9-fe8a-4079-a2a9-48053ed0fe57 > @scandipwa/stylelint-config > stylelint-use-logical@1.1.0" has incorrect peer dependency "stylelint@^9.6.0".
2022-03-29T10:56:55.768Z [WARNING]: warning "workspace-aggregator-db2d53f9-fe8a-4079-a2a9-48053ed0fe57 > @scandipwa/stylelint-config > stylelint-webpack-plugin@3.1.0" has unmet peer dependency "webpack@^5.0.0".
2022-03-29T10:56:55.768Z [WARNING]: warning "workspace-aggregator-db2d53f9-fe8a-4079-a2a9-48053ed0fe57 > @scandipwa/scandipwa-development-toolkit-core > @typescript-eslint/eslint-plugin@2.34.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
2022-03-29T10:56:55.768Z [WARNING]: warning "workspace-aggregator-db2d53f9-fe8a-4079-a2a9-48053ed0fe57 > @scandipwa/scandipwa-development-toolkit-core > @typescript-eslint/parser@2.34.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
2022-03-29T10:56:55.768Z [WARNING]: warning "workspace-aggregator-db2d53f9-fe8a-4079-a2a9-48053ed0fe57 > @scandipwa/router > react-router > mini-create-react-context@0.4.1" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0".
2022-03-29T10:56:55.769Z [WARNING]: warning "workspace-aggregator-db2d53f9-fe8a-4079-a2a9-48053ed0fe57 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-config-injectors@0.1.17" has unmet peer dependency "@babel/core@^7.14.0".
2022-03-29T10:56:55.769Z [WARNING]: warning "workspace-aggregator-db2d53f9-fe8a-4079-a2a9-48053ed0fe57 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-craco@0.0.5" has incorrect peer dependency "react-scripts@4.0.1".
                                    warning "workspace-aggregator-db2d53f9-fe8a-4079-a2a9-48053ed0fe57 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > babel-jest@26.6.3" has unmet peer dependency "@babel/core@^7.0.0".
                                    warning "workspace-aggregator-db2d53f9-fe8a-4079-a2a9-48053ed0fe57 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > craco-sass-resources-loader@1.1.0" has unmet peer dependency "@craco/craco@^3.3.1".
2022-03-29T10:56:55.770Z [WARNING]: warning "workspace-aggregator-db2d53f9-fe8a-4079-a2a9-48053ed0fe57 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > craco-sass-resources-loader@1.1.0" has incorrect peer dependency "react-scripts@^2.1.3".
                                    warning "workspace-aggregator-db2d53f9-fe8a-4079-a2a9-48053ed0fe57 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > progress-bar-webpack-plugin@2.1.0" has unmet peer dependency "webpack@^1.3.0 || ^2 || ^3 || ^4 || ^5".
                                    warning "workspace-aggregator-db2d53f9-fe8a-4079-a2a9-48053ed0fe57 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > react-scripts@4.0.3" has unmet peer dependency "react@>= 16".
2022-03-29T10:56:55.770Z [WARNING]: warning "workspace-aggregator-db2d53f9-fe8a-4079-a2a9-48053ed0fe57 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-config-injectors > @babel/plugin-transform-arrow-functions@7.13.0" has unmet peer dependency "@babel/core@^7.0.0-0".
                                    warning "workspace-aggregator-db2d53f9-fe8a-4079-a2a9-48053ed0fe57 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-config-injectors > @babel/plugin-transform-async-to-generator@7.13.0" has unmet peer dependency "@babel/core@^7.0.0-0".
2022-03-29T10:56:55.770Z [WARNING]: warning "workspace-aggregator-db2d53f9-fe8a-4079-a2a9-48053ed0fe57 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-config-injectors > babel-loader@8.1.0" has unmet peer dependency "@babel/core@^7.0.0".
                                    warning "workspace-aggregator-db2d53f9-fe8a-4079-a2a9-48053ed0fe57 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-config-injectors > babel-loader@8.1.0" has unmet peer dependency "webpack@>=2".
                                    warning "workspace-aggregator-db2d53f9-fe8a-4079-a2a9-48053ed0fe57 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-test-utils > @testing-library/react@11.2.7" has unmet peer dependency "react-do [...]

2022-03-31 01:13 UTC, zans-laksa commented
It's not a cache issue.
The error log clearly says what is wrong.

![image](https://user-images.githubusercontent.com/73945186/160956330-28400d8c-d8ea-4aa3-aa8e-f9f26ad9831a.png)
![image](https://user-images.githubusercontent.com/73945186/160956406-34f6eaad-1077-45a1-be8f-2e88e4988bc8.png)

2022-03-31 13:17 UTC, florianf22 commented
I see, corrected spacing now

2022-03-31 15:31 UTC, zans-laksa requested changes

2022-03-31 15:31 UTC, zans-laksa commented on packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.style.scss
> +
Please remove this space too.

2022-04-01 12:32 UTC, florianf22 commented on packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.style.scss
> +
space has been removed

2022-04-01 12:33 UTC, florianf22 commented on packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.component.js
> +                  mods={ { isShifted: screen.width <= SCREEN_WIDTH_THRESHOLD } }
I can't use media queries. there are pre defined media queries for mobile, I didn't find custom media query in the codebase. However, I need to change something when it gets to the very small screen, that's why

2022-04-14 00:02 UTC, carinadues commented
@florianf22 There are more changes required. Can you please check?

2022-04-18 14:39 UTC, carinadues commented
The issue will be fixed in https://github.com/scandipwa/scandipwa/pull/4709

2022-04-18 14:39 UTC, closed without merging