added check for attributes if they have attribute_values
scandipwa/scandipwa pull request #4571
Opened 2022-03-25 11:37 UTC by AzizKHAN030

**Related issue(s):**
* Fixes #4506 

**Problem:**
* User didn't redirect from PLP if the visual_swatch or text attribute was inside PDP 

**In this PR:**
* Added check condition if there is value for attribute in PLP

2022-03-28 09:15 UTC, AleksandrsKondratjevs requested changes

2022-03-28 09:15 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductCard/ProductCard.component.js
> +            && Object.keys(super.getConfigurableAttributes()).length !== Object.keys(this.getConfigurableAttributes()).length) || (type === PRODUCT_TYPE.configurable && Object.values(this.getConfigur
move please next condition on next line.

2022-03-28 09:33 UTC, AzizKHAN030 commented on packages/scandipwa/src/component/ProductCard/ProductCard.component.js
> +            && Object.keys(super.getConfigurableAttributes()).length !== Object.keys(this.getConfigurableAttributes()).length) || (type === PRODUCT_TYPE.configurable && Object.values(this.getConfigur
Ready!

2022-03-28 15:28 UTC, AleksandrsKondratjevs requested changes

2022-03-28 15:28 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductCard/ProductCard.component.js
> +                    .some((value) => value.attribute_values.length === 0));
no need for pyramid :D

2022-03-30 08:58 UTC, AzizKHAN030 commented on packages/scandipwa/src/component/ProductCard/ProductCard.component.js
> +                    .some((value) => value.attribute_values.length === 0));
fixed

2022-03-30 12:00 UTC, merged