#4530 List/Grid icons and Sort by dropdown is shifted left on PLP
scandipwa/scandipwa pull request #4580
Opened 2022-03-27 14:43 UTC by VanilStorm

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4530

**Problem:**
* List/Grid icons and Sort by dropdown is shifted left on PLP

**In this PR:**
* Aligned all items and fixed mobile version

2022-03-28 06:43 UTC, aleksandrakorolova commented
Issues from #4554:
2. Still, it's not aligned. '{number} items found' is slightly shifted down
![download](https://user-images.githubusercontent.com/73526235/160337036-ec808fb8-e6b5-4077-be3d-118d89b850b5.png)
3. Fixed

2022-03-29 19:59 UTC, zans-laksa requested changes

2022-03-29 19:59 UTC, zans-laksa commented on packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js
> +
Please remove the empty line here.

2022-03-30 15:34 UTC, zans-laksa approved these changes

2022-03-30 17:45 UTC, merged