#4035 Minus and plus button disabled if product only 1 in stock
scandipwa/scandipwa pull request #4582
Opened 2022-03-28 07:07 UTC by VanilStorm

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4035

**Problem:**
* Minus button activated if product only 1 in stock available, and it is less than minimum salable quantity (= 2 items)

**In this PR:**
* Added checks to the minus and plus buttons

2022-03-29 09:51 UTC, Elena-Evsa commented
Please, read task carefully. "Expected result: Minus and plus button disabled if product only 1 in stock available and it is less than minimum salable quantity." Please, just block buttons + - in our case
https://vimeo.com/693462969/ec380bbbd1

2022-03-29 14:04 UTC, VanilStorm commented
> Please, read task carefully. "Expected result: Minus and plus button disabled if product only 1 in stock available and it is less than minimum salable quantity." Please, just block buttons + - in our case https://vimeo.com/693462969/ec380bbbd1

I did everything as it was written in the issue. The plus and minus buttons are disabled. The notification you get when you click the "add" button is another problem.

2022-03-29 21:44 UTC, zans-laksa requested changes

2022-03-29 21:44 UTC, zans-laksa commented on packages/scandipwa/src/component/FieldNumber/FieldNumber.component.js
> +                  disabled={ min === 1 + +value || +value === min || isDisabled }
Expressions are evaluated from left to right.
```javascript
1 + +value
```
So `1 + ?` will always try to cast `?` to number. You don't need to cast `value` again here.

2022-03-29 21:44 UTC, zans-laksa commented on packages/scandipwa/src/component/FieldNumber/FieldNumber.component.js
> +                  disabled={ min === 1 + +value || +value === min || isDisabled }
Actually if would be more readable if you cast the `value` to the number before you make add and comparison operations.

2022-03-30 09:13 UTC, zans-laksa approved these changes

2022-03-30 13:42 UTC, merged