Fixed product name not aligned with cross on IOS
scandipwa/scandipwa pull request #4600
Opened 2022-03-28 16:33 UTC by SalimMersally

**Related issue(s):**
* Fixes #4069 

**Problem:**
* Product name or stars is not aligned with the cross in Wishlist on mobile

**In this PR:**
* Fixed alignment

2022-03-29 06:45 UTC, aleksandrakorolova commented
1. iOS: Cross is slightly shifted up in two cases
![Screenshot 2022-03-29 at 09 36 58](https://user-images.githubusercontent.com/73526235/160549331-a3736e2d-9713-48f4-9715-54bdb78335ac.png)

2. Android: Cross is slightly shifted up if product has reviews
![Screenshot 2022-03-29 at 09 38 59](https://user-images.githubusercontent.com/73526235/160549342-ee6218b9-419d-43c8-b5a5-28cb66118e4c.png)

2022-03-29 21:55 UTC, zans-laksa requested changes

2022-03-29 21:55 UTC, zans-laksa commented on packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
> +            &_withReview[aria-label='Remove'] {
Is it necessary to raise the CSS selector specificity by putting the attribute with value?
If yes, please use the `mods` prop in order to add an additional, more specific, class name.

2022-03-29 21:55 UTC, zans-laksa commented on packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
> +            &_withReview[aria-label='Remove'] {
BTW, this will not work with other languages, since "Remove" is put to the translation function.
```javascript
aria-label={ __('Remove') }
```

2022-03-30 09:10 UTC, zans-laksa approved these changes

2022-03-30 13:41 UTC, merged