reduced margin top down to 5px from 24px
scandipwa/scandipwa pull request #4622
Opened 2022-03-30 05:47 UTC by AzizKHAN030

**Related issue(s):**
* Fixes #4610 

**Problem:**
* Unnecessary margin-top for ProductConfigurableAttributes block

**In this PR:**
* Reduced the margin down to 5px because on hover to the attribute, the border should be visible

2022-03-30 05:49 UTC, AzizKHAN030 commented
Didn't get rid of the margin completely because on hover to attribute the appeared border was partially hidden under top block
![image](https://user-images.githubusercontent.com/76899788/160760336-85df4f63-72f8-45b7-948b-75a8b06a89e5.png)

2022-03-31 15:53 UTC, zans-laksa requested changes

2022-03-31 15:53 UTC, zans-laksa commented on packages/scandipwa/i18n/da_DK.json
> +    "Maximum %s characters (%s too many)": null
Usually, when localization files are updated, they all are updated, not just the Danish one.

2022-03-31 16:30 UTC, closed without merging

2022-03-31 17:12 UTC, zans-laksa commented
If you fix something in another PR, please provide a link to this PR.

2022-03-31 17:14 UTC, AzizKHAN030 commented
This issue was fixed by another person, not in my PR