Fixed Addres book header not showing
scandipwa/scandipwa pull request #4629
Opened 2022-03-30 16:28 UTC by SalimMersally

**Related issue(s):**
* Fixes #4611 

**Problem:**
* Title 'Address book' is missing and button 'Add New Address' is shifted up in Address book in My Account when opening it via Manage Addresses link

**In this PR:**
* Fixed header not showing

2022-03-31 11:13 UTC, carinadues commented
Seems good. This is how it looks for me:
![image](https://user-images.githubusercontent.com/82165392/161042568-b52fe599-5ba4-4aaf-a0b7-edbd9ae35876.png)

2022-03-31 11:31 UTC, AleksandrsKondratjevs commented
Breaks orders. 
![image](https://user-images.githubusercontent.com/68007919/161045483-0f55fc08-73cd-439d-b08c-e44ea513787c.png)

2022-04-04 09:14 UTC, aleksandrakorolova commented
Still, can reproduce issue if user doesn't have default shipping/billing address and clicks on Go to "Address Book", to configure them!
![Screenshot 2022-04-04 at 12 12 19](https://user-images.githubusercontent.com/73526235/161512956-8122fd12-8d84-4767-918c-c11b3ef1c542.png)

2022-04-07 04:19 UTC, zans-laksa requested changes

2022-04-07 04:19 UTC, zans-laksa commented on packages/scandipwa/src/component/MyAccountAddressBook/MyAccountAddressBook.container.js
> +        changeTabName(tabName);
Please don't make such actions inside the constructor.
The purpose of the constructor in React components is to initialize values.
Please perform all changes inside the lifecycle methods.

2022-04-07 04:19 UTC, zans-laksa commented on packages/scandipwa/src/component/MyAccountDashboard/MyAccountDashboard.container.js
> -
Please put the empty line between the `return` statement and the rest of the code.

2022-04-07 12:42 UTC, zans-laksa approved these changes

2022-04-07 12:44 UTC, merged