4614 number inputs
scandipwa/scandipwa pull request #4631
Opened 2022-03-31 05:30 UTC by AzizKHAN030

**Related issue(s):**
* Fixes #4614 

**Problem:**
* Regular inputs with types 'number' and 'tel' were not supported

**In this PR:**
* Moved styles for custom FieldNumber with controls, added support for regular number and tel types, added check if FIELD_TYPE is undefined then should be rendered default field

Demo video for **QA** : [https://drive.google.com/file/d/1YzUZwm7omewxLxkGnuP99kBM5HDE3cxG/view?usp=sharing](url)

2022-03-31 05:35 UTC, AzizKHAN030 commented
For **QA**: Needs proper testing of quantity fields with controls

2022-03-31 08:13 UTC, aleksandrakorolova commented
Hey
Please, add input fields with input type ```number``` and ```tel``` on our /styleguide page but before it fix it. Now ooops page opens 
Error message 'TypeError: Cannot read properties of undefined (reading 'isAvailable')' appears in the console.
![Screenshot 2022-03-31 at 11 11 29](https://user-images.githubusercontent.com/73526235/161008692-1c6471b2-8032-46a0-9d7e-c2bd9afd9538.png)

2022-03-31 17:00 UTC, AzizKHAN030 commented
Seems like Amplify stuck, but the changes are applied

2022-03-31 17:11 UTC, zans-laksa approved these changes

2022-04-12 08:06 UTC, aleksandrakorolova commented
1. /styleguide page is **fixed**
2. Please, add all views for tel and number fields (enable and disabled fields, required and not required, validated and etc) as text/dropdown/checkbox/radio buttons
![Screenshot 2022-04-12 at 09 03 35](https://user-images.githubusercontent.com/73526235/162891552-a0214956-459d-41e1-8c3b-5e90a975136f.png)

2022-04-13 20:33 UTC, zans-laksa requested changes

2022-04-13 20:33 UTC, zans-laksa commented on packages/scandipwa/src/route/StyleGuidePage/StyleGuidePage.component.js
> +                      />
Please keep the same indents for the adjacent elements in the markup.

2022-04-13 20:33 UTC, zans-laksa commented on packages/scandipwa/src/route/StyleGuidePage/StyleGuidePage.component.js
> +
Please remove the empty line.

2022-04-13 20:33 UTC, zans-laksa commented on packages/scandipwa/src/route/StyleGuidePage/StyleGuidePage.component.js
> +                      />
Please fix indents here too.

2022-04-14 14:43 UTC, zans-laksa approved these changes

2022-04-18 15:14 UTC, zans-laksa approved these changes

2022-05-03 00:55 UTC, zans-laksa approved these changes

2022-05-03 01:09 UTC, merged