[4165] - transparent footer background on mobile
scandipwa/scandipwa pull request #4748
Opened 2022-05-02 10:28 UTC by leonazava

**Related issue(s):**
* Fixes scandipwa/scandipwa/issues/4165

**Problem:**
* On mobile devices without a physical home screen, the navbar would disappear and leave transparent space in it's place.

**In this PR:**
* Added the navbar's height to the action wrapper UI as whitespace to make up for the navbar disappearing
* Moved the ruleset defining that UI to _parts.scss so that it's reusable across the codebase

2022-05-03 01:03 UTC, zans-laksa approved these changes

2022-05-03 11:02 UTC, zans-laksa requested changes

2022-05-03 11:02 UTC, zans-laksa commented on packages/scandipwa/src/component/NavigationTabs/NavigationTabs.style.scss
> +    // transform: translateY(0);
Please don't leave comments in the code for no reason.

2022-05-03 13:15 UTC, zans-laksa approved these changes

2022-05-05 00:14 UTC, zans-laksa approved these changes

2022-05-05 08:54 UTC, Elena-Evsa commented
Passed on:
- PLP
- PDP
- Write a review
- Homepage and other CMS page (except About us)
- Cart
- Checkout
- My account pages
- Compare

Failed:
1. About us - menu does not appear if user scroll About us page https://drive.google.com/file/d/15z6Qd_P-EjixYneSV9RbNaXFpcVcPfuA/view?usp=sharing
2. Button in layered navigation is not hiding
3. Wishlist

2022-05-05 16:42 UTC, zans-laksa approved these changes

2022-05-10 08:40 UTC, leonazava commented
1. can't replicate
2. it didn't have the hiding behavior before. should it now?
3. fixed

2022-05-10 13:01 UTC, carinadues commented
Tested on iOS 15:

All "Passed" passed for me too
The two situations in the original issue are fixed

1. I can't replicate either. What version was it in the recording, @Elena-Evsa?
2. Let's keep it as it is
3. Fixed

2022-05-11 12:53 UTC, zans-laksa approved these changes

2022-05-11 13:04 UTC, merged