#4803 - added order total and subtotal fields to orders equal to 0
scandipwa/scandipwa pull request #4810
Opened 2022-05-20 14:24 UTC by MaritaKochua

**Related issue(s):**
* #4803 

**Problem:**
* Order total and subtotal were not appearing when the items total cost was 0. 

**In this PR:**
* Removed some conditionals and changed numbers to strings for order totals.

2022-05-20 14:38 UTC, zans-laksa approved these changes

2022-05-23 11:42 UTC, carinadues commented
Hey!
Please add `Excl. tax: €0.00` in the Order Total to the following:

Mini cart:
![image](https://user-images.githubusercontent.com/82165392/169810622-7fcc75b3-054f-4a5b-9a53-0200ae339a2e.png)

Cart summary:
![image](https://user-images.githubusercontent.com/82165392/169810681-54465c17-4a6e-449b-b3da-9407624006cf.png)

Shipping:
![image](https://user-images.githubusercontent.com/82165392/169810770-154ab675-89ef-498f-aff3-c374f0a99315.png)

Billing Step:
![image](https://user-images.githubusercontent.com/82165392/169811207-6c1e9d18-841f-45d3-a7ca-3fb9183196cf.png)

It should show if this setting is set to Yes:
![image](https://user-images.githubusercontent.com/82165392/169811732-b9d21710-7ef7-40f1-a3c1-06c4f9a8f244.png)

2022-05-24 23:32 UTC, zans-laksa requested changes

2022-05-24 23:32 UTC, zans-laksa commented on packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
> +                  price={ grand_total.toFixed(2) }
What if the `grand_total` is undefined?

2022-05-27 10:28 UTC, zans-laksa approved these changes

2022-05-31 15:54 UTC, carinadues commented
Hey, @MaritaKochua!

- https://github.com/scandipwa/scandipwa/issues/4796 - **Passed**
- https://github.com/scandipwa/scandipwa/issues/4803 - **Failed**:

 `Excl. tax: €0.00` is missing in the mini cart. Here's how it's on Luma:

![image](https://user-images.githubusercontent.com/82165392/171215117-6cbb56b2-ab03-497d-b456-dab3ae0722a3.png)
Here's now: 

![image](https://user-images.githubusercontent.com/82165392/171215252-c11d9a30-c4e2-4e01-b2e3-d2b15bca0af5.png)

Please add, to be like here:

![image](https://user-images.githubusercontent.com/82165392/171216838-e9768430-b4b8-4377-aba5-31bd6c9332f5.png)

2022-06-02 02:21 UTC, carinadues commented
Please add it here too (view previous comments for more pictures):

![image](https://user-images.githubusercontent.com/82165392/171535880-119c9069-3ca5-4737-aba0-afeb7cff09b3.png)

2022-06-06 23:07 UTC, zans-laksa approved these changes

2022-06-08 00:27 UTC, merged