#4812 adjusted form width when ratings are disabled
scandipwa/scandipwa pull request #4828
Opened 2022-05-25 08:28 UTC by MaritaKochua

**Related issue(s):**
* Fixes #4812 

**Problem:**
* Popup looked off when ratings were disabled.

**In this PR:**
* Made form spread 3 columns only when it's the first child, thus making it fill the entire popup.

2022-05-25 09:25 UTC, zans-laksa requested changes

2022-05-25 09:25 UTC, zans-laksa commented on packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.component.js
> +                ) }
Please move this one to the separate render method.

2022-05-26 08:55 UTC, zans-laksa approved these changes

2022-05-31 16:26 UTC, carinadues commented
Looking good! Let's just improve one more thing:

Please increase the top margin of the Submit Review button, to be the same spacing as we have now between the other fields.

![image](https://user-images.githubusercontent.com/82165392/171225155-7dd15c67-c7c7-4f94-a542-5354bc00d8e7.png)

2022-06-04 17:07 UTC, zans-laksa requested changes

2022-06-04 17:07 UTC, zans-laksa commented on packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.style.scss
> +
Please put properties before any nested block.

2022-06-06 23:03 UTC, zans-laksa approved these changes

2022-06-08 00:23 UTC, merged