#4813 removed stars when ratings are disabled
scandipwa/scandipwa pull request #4829
Opened 2022-05-25 10:22 UTC by MaritaKochua

**Related issue(s):**
* Fixes #4813 

**Problem:**
* Stars and percentages were displayed when ratings were disabled. 

**In this PR:**
* Removed stars and ratings when ratings are disabled.

2022-05-27 00:36 UTC, zans-laksa requested changes

2022-05-27 00:36 UTC, zans-laksa commented on packages/scandipwa/src/component/ProductReviews/ProductReviews.component.js
> +                    { reviewRatings.length > 0 && <span>{ percent }</span> }
Do you really need the empty `<span>` element here?

2022-05-27 00:36 UTC, zans-laksa commented on packages/scandipwa/src/component/ProductReviews/ProductReviews.component.js
> +                    { reviewRatings.length > 0 && <span>{ percent }</span> }
If you going to style it, please give the `span` the implicit class name (block-element-etc).

2022-05-27 00:36 UTC, zans-laksa commented on packages/scandipwa/src/component/ProductReviews/ProductReviews.style.scss
> +        span:nth-child(2) {
Please use class names as they are more implicit selectors.
If someone changes the layout, this may break but remain unnoticed.

2022-05-31 18:11 UTC, carinadues commented
Please remove the white space that is right before the number of reviews (1), making it left-aligned with the review box.

![image](https://user-images.githubusercontent.com/82165392/171255070-04440e15-df7e-422d-a0dd-ad237df51bff.png)

2022-06-06 23:06 UTC, zans-laksa approved these changes

2022-06-08 00:25 UTC, carinadues commented
Something's wrong:

![image](https://user-images.githubusercontent.com/82165392/172505797-2e6524fe-b42b-4fbe-83f0-1d847560ea71.png)

2022-07-12 11:45 UTC, aleksandrakorolova commented
```                                 # Starting phase: preBuild
                                 # Executing command: nvm install 14
2022-07-04T14:26:31.219Z [INFO]: Downloading and installing node v14.19.3...
2022-07-04T14:26:31.341Z [WARNING]: Downloading https://nodejs.org/dist/v14.19.3/node-v14.19.3-linux-x64.tar.gz...
2022-07-04T14:26:31.460Z [WARNING]: ####################
2022-07-04T14:26:31.461Z [WARNING]: 28.5%
2022-07-04T14:26:31.559Z [WARNING]: ###################################
2022-07-04T14:26:31.560Z [WARNING]: ##################################### 100.0%
2022-07-04T14:26:31.576Z [WARNING]: Computing checksum with sha256sum
2022-07-04T14:26:31.663Z [WARNING]: Checksums matched!
2022-07-04T14:26:32.739Z [INFO]: Now using node v14.19.3 (npm v6.14.17)
2022-07-04T14:26:32.770Z [INFO]: Installing default global packages from /root/.nvm/default-packages...
                                 npm install -g --quiet yarn@1.22.0
2022-07-04T14:26:34.950Z [INFO]: /root/.nvm/versions/node/v14.19.3/bin/yarn -> /root/.nvm/versions/node/v14.19.3/lib/node_modules/yarn/bin/yarn.js
2022-07-04T14:26:34.952Z [INFO]: /root/.nvm/versions/node/v14.19.3/bin/yarnpkg -> /root/.nvm/versions/node/v14.19.3/lib/node_modules/yarn/bin/yarn.js
2022-07-04T14:26:34.953Z [INFO]: + yarn@1.22.0
                                 added 1 package in 1.858s
2022-07-04T14:26:34.987Z [INFO]: # Executing command: nvm use 14
2022-07-04T14:26:35.225Z [INFO]: Now using node v14.19.3 (npm v6.14.17)
2022-07-04T14:26:35.225Z [INFO]: # Executing command: yarn install
2022-07-04T14:26:35.669Z [INFO]: yarn install v1.18.0
2022-07-04T14:26:35.801Z [INFO]: [1/4] Resolving packages...
2022-07-04T14:26:36.612Z [INFO]: [2/4] Fetching packages...
2022-07-04T14:27:02.510Z [WARNING]: warning scandipwa-development-toolkit-vscode@1.0.26: The engine "vscode" appears to be invalid.
2022-07-04T14:27:02.513Z [INFO]: info fsevents@2.1.3: The platform "linux" is incompatible with this module.
2022-07-04T14:27:02.513Z [INFO]: info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-07-04T14:27:02.513Z [INFO]: info fsevents@2.3.2: The platform "linux" is incompatible with this module.
                                 info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-07-04T14:27:02.518Z [INFO]: info fsevents@1.2.13: The platform "linux" is incompatible with this module.
2022-07-04T14:27:02.518Z [INFO]: info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-07-04T14:27:02.523Z [INFO]: [3/4] Linking dependencies...
2022-07-04T14:27:02.528Z [WARNING]: warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.4" has unmet peer dependency "@octokit/core@>=3".
2022-07-04T14:27:02.528Z [WARNING]: warning " > @scandipwa/router@0.0.8" has incorrect peer dependency "@scandipwa/framework@^0.0.1".
2022-07-04T14:27:02.529Z [WARNING]: warning " > @scandipwa/scandipwa-scripts@2.4.20" has unmet peer dependency "@tilework/mosaic@0.1.4".
                                    warning " > @scandipwa/service-worker@0.0.17" has unmet peer dependency "@tilework/mosaic-craco@0.0.5".
2022-07-04T14:27:02.529Z [WARNING]: warning "workspace-aggregator-5bf40fe5-038d-45f4-b56a-78314013eb86 > @scandipwa/router > react-router@5.2.1" has unmet peer dependency "react@>=15".
                                    warning "workspace-aggregator-5bf40fe5-038d-45f4-b56a-78314013eb86 > @scandipwa/router > react-router-dom@5.3.0" has unmet peer dependency "react@>=15".
2022-07-04T14:27:02.530Z [WARNING]: warning "workspace-aggregator-5bf40fe5-038d-45f4-b56a-78314013eb86 > @scandipwa/stylelint-config > stylelint-use-logical@1.1.0" has incorrect peer dependency "stylelint@^9.6.0".
2022-07-04T14:27:02.531Z [WARNING]: warning "workspace-aggregator-5bf40fe5-038d-45f4-b56a-78314013eb86 > @scandipwa/stylelint-config > stylelint-webpack-plugin@3.2.0" has unmet peer dependency "webpack@^5.0.0".
2022-07-04T14:27:02.531Z [WARNING]: warning "workspace-aggregator-5bf40fe5-038d-45f4-b56a-78314013eb86 > @scandipwa/scandipwa-development-toolkit-core > @typescript-eslint/eslint-plugin@2.34.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
2022-07-04T14:27:02.531Z [WARNING]: warning "workspace-aggregator-5bf40fe5-038d-45f4-b56a-78314013eb86 > @scandipwa/scandipwa-development-toolkit-core > @typescript-eslint/parser@2.34.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
                                    warning "workspace-aggregator-5bf40fe5-038d-45f4-b56a-78314013eb86 > @scandipwa/router > react-router > mini-create-react-context@0.4.1" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0".
2022-07-04T14:27:02.532Z [WARNING]: warning "workspace-aggregator-5bf40fe5-038d-45f4-b56a-78314013eb86 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-config-injectors@0.1.19" has unmet peer dependency "@babel/core@^7.14.0".
2022-07-04T14:27:02.532Z [WARNING]: warning "workspace-aggregator-5bf40fe5-038d-45f4-b56a-78314013eb86 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-craco@0.0.5" has incorrect peer dependency "react-scripts@4.0.1".
                                    warning "workspace-aggregator-5bf40fe5-038d-45f4-b56a-78314013eb86 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > babel-jest@26.6.3" has unmet peer dependency "@babel/core@^7.0.0".
                                    warning "workspace-aggregator-5bf40fe5-038d-45f4-b56a-78314013eb86 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > craco-sass-resources-loader@1.1.0" has unmet peer dependency "@craco/craco@^3.3.1".
2022-07-04T14:27:02.532Z [WARNING]: warning "workspace-aggregator-5bf40fe5-038d-45f4-b56a-78314013eb86 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > craco-sass-resources-loader@1.1.0" has incorrect peer dependency "react-scripts@^2.1.3".
                                    warning "workspace-aggregator-5bf40fe5-038d-45f4-b56a-78314013eb86 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > progress-bar-webpack-plugin@2.1.0" has unmet peer dependency "webpack@^1.3.0 || ^2 || ^3 || ^4 || ^5".
                                    warning "workspace-aggregator-5bf40fe5-038d-45f4-b56a-78314013eb86 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > react-scripts@4.0.3" has unmet peer dependency "react@>= 16".
2022-07-04T14:27:02.533Z [WARNING]: warning "workspace-aggregator-5bf40fe5-038d-45f4-b56a-78314013eb86 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-config-injectors > @babel/plugin-transform-arrow-functions@7.13.0" has unmet peer dependency "@babel/core@^7.0.0-0".
2022-07-04T14:27:02.533Z [WARNING]: warning "workspace-aggregator-5bf40fe5-038d-45f4-b56a-78314013eb86 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-config-injectors > @babel/plugin-transform-async-to-generator@7.13.0" has unmet peer dependency "@babel/core@^7.0.0-0".
                                    warning "workspace-aggregator-5bf40fe5-038d-45f4-b56a-78314013eb86 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-config-injectors > babel-loader@8.1.0" has unmet peer dependency "@babel/core@^7.0.0".
                                    warning "workspace-aggregator-5bf40fe5-038d-45f4-b56a-78314013eb86 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-config-injectors > babel-loader@8.1.0" has unmet peer dependency "webpack@>=2".
                                    warning "workspace-aggregator-5bf40fe5-038d-45f4-b56a-78314013eb86 > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-test-utils > @testing-library/react@11.2.7" has unmet peer dependency "react-dom@*".
2022-07-04T1 [...]

2022-07-13 10:33 UTC, aleksandrakorolova commented
Still, amplify is broken 
![Screenshot 2022-07-13 at 13 29 35](https://user-images.githubusercontent.com/73526235/178713274-c7308b4e-8fa6-4a7e-8349-db0d2105c30e.png)

```                                 # Starting phase: preBuild
                                 # Executing command: nvm install 14
2022-07-13T08:31:48.382Z [INFO]: Downloading and installing node v14.20.0...
2022-07-13T08:31:48.479Z [WARNING]: Downloading https://nodejs.org/dist/v14.20.0/node-v14.20.0-linux-x64.tar.gz...
2022-07-13T08:31:48.596Z [WARNING]: #############################
2022-07-13T08:31:48.596Z [WARNING]: #                                            42.9%
2022-07-13T08:31:48.665Z [WARNING]: ####################
2022-07-13T08:31:48.666Z [WARNING]: #################################################### 100.0%
2022-07-13T08:31:48.681Z [WARNING]: Computing checksum with sha256sum
2022-07-13T08:31:48.768Z [WARNING]: Checksums matched!
2022-07-13T08:31:49.868Z [INFO]: Now using node v14.20.0 (npm v6.14.17)
2022-07-13T08:31:49.897Z [INFO]: Installing default global packages from /root/.nvm/default-packages...
2022-07-13T08:31:49.897Z [INFO]: npm install -g --quiet yarn@1.22.0
2022-07-13T08:31:51.969Z [INFO]: /root/.nvm/versions/node/v14.20.0/bin/yarn -> /root/.nvm/versions/node/v14.20.0/lib/node_modules/yarn/bin/yarn.js
2022-07-13T08:31:51.972Z [INFO]: /root/.nvm/versions/node/v14.20.0/bin/yarnpkg -> /root/.nvm/versions/node/v14.20.0/lib/node_modules/yarn/bin/yarn.js
2022-07-13T08:31:51.973Z [INFO]: + yarn@1.22.0
                                 added 1 package in 1.753s
2022-07-13T08:31:52.002Z [INFO]: # Executing command: nvm use 14
2022-07-13T08:31:52.239Z [INFO]: Now using node v14.20.0 (npm v6.14.17)
2022-07-13T08:31:52.240Z [INFO]: # Executing command: yarn install
2022-07-13T08:31:52.662Z [INFO]: yarn install v1.18.0
2022-07-13T08:31:52.795Z [INFO]: [1/4] Resolving packages...
2022-07-13T08:31:53.570Z [INFO]: [2/4] Fetching packages...
2022-07-13T08:32:18.311Z [WARNING]: warning scandipwa-development-toolkit-vscode@1.0.27: The engine "vscode" appears to be invalid.
2022-07-13T08:32:18.314Z [INFO]: info fsevents@2.1.3: The platform "linux" is incompatible with this module.
2022-07-13T08:32:18.314Z [INFO]: info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-07-13T08:32:18.315Z [INFO]: info fsevents@2.3.2: The platform "linux" is incompatible with this module.
                                 info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-07-13T08:32:18.320Z [INFO]: info fsevents@1.2.13: The platform "linux" is incompatible with this module.
2022-07-13T08:32:18.320Z [INFO]: info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-07-13T08:32:18.326Z [INFO]: [3/4] Linking dependencies...
2022-07-13T08:32:18.331Z [WARNING]: warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.4" has unmet peer dependency "@octokit/core@>=3".
2022-07-13T08:32:18.332Z [WARNING]: warning " > @scandipwa/router@0.0.8" has incorrect peer dependency "@scandipwa/framework@^0.0.1".
2022-07-13T08:32:18.332Z [WARNING]: warning " > @scandipwa/scandipwa-scripts@2.4.21" has unmet peer dependency "@tilework/mosaic@0.1.4".
                                    warning " > @scandipwa/service-worker@0.0.17" has unmet peer dependency "@tilework/mosaic-craco@0.0.5".
2022-07-13T08:32:18.332Z [WARNING]: warning "workspace-aggregator-3515d3c2-d446-4911-87ee-536378390fef > @scandipwa/router > react-router@5.2.1" has unmet peer dependency "react@>=15".
                                    warning "workspace-aggregator-3515d3c2-d446-4911-87ee-536378390fef > @scandipwa/router > react-router-dom@5.3.0" has unmet peer dependency "react@>=15".
2022-07-13T08:32:18.333Z [WARNING]: warning "workspace-aggregator-3515d3c2-d446-4911-87ee-536378390fef > @scandipwa/stylelint-config > stylelint-use-logical@1.1.0" has incorrect peer dependency "stylelint@^9.6.0".
2022-07-13T08:32:18.333Z [WARNING]: warning "workspace-aggregator-3515d3c2-d446-4911-87ee-536378390fef > @scandipwa/stylelint-config > stylelint-webpack-plugin@3.2.0" has unmet peer dependency "webpack@^5.0.0".
2022-07-13T08:32:18.334Z [WARNING]: warning "workspace-aggregator-3515d3c2-d446-4911-87ee-536378390fef > @scandipwa/scandipwa-development-toolkit-core > @typescript-eslint/eslint-plugin@2.34.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
2022-07-13T08:32:18.334Z [WARNING]: warning "workspace-aggregator-3515d3c2-d446-4911-87ee-536378390fef > @scandipwa/scandipwa-development-toolkit-core > @typescript-eslint/parser@2.34.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
2022-07-13T08:32:18.334Z [WARNING]: warning "workspace-aggregator-3515d3c2-d446-4911-87ee-536378390fef > @scandipwa/router > react-router > mini-create-react-context@0.4.1" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0".
2022-07-13T08:32:18.335Z [WARNING]: warning "workspace-aggregator-3515d3c2-d446-4911-87ee-536378390fef > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-config-injectors@0.1.19" has unmet peer dependency "@babel/core@^7.14.0".
2022-07-13T08:32:18.335Z [WARNING]: warning "workspace-aggregator-3515d3c2-d446-4911-87ee-536378390fef > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-craco@0.0.5" has incorrect peer dependency "react-scripts@4.0.1".
                                    warning "workspace-aggregator-3515d3c2-d446-4911-87ee-536378390fef > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > babel-jest@26.6.3" has unmet peer dependency "@babel/core@^7.0.0".
                                    warning "workspace-aggregator-3515d3c2-d446-4911-87ee-536378390fef > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > craco-sass-resources-loader@1.1.0" has unmet peer dependency "@craco/craco@^3.3.1".
2022-07-13T08:32:18.336Z [WARNING]: warning "workspace-aggregator-3515d3c2-d446-4911-87ee-536378390fef > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > craco-sass-resources-loader@1.1.0" has incorrect peer dependency "react-scripts@^2.1.3".
                                    warning "workspace-aggregator-3515d3c2-d446-4911-87ee-536378390fef > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > progress-bar-webpack-plugin@2.1.0" has unmet peer dependency "webpack@^1.3.0 || ^2 || ^3 || ^4 || ^5".
                                    warning "workspace-aggregator-3515d3c2-d446-4911-87ee-536378390fef > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > react-scripts@4.0.3" has unmet peer dependency "react@>= 16".
                                    warning "workspace-aggregator-3515d3c2-d446-4911-87ee-536378390fef > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-config-injectors > @babel/plugin-transform-arrow-functions@7.13.0" has unmet peer dependency "@babel/core@^7.0.0-0".
                                    warning "workspace-aggregator-3515d3c2-d446-4911-87ee-536378390fef > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-config-injectors > @babel/plugin-transform-async-to-generator@7.13.0" has unmet peer dependency "@babel/core@^7.0.0-0".
                                    warning "workspace-aggregator-3515d3c2-d446-4911-87ee-536378390fef > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-config-injectors > babel-loader@8.1.0" has unmet peer dependency "@babel/core@^7.0.0".
                                    warning "workspace-aggregator-3515d3c2-d446-4911-87ee-536378390fef > @scandipwa/scandipwa-scripts > @tilework/mosaic-cra-scripts > @tilework/mosaic-config-injectors > babel-loader@8.1.0" has unmet peer dependency "webpack@>=2".
                                    warning "workspace-aggre [...]

2022-07-21 11:26 UTC, carinadues commented
Closing. The issue will be fixed by https://github.com/scandipwa/scandipwa/pull/5055

2022-07-21 11:26 UTC, closed without merging