[4710] changed the secondary light color
scandipwa/scandipwa pull request #4887
Opened 2022-06-03 11:56 UTC by NutellaON

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4710

**Problem:**
* Highlight color is blinking if user zoom first image
* Background for first image on PDP painted by Secondary color 'Highligh'
* Highlight color shown in image popup is user click on default image (if custom image is absent)

**In this PR:**
* changed the secondary light color variable to white color

2022-06-04 16:59 UTC, zans-laksa requested changes
This solution is wrong by all means.
1. You shouldn't override the variable globally just because of the single element.
2. This code will work only in non-magento mode.
3. This solution will make additional bugs.

Please remove this and try again.

2022-06-06 08:55 UTC, NutellaON reviewed
Forgot to add commit message.  
- Removed  the global style colors.
- Changed image background color.

2022-06-06 23:02 UTC, zans-laksa approved these changes

2022-07-15 11:41 UTC, carinadues commented
Will merge to test on pmrev

2022-07-15 11:41 UTC, merged