#4899 Stop scrollbar and scroller block from overriding each-others' `scrollLeft`
scandipwa/scandipwa pull request #4946
Opened 2022-06-21 15:46 UTC by neeeeecka

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4899

**Problem:**
* Scrollbar and scroller block element were overriding each-other's `scrollLeft` parameter, which caused noticeable product twitching in Safari and Firefox in Product Compare component.

**In this PR:**
* I modified `ProductCompare.continer.js` to correctly handle scroll events and ignore calls depending on whether they come from the user or function.
* I also modified `ProductCompare.component.js` to not include scrollbar inside the scrolling component, otherwise, that caused another conflict with scroll events.

2022-06-22 06:37 UTC, aleksandrakorolova commented
Still, small twitching exist if user has a lot of products in compare list
https://vimeo.com/722836634/1587898d91

2022-06-23 19:00 UTC, zans-laksa requested changes

2022-06-24 19:42 UTC, zans-laksa approved these changes

2022-06-27 06:36 UTC, aleksandrakorolova commented
FF: looks good
Safari(Version 14.1 (16611.1.21.161.3)): 
- Looks good if user has equal or less than 70 products
- Still, small twitching exist if user has equal or more than 80 products in compare list

Video:
More than 90- https://vimeo.com/724351508/2f28c8f759
±80 - https://vimeo.com/724352239/d176e64cdb

Will update Mac and Safari today and will recheck this issue on the latest Safari version again

2022-06-28 06:10 UTC, aleksandrakorolova commented
Checked issue on Safari 15.5 version - Still, small twitching exist if user has a lot of products(± 80 products) in compare list
https://vimeo.com/724745216/60a487c25c
I think we should merge this PR as it is. And I will create new task for issue for users who have >80products in compare list and some day we will fix it

2022-06-28 11:07 UTC, merged