[4974] - 'My billing and shipping are the same' isn't selected - fixed
scandipwa/scandipwa pull request #4984
Opened 2022-06-30 10:33 UTC by leonazava

**Related issue(s):**
* Fixes scandipwa/scandipwa/issues/4974

**Problem:**
* Logic in isSameShippingAddress() method sometimes would return unexpected results, preventing the 'billing and shipping are same' box from being checked when it should've been.

**In this PR:**
* fixed 'billing and shipping are same' checkbox auto-selection (BASA) on billing page reload; 
* fixed BASA if the user chose a different SM from default that's different from billing; 
* fixed BAS not being selected when it should be

2022-06-30 10:36 UTC, leonazava commented
request to QA: please test that [4716](https://github.com/scandipwa/scandipwa/pull/4716) and [4462](https://github.com/scandipwa/scandipwa/pull/4462) are still working. it was fine for me but better safe than sorry.

2022-07-01 13:42 UTC, zans-laksa requested changes

2022-07-04 06:49 UTC, leonazava commented on packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.container.js
> +            return (
done

2022-07-05 02:23 UTC, zans-laksa approved these changes

2022-07-05 19:45 UTC, Elena-Evsa commented
Oops page on cart or checkout
![image](https://user-images.githubusercontent.com/84388061/177403402-38e99500-7a98-41dc-bad8-9d2580a75dee.png)

2022-07-08 12:19 UTC, Elena-Evsa commented
Fixed
4716 - not reproducible
4462 - not reproducible

2022-07-08 12:23 UTC, merged