3731 - wrong content on page switching w/ slow internet - fixed
scandipwa/scandipwa pull request #5028
Opened 2022-07-13 10:06 UTC by leonazava

**Related issue(s):**
* Fixes candipwa/scandipwa/issues/3731

**Problem:**
* Error messages still show up once in a while.

**In this PR:**
* Made error handling more conservative so that onError method won't get called on manual request aborts

2022-07-13 12:30 UTC, aleksandrakorolova commented
1. Can reproduce issue from the task:
- URL for Men category
- Category Description for Tech category
- Products from Women category
![Screenshot 2022-07-13 at 15 21 28](https://user-images.githubusercontent.com/73526235/178732961-a7105308-37f4-4619-ab1c-296d34347ba0.png)

2.Error fetching messages don't appear **BUT** Error message 'Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'message')' appears in the console

2022-07-18 08:04 UTC, zans-laksa requested changes

2022-07-18 08:04 UTC, zans-laksa commented on packages/scandipwa/src/util/Request/QueryDispatcher.js
> +            }
Can we trust these strings? Can they change on different browsers and versions?

2022-07-18 08:04 UTC, zans-laksa commented on packages/scandipwa/src/util/Request/QueryDispatcher.js
> +            }
Maybe there is some error code available?

2022-07-18 08:04 UTC, zans-laksa commented on packages/scandipwa/src/util/Request/QueryDispatcher.js
> +            }
`REQUEST_ABORT_MESSAGE` as a substring of `REQUEST_ABORT_MESSAGE_2`.
So actually you don't need two constants, you can just search a substring.

2022-07-18 09:45 UTC, zans-laksa approved these changes

2022-07-18 13:15 UTC, aleksandrakorolova commented
1. Still can reproduce different cases:

- URL and category description are displayed for category X but products are displayed for category Y
![Screenshot 2022-07-18 at 15 55 55](https://user-images.githubusercontent.com/73526235/179516265-71771f75-c252-4ad9-b96d-60bd6b932144.png)
- URL and products are displayed for category X but category description for category Y
![Screenshot 2022-07-18 at 15 59 21](https://user-images.githubusercontent.com/73526235/179516645-9b3661c2-656a-4c46-afd9-7fe710ca6bfd.png)
- URL is displayed for category X but category description and products for category Y
![Screenshot 2022-07-18 at 16 08 52](https://user-images.githubusercontent.com/73526235/179518245-512b52d9-e50d-4e38-91c8-624be70e820f.png)

2. Fixed

2022-07-20 06:23 UTC, zans-laksa approved these changes

2022-07-20 08:35 UTC, leonazava commented
Relevant for #4974 and #3088:
Those issues are a byproduct of our caching strategy. 
I initially planned to cancel a request if a newer request was dispatched before the previous one completes. The problem is that the cache is... to fast. Getting a response from the cache only takes 2-3ms, which is way faster than a human is physically able to click on a new link to dispatch a new request and cancel an older one. 
This becomes problematic when the service worker, which sends requests to an actual server, on slow 3g takes anywhere from 200ms-6s to complete a request. A user can queue multiple uncancellable requests like that, and they all will resolve and attempt to update the app state, which leads to the behavior described in the aforementioned issues.

This PR won't solve the issues but it still has a lot of good code, reactors, adjustments, etc, so I believe we could still try to merge it.
How to test: this PR doesn't add anything new behavior-wise. As long as homepage/pdp/plp/cart/checkout work as intended, it's safe to merge.

2022-08-23 13:48 UTC, Ylmzef commented
I'm still facing with this issue in 5.3.3

2022-08-24 06:38 UTC, merged

2022-08-28 17:02 UTC, sliceem88 commented
Getting error on search with this fix:
`code: "410"
error: true
message: "Query hash is unknown"`
![image](https://user-images.githubusercontent.com/43166842/187085807-55d781f9-3e72-4c85-9da0-a6439f933156.png)

Rolled back to 5.3.3

2022-08-29 08:28 UTC, leonazava commented
@Ylmzef this PR won't fix the issues, refer to [the earlier comment](https://github.com/scandipwa/scandipwa/pull/5028#issuecomment-1189990491)

@sliceem88 Is the search result broken as well? If it's just the log, you're most probably seeing it because of better error handling and the cause of the error exists in the older versions too. There are also a few edge cases that cause the search to fail that are unrelated to this PR.

2022-08-30 02:04 UTC, Ylmzef commented
> Getting error on search with this fix: `code: "410" error: true message: "Query hash is unknown"` ![image](https://user-images.githubusercontent.com/43166842/187085807-55d781f9-3e72-4c85-9da0-a6439f933156.png)
> 
> Rolled back to 5.3.3

Same here

2022-08-31 13:59 UTC, sliceem88 commented
> @Ylmzef this PR won't fix the issues, refer to [the earlier comment](https://github.com/scandipwa/scandipwa/pull/5028#issuecomment-1189990491)
> 
> @sliceem88 Is the search result broken as well? If it's just the log, you're most probably seeing it because of better error handling and the cause of the error exists in the older versions too. There are also a few edge cases that cause the search to fail that are unrelated to this PR.

Any reason why rolled back worked ?

2022-08-31 14:51 UTC, Ylmzef commented
Yes, I rolled back to 5.3.3 and it's working fine again.

2022-09-08 12:56 UTC, Ylmzef commented
is there any progress yet? Our website not available to customers for a long time due this issue.
Maybe can you release a patch for this issue? It’s not a simple problem for live shops.

2022-09-08 13:08 UTC, leonazava commented
@Ylmzef the fix can be found [here](https://github.com/scandipwa/scandipwa/issues/5181).