fixed page rendering and added scrolling to the top on page update
scandipwa/scandipwa pull request #5136
Opened 2022-08-10 08:02 UTC by AzizKHAN030

**Related issue(s):**
* Fixes 4707

**Problem:**
* Page glitches when getting to the next page

**In this PR:**
* Fixed page rendering and scrolltop on page update

**Additional:**
* Better to test on a real device

2022-08-15 13:01 UTC, zans-laksa requested changes

2022-08-15 13:01 UTC, zans-laksa commented on packages/scandipwa/src/component/ProductList/ProductList.component.js
> +/* eslint-disable no-unused-vars */
Please remove this line, since:
1. We shouldn't disable eslint for such issues.
2. I don't see any unused variables in this PR.

2022-08-22 11:56 UTC, zans-laksa approved these changes

2024-03-23 11:48 UTC, AleksandrsKondratjevs commented
Closing due to deprecated code and no activity.

2024-03-23 11:48 UTC, closed without merging