Refactored productTabs and added global state to active product tab
scandipwa/scandipwa pull request #5361
Opened 2022-12-18 14:17 UTC by neeeeecka

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/5346

**Problem:**
* Previously, it was not possible to (Easily and properly) insert tabs between specific locations as well as it wasn't possible to change active tab's state from anywhere(Usual workaround was to add refs and call click events on tabs)

**In this PR:**
* Created global store `ProductTabsReducer` with `activeTab` property.
* Added `position` property to product tabs indicating their sorting order (Starting with 100, 200, 300, its possible to insert anywhere between these numbers).
* Refactored `ProductTabs` to move all logic to the container.
* Refactored `ProductTab` to use product `id` instead of `name` for handling click events.

2022-12-18 14:21 UTC, neeeeecka commented
Example for inserting tab at any place:
![image](https://user-images.githubusercontent.com/22796372/208303365-9201f9a3-fe89-4eb8-8c5c-b3ffdbc74bae.png)
Result:
![image](https://user-images.githubusercontent.com/22796372/208303438-b9cab8d3-a708-429e-bb7b-f5f2b10a1cac.png)
Example for setting global state:
```
export const mapDispatchToProps = (dispatch: Dispatch): ProductTabsContainerMapDispatchProps => ({
    setActiveTab: (newActiveTab) => dispatch(updateActiveTab(newActiveTab)),
});
...
Somewhere:
setActiveTab('TEST_TAB');
...
```

2022-12-22 11:57 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductTab/ProductTab.component.tsx
> +    };
How are you gonna be a plugin to it? 
As I know arrow functions not working for plugins

2022-12-22 11:59 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductTabs/ProductTabs.container.tsx
> +    render() {
Return type please everywhere

2022-12-22 12:04 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/component/ProductTabs/ProductTabs.container.tsx
> +        if (tab?.id !== prevTab?.id) {
Destruct

2022-12-22 12:06 UTC, AleksandrsKondratjevs requested changes

2022-12-22 12:06 UTC, AleksandrsKondratjevs commented on packages/scandipwa/src/store/ProductTabs/ProductTabs.reducer.ts
> +export default ProductTabsReducer;
Do we really need separate reducer for product tabs? Maybe we can move it to product store?

2023-01-03 07:14 UTC, AleksandrsKondratjevs approved these changes

2024-03-23 11:51 UTC, AleksandrsKondratjevs commented
Closing due to deprecated code and no activity.

2024-03-23 11:51 UTC, closed without merging