Perf 17
scandipwa/scandipwa pull request #5521
Opened 2024-03-11 11:01 UTC by IljaFatkulin

**Related issue(s):**
* Fixes https://scandiflow.atlassian.net/jira/software/c/projects/PERF/boards/1517?selectedIssue=PERF-17

**Problem:**
* Large CLS

**In this PR:**
* Fixed CLS for ProductPage

2024-03-14 10:24 UTC, matesich requested changes

2024-03-14 10:24 UTC, matesich commented on packages/scandipwa/src/component/Router/Router.component.tsx
> +        if (isMobile && type === 'PRODUCT' && name) {
use constant for PDP page type instead of the `'PRODUCT'`.

2024-03-14 10:24 UTC, matesich commented on packages/scandipwa/src/component/ProductActions/ProductActions.component.tsx
> +                  elem="skuAndStockPlaceholder"
elem prop value should start with uppercase

2024-03-23 12:02 UTC, AleksandrsKondratjevs approved these changes

2024-04-03 09:36 UTC, matesich approved these changes

2024-04-04 09:21 UTC, merged