Fixed cls on MyAccount page
scandipwa/scandipwa pull request #5522
Opened 2024-03-11 11:12 UTC by IljaFatkulin

**Related issue(s):**
* Fixes https://scandiflow.atlassian.net/jira/software/c/projects/PERF/boards/1517?selectedIssue=PERF-19

**Problem:**
* No placeholder for account info

**In this PR:**
* Added placeholder, fixed cls

2024-03-14 10:26 UTC, matesich requested changes

2024-03-14 10:26 UTC, matesich commented on packages/scandipwa/src/component/MyAccountDashboard/MyAccountDashboard.component.tsx
> +                <Suspense fallback={ <div block="MyAccountDashboard" elem="MyAccountCustomerTableFallback" /> }>
ideally, we should have a separate rendering method for the fallback. it will make the customizations easier.

2024-03-23 12:03 UTC, AleksandrsKondratjevs approved these changes

2024-03-26 11:00 UTC, AleksandrsKondratjevs approved these changes

2024-04-03 09:35 UTC, matesich approved these changes

2024-04-04 09:22 UTC, merged