PERF-27: Animate menu dropdowns to expand collapse on Desktop
scandipwa/scandipwa pull request #5529
Opened 2024-03-14 03:14 UTC by ahmedmwalied

**Related issue(s):**
Fixes [PERF-27](https://scandiflow.atlassian.net/browse/PERF-27)

**Problem:**
*  Adds Animate to menu dropdowns to expand collapse on Desktop

2024-03-14 10:32 UTC, matesich requested changes
as mentioned here: [PERF-22](https://github.com/scandipwa/scandipwa/pull/5525/files)
no business logic in render methods, please refactor the implementation by moving this to the container.

2024-03-20 12:46 UTC, matesich requested changes

2024-03-20 12:46 UTC, matesich commented on packages/scandipwa/src/component/Menu/Menu.component.tsx
> +            removeVisitedMenuItems(item_id);
as mentioned previously, there shouldn't be any function calls in render methods. Have you tried refactoring this implementation?

2024-03-26 10:58 UTC, AleksandrsKondratjevs approved these changes

2024-04-02 05:22 UTC, merged