Perf 24
scandipwa/scandipwa pull request #5530
Opened 2024-03-14 10:13 UTC by kamilkawasw

**Related issue(s):**
* Fixes [PERF-24](https://scandiflow.atlassian.net/browse/PERF-24)

**Problem:**
* Animate filter dropdowns on mobile

**In this PR:**
* animate filter overlay
* animate filter dropdowns
* prevent background page scroll when overlay is opened

2024-03-14 10:34 UTC, matesich requested changes

2024-03-14 10:34 UTC, matesich commented on packages/scandipwa/src/component/ExpandableContent/ExpandableContent.style.scss
> +            & > div {
better to have a proper selector for it

2024-03-19 21:04 UTC, matesitchinava approved these changes

2024-03-19 21:06 UTC, matesich approved these changes

2024-03-23 12:12 UTC, merged